package com.cleany.action;

public enum ActionType {
    OPEN_TRANSACTION,
    OPEN_CLEANING_HISTORY,
    REPEAT_CLEANING,
    REPEAT_TRANSFER,
    START_RENTAL_CLEANING,
    START_RENTAL_TRANSFER,
    OPEN_ADMIN_TRANSACTION,
    OPEN_SUPPORT_CASE
}
