package com.cleany.order;

public enum OrderEventType {
    IMPORTED,
    CREATED,
    ACCEPTED,
    REPORT_STARTED,
    PHOTO_ADDED,
    COMMENT_UPDATED,
    ONSITE_ISSUE_REPORTED,
    ISSUE_PHOTO_ADDED,
    ISSUE_REPORT_SUBMITTED,
    ISSUE_CUSTOMER_NOTIFIED,
    ISSUE_RESOLVED,
    COMPLETED,
    CANCELLED_BY_CUSTOMER,
    CANCELLED_BY_CLEANER
}
