/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountIdentity } from './AccountIdentity';
import {
    AccountIdentityFromJSON,
    AccountIdentityFromJSONTyped,
    AccountIdentityToJSON,
    AccountIdentityToJSONTyped,
} from './AccountIdentity';

/**
 * 
 * @export
 * @interface AccountIdentities
 */
export interface AccountIdentities {
    /**
     * 
     */
    identities: Array<AccountIdentity>;
}

/**
 * Check if a given object implements the AccountIdentities interface.
 */
export function instanceOfAccountIdentities(value: object): value is AccountIdentities {
    if (!('identities' in value) || value['identities'] === undefined) return false;
    return true;
}

export function AccountIdentitiesFromJSON(json: any): AccountIdentities {
    return AccountIdentitiesFromJSONTyped(json, false);
}

export function AccountIdentitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountIdentities {
    if (json == null) {
        return json;
    }
    return {
        
        'identities': ((json['identities'] as Array<any>).map(AccountIdentityFromJSON)),
    };
}

export function AccountIdentitiesToJSON(json: any): AccountIdentities {
    return AccountIdentitiesToJSONTyped(json, false);
}

export function AccountIdentitiesToJSONTyped(value?: AccountIdentities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identities': ((value['identities'] as Array<any>).map(AccountIdentityToJSON)),
    };
}

