/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApartmentPrice
 */
export interface ApartmentPrice {
    /**
     * 
     */
    type: ApartmentPriceTypeEnum;
    /**
     * 
     */
    regularPrice: number;
    /**
     * 
     */
    deepPrice: number;
}


/**
 * @export
 */
export const ApartmentPriceTypeEnum = {
    Studio: 'STUDIO',
    OnePlusOne: 'ONE_PLUS_ONE',
    TwoPlusOne: 'TWO_PLUS_ONE',
    ThreePlusOne: 'THREE_PLUS_ONE',
    FourPlusOne: 'FOUR_PLUS_ONE',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type ApartmentPriceTypeEnum = typeof ApartmentPriceTypeEnum[keyof typeof ApartmentPriceTypeEnum];


/**
 * Check if a given object implements the ApartmentPrice interface.
 */
export function instanceOfApartmentPrice(value: object): value is ApartmentPrice {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('regularPrice' in value) || value['regularPrice'] === undefined) return false;
    if (!('deepPrice' in value) || value['deepPrice'] === undefined) return false;
    return true;
}

export function ApartmentPriceFromJSON(json: any): ApartmentPrice {
    return ApartmentPriceFromJSONTyped(json, false);
}

export function ApartmentPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartmentPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'regularPrice': json['regularPrice'],
        'deepPrice': json['deepPrice'],
    };
}

export function ApartmentPriceToJSON(json: any): ApartmentPrice {
    return ApartmentPriceToJSONTyped(json, false);
}

export function ApartmentPriceToJSONTyped(value?: ApartmentPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'regularPrice': value['regularPrice'],
        'deepPrice': value['deepPrice'],
    };
}

