/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    message: string;
    /**
     * 
     */
    fieldErrors?: { [key: string]: string; };
    /**
     * 
     */
    requestId: string;
}

/**
 * Check if a given object implements the ApiError interface.
 */
export function instanceOfApiError(value: object): value is ApiError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ApiErrorFromJSON(json: any): ApiError {
    return ApiErrorFromJSONTyped(json, false);
}

export function ApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'fieldErrors': json['fieldErrors'] == null ? undefined : json['fieldErrors'],
        'requestId': json['requestId'],
    };
}

export function ApiErrorToJSON(json: any): ApiError {
    return ApiErrorToJSONTyped(json, false);
}

export function ApiErrorToJSONTyped(value?: ApiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'fieldErrors': value['fieldErrors'],
        'requestId': value['requestId'],
    };
}

