/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CleaningOrderQuote
 */
export interface CleaningOrderQuote {
    /**
     * 
     */
    basePrice: number;
    /**
     * 
     */
    customerDiscount: number;
    /**
     * 
     */
    finalCustomerPrice: number;
    /**
     * 
     */
    customerDiscountType: string;
    /**
     * 
     */
    currency: string;
}

/**
 * Check if a given object implements the CleaningOrderQuote interface.
 */
export function instanceOfCleaningOrderQuote(value: object): value is CleaningOrderQuote {
    if (!('basePrice' in value) || value['basePrice'] === undefined) return false;
    if (!('customerDiscount' in value) || value['customerDiscount'] === undefined) return false;
    if (!('finalCustomerPrice' in value) || value['finalCustomerPrice'] === undefined) return false;
    if (!('customerDiscountType' in value) || value['customerDiscountType'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CleaningOrderQuoteFromJSON(json: any): CleaningOrderQuote {
    return CleaningOrderQuoteFromJSONTyped(json, false);
}

export function CleaningOrderQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CleaningOrderQuote {
    if (json == null) {
        return json;
    }
    return {
        
        'basePrice': json['basePrice'],
        'customerDiscount': json['customerDiscount'],
        'finalCustomerPrice': json['finalCustomerPrice'],
        'customerDiscountType': json['customerDiscountType'],
        'currency': json['currency'],
    };
}

export function CleaningOrderQuoteToJSON(json: any): CleaningOrderQuote {
    return CleaningOrderQuoteToJSONTyped(json, false);
}

export function CleaningOrderQuoteToJSONTyped(value?: CleaningOrderQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'basePrice': value['basePrice'],
        'customerDiscount': value['customerDiscount'],
        'finalCustomerPrice': value['finalCustomerPrice'],
        'customerDiscountType': value['customerDiscountType'],
        'currency': value['currency'],
    };
}

