/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface CleaningRepeatReminder
 */
export interface CleaningRepeatReminder {
    /**
     * 
     */
    selection?: CleaningRepeatReminderSelectionEnum | null;
    /**
     * 
     */
    status?: CleaningRepeatReminderStatusEnum | null;
    /**
     * 
     */
    scheduledDate?: Date | null;
    /**
     * 
     */
    notifiedAt?: Date | null;
    /**
     * 
     */
    editable: boolean;
}


/**
 * @export
 */
export const CleaningRepeatReminderSelectionEnum = {
    In14Days: 'IN_14_DAYS',
    In30Days: 'IN_30_DAYS',
    DoNotRemind: 'DO_NOT_REMIND',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CleaningRepeatReminderSelectionEnum = typeof CleaningRepeatReminderSelectionEnum[keyof typeof CleaningRepeatReminderSelectionEnum];

/**
 * @export
 */
export const CleaningRepeatReminderStatusEnum = {
    Pending: 'PENDING',
    Notified: 'NOTIFIED',
    Disabled: 'DISABLED',
    Superseded: 'SUPERSEDED',
    Expired: 'EXPIRED',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CleaningRepeatReminderStatusEnum = typeof CleaningRepeatReminderStatusEnum[keyof typeof CleaningRepeatReminderStatusEnum];


/**
 * Check if a given object implements the CleaningRepeatReminder interface.
 */
export function instanceOfCleaningRepeatReminder(value: object): value is CleaningRepeatReminder {
    if (!('editable' in value) || value['editable'] === undefined) return false;
    return true;
}

export function CleaningRepeatReminderFromJSON(json: any): CleaningRepeatReminder {
    return CleaningRepeatReminderFromJSONTyped(json, false);
}

export function CleaningRepeatReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): CleaningRepeatReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'selection': json['selection'] === undefined ? undefined : json['selection'] === null ? null : json['selection'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
        'scheduledDate': json['scheduledDate'] === undefined ? undefined : json['scheduledDate'] === null ? null : (parseDate(json['scheduledDate'])),
        'notifiedAt': json['notifiedAt'] === undefined ? undefined : json['notifiedAt'] === null ? null : (parseDateTime(json['notifiedAt'])),
        'editable': json['editable'],
    };
}

export function CleaningRepeatReminderToJSON(json: any): CleaningRepeatReminder {
    return CleaningRepeatReminderToJSONTyped(json, false);
}

export function CleaningRepeatReminderToJSONTyped(value?: CleaningRepeatReminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selection': value['selection'],
        'status': value['status'],
        'scheduledDate': value['scheduledDate'] == null ? value['scheduledDate'] : serializeDate(value['scheduledDate']),
        'notifiedAt': value['notifiedAt'] == null ? value['notifiedAt'] : serializeDateTime(value['notifiedAt']),
        'editable': value['editable'],
    };
}

