/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApartmentPrice } from './ApartmentPrice';
import {
    ApartmentPriceFromJSON,
    ApartmentPriceFromJSONTyped,
    ApartmentPriceToJSON,
    ApartmentPriceToJSONTyped,
} from './ApartmentPrice';

/**
 * 
 * @export
 * @interface CleaningConfiguration
 */
export interface CleaningConfiguration {
    /**
     * 
     */
    areas: Array<CleaningConfigurationAreasEnum>;
    /**
     * 
     */
    apartmentTypes: Array<ApartmentPrice>;
    /**
     * 
     */
    duplexSurcharges: { [key: string]: number; };
    /**
     * 
     */
    bookingDaysAhead: number;
    /**
     * 
     */
    currency: string;
}


/**
 * @export
 */
export const CleaningConfigurationAreasEnum = {
    Mahmutlar: 'MAHMUTLAR',
    Kargicak: 'KARGICAK',
    Kestel: 'KESTEL',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CleaningConfigurationAreasEnum = typeof CleaningConfigurationAreasEnum[keyof typeof CleaningConfigurationAreasEnum];


/**
 * Check if a given object implements the CleaningConfiguration interface.
 */
export function instanceOfCleaningConfiguration(value: object): value is CleaningConfiguration {
    if (!('areas' in value) || value['areas'] === undefined) return false;
    if (!('apartmentTypes' in value) || value['apartmentTypes'] === undefined) return false;
    if (!('duplexSurcharges' in value) || value['duplexSurcharges'] === undefined) return false;
    if (!('bookingDaysAhead' in value) || value['bookingDaysAhead'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CleaningConfigurationFromJSON(json: any): CleaningConfiguration {
    return CleaningConfigurationFromJSONTyped(json, false);
}

export function CleaningConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CleaningConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'areas': json['areas'],
        'apartmentTypes': ((json['apartmentTypes'] as Array<any>).map(ApartmentPriceFromJSON)),
        'duplexSurcharges': json['duplexSurcharges'],
        'bookingDaysAhead': json['bookingDaysAhead'],
        'currency': json['currency'],
    };
}

export function CleaningConfigurationToJSON(json: any): CleaningConfiguration {
    return CleaningConfigurationToJSONTyped(json, false);
}

export function CleaningConfigurationToJSONTyped(value?: CleaningConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areas': value['areas'],
        'apartmentTypes': ((value['apartmentTypes'] as Array<any>).map(ApartmentPriceToJSON)),
        'duplexSurcharges': value['duplexSurcharges'],
        'bookingDaysAhead': value['bookingDaysAhead'],
        'currency': value['currency'],
    };
}

