/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CleaningRepeatReminderRequest
 */
export interface CleaningRepeatReminderRequest {
    /**
     * 
     */
    selection: CleaningRepeatReminderRequestSelectionEnum;
}


/**
 * @export
 */
export const CleaningRepeatReminderRequestSelectionEnum = {
    In14Days: 'IN_14_DAYS',
    In30Days: 'IN_30_DAYS',
    DoNotRemind: 'DO_NOT_REMIND',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CleaningRepeatReminderRequestSelectionEnum = typeof CleaningRepeatReminderRequestSelectionEnum[keyof typeof CleaningRepeatReminderRequestSelectionEnum];


/**
 * Check if a given object implements the CleaningRepeatReminderRequest interface.
 */
export function instanceOfCleaningRepeatReminderRequest(value: object): value is CleaningRepeatReminderRequest {
    if (!('selection' in value) || value['selection'] === undefined) return false;
    return true;
}

export function CleaningRepeatReminderRequestFromJSON(json: any): CleaningRepeatReminderRequest {
    return CleaningRepeatReminderRequestFromJSONTyped(json, false);
}

export function CleaningRepeatReminderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CleaningRepeatReminderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'selection': json['selection'],
    };
}

export function CleaningRepeatReminderRequestToJSON(json: any): CleaningRepeatReminderRequest {
    return CleaningRepeatReminderRequestToJSONTyped(json, false);
}

export function CleaningRepeatReminderRequestToJSONTyped(value?: CleaningRepeatReminderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selection': value['selection'],
    };
}

