/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientConfiguration
 */
export interface ClientConfiguration {
    /**
     * 
     */
    environment: string;
    /**
     * 
     */
    iosApplicationId: string;
    /**
     * 
     */
    androidApplicationId: string;
    /**
     * 
     */
    minimumIosVersion: string;
    /**
     * 
     */
    minimumAndroidVersion: string;
    /**
     * 
     */
    apiRevision: string;
}

/**
 * Check if a given object implements the ClientConfiguration interface.
 */
export function instanceOfClientConfiguration(value: object): value is ClientConfiguration {
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('iosApplicationId' in value) || value['iosApplicationId'] === undefined) return false;
    if (!('androidApplicationId' in value) || value['androidApplicationId'] === undefined) return false;
    if (!('minimumIosVersion' in value) || value['minimumIosVersion'] === undefined) return false;
    if (!('minimumAndroidVersion' in value) || value['minimumAndroidVersion'] === undefined) return false;
    if (!('apiRevision' in value) || value['apiRevision'] === undefined) return false;
    return true;
}

export function ClientConfigurationFromJSON(json: any): ClientConfiguration {
    return ClientConfigurationFromJSONTyped(json, false);
}

export function ClientConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'environment': json['environment'],
        'iosApplicationId': json['iosApplicationId'],
        'androidApplicationId': json['androidApplicationId'],
        'minimumIosVersion': json['minimumIosVersion'],
        'minimumAndroidVersion': json['minimumAndroidVersion'],
        'apiRevision': json['apiRevision'],
    };
}

export function ClientConfigurationToJSON(json: any): ClientConfiguration {
    return ClientConfigurationToJSONTyped(json, false);
}

export function ClientConfigurationToJSONTyped(value?: ClientConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'environment': value['environment'],
        'iosApplicationId': value['iosApplicationId'],
        'androidApplicationId': value['androidApplicationId'],
        'minimumIosVersion': value['minimumIosVersion'],
        'minimumAndroidVersion': value['minimumAndroidVersion'],
        'apiRevision': value['apiRevision'],
    };
}

