/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunicationEndpoint
 */
export interface CommunicationEndpoint {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    type: CommunicationEndpointTypeEnum;
    /**
     * 
     */
    platform: CommunicationEndpointPlatformEnum;
    /**
     * 
     */
    installationId?: string | null;
    /**
     * 
     */
    active: boolean;
}


/**
 * @export
 */
export const CommunicationEndpointTypeEnum = {
    Fcm: 'FCM',
    Telegram: 'TELEGRAM',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CommunicationEndpointTypeEnum = typeof CommunicationEndpointTypeEnum[keyof typeof CommunicationEndpointTypeEnum];

/**
 * @export
 */
export const CommunicationEndpointPlatformEnum = {
    Ios: 'IOS',
    Android: 'ANDROID',
    Telegram: 'TELEGRAM',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CommunicationEndpointPlatformEnum = typeof CommunicationEndpointPlatformEnum[keyof typeof CommunicationEndpointPlatformEnum];


/**
 * Check if a given object implements the CommunicationEndpoint interface.
 */
export function instanceOfCommunicationEndpoint(value: object): value is CommunicationEndpoint {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function CommunicationEndpointFromJSON(json: any): CommunicationEndpoint {
    return CommunicationEndpointFromJSONTyped(json, false);
}

export function CommunicationEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunicationEndpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'platform': json['platform'],
        'installationId': json['installationId'] === undefined ? undefined : json['installationId'] === null ? null : json['installationId'],
        'active': json['active'],
    };
}

export function CommunicationEndpointToJSON(json: any): CommunicationEndpoint {
    return CommunicationEndpointToJSONTyped(json, false);
}

export function CommunicationEndpointToJSONTyped(value?: CommunicationEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'platform': value['platform'],
        'installationId': value['installationId'],
        'active': value['active'],
    };
}

