/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RentalTermType } from './RentalTermType';
import {
    RentalTermTypeFromJSON,
    RentalTermTypeFromJSONTyped,
    RentalTermTypeToJSON,
    RentalTermTypeToJSONTyped,
} from './RentalTermType';

/**
 * 
 * @export
 * @interface CreateRentalBookingRequest
 */
export interface CreateRentalBookingRequest {
    /**
     * 
     */
    propertyId: number;
    /**
     * 
     */
    termType: RentalTermType;
    /**
     * 
     */
    checkInDate: Date;
    /**
     * 
     */
    checkOutDate?: Date | null;
    /**
     * 
     */
    months?: number | null;
    /**
     * 
     */
    guests: number;
    /**
     * 
     */
    phone: string;
    /**
     * 
     */
    comment?: string | null;
    /**
     * Legacy optimistic-price input; response money always uses the Money object.
     */
    expectedTotalPrice: number;
    /**
     * 
     */
    expectedCurrency: string;
    /**
     * 
     */
    searchExecutionId?: string | null;
}



/**
 * Check if a given object implements the CreateRentalBookingRequest interface.
 */
export function instanceOfCreateRentalBookingRequest(value: object): value is CreateRentalBookingRequest {
    if (!('propertyId' in value) || value['propertyId'] === undefined) return false;
    if (!('termType' in value) || value['termType'] === undefined) return false;
    if (!('checkInDate' in value) || value['checkInDate'] === undefined) return false;
    if (!('guests' in value) || value['guests'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('expectedTotalPrice' in value) || value['expectedTotalPrice'] === undefined) return false;
    if (!('expectedCurrency' in value) || value['expectedCurrency'] === undefined) return false;
    return true;
}

export function CreateRentalBookingRequestFromJSON(json: any): CreateRentalBookingRequest {
    return CreateRentalBookingRequestFromJSONTyped(json, false);
}

export function CreateRentalBookingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRentalBookingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['propertyId'],
        'termType': RentalTermTypeFromJSON(json['termType']),
        'checkInDate': (json['checkInDate'] == null ? json['checkInDate'] : parseDate(json['checkInDate'])),
        'checkOutDate': json['checkOutDate'] === undefined ? undefined : json['checkOutDate'] === null ? null : (parseDate(json['checkOutDate'])),
        'months': json['months'] === undefined ? undefined : json['months'] === null ? null : json['months'],
        'guests': json['guests'],
        'phone': json['phone'],
        'comment': json['comment'] === undefined ? undefined : json['comment'] === null ? null : json['comment'],
        'expectedTotalPrice': json['expectedTotalPrice'],
        'expectedCurrency': json['expectedCurrency'],
        'searchExecutionId': json['searchExecutionId'] === undefined ? undefined : json['searchExecutionId'] === null ? null : json['searchExecutionId'],
    };
}

export function CreateRentalBookingRequestToJSON(json: any): CreateRentalBookingRequest {
    return CreateRentalBookingRequestToJSONTyped(json, false);
}

export function CreateRentalBookingRequestToJSONTyped(value?: CreateRentalBookingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'propertyId': value['propertyId'],
        'termType': RentalTermTypeToJSON(value['termType']),
        'checkInDate': value['checkInDate'] == null ? value['checkInDate'] : serializeDate(value['checkInDate']),
        'checkOutDate': value['checkOutDate'] == null ? value['checkOutDate'] : serializeDate(value['checkOutDate']),
        'months': value['months'],
        'guests': value['guests'],
        'phone': value['phone'],
        'comment': value['comment'],
        'expectedTotalPrice': value['expectedTotalPrice'],
        'expectedCurrency': value['expectedCurrency'],
        'searchExecutionId': value['searchExecutionId'],
    };
}

