/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTransactionFeedbackRequest
 */
export interface CreateTransactionFeedbackRequest {
    /**
     * 
     */
    service: CreateTransactionFeedbackRequestServiceEnum;
    /**
     * 
     */
    sourceEntityId: number;
    /**
     * 
     */
    outcome: CreateTransactionFeedbackRequestOutcomeEnum;
    /**
     * 
     */
    category?: CreateTransactionFeedbackRequestCategoryEnum | null;
    /**
     * 
     */
    comment?: string | null;
}


/**
 * @export
 */
export const CreateTransactionFeedbackRequestServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateTransactionFeedbackRequestServiceEnum = typeof CreateTransactionFeedbackRequestServiceEnum[keyof typeof CreateTransactionFeedbackRequestServiceEnum];

/**
 * @export
 */
export const CreateTransactionFeedbackRequestOutcomeEnum = {
    Good: 'GOOD',
    Problem: 'PROBLEM',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateTransactionFeedbackRequestOutcomeEnum = typeof CreateTransactionFeedbackRequestOutcomeEnum[keyof typeof CreateTransactionFeedbackRequestOutcomeEnum];

/**
 * @export
 */
export const CreateTransactionFeedbackRequestCategoryEnum = {
    ProviderLate: 'PROVIDER_LATE',
    ProviderNoShow: 'PROVIDER_NO_SHOW',
    QualityProblem: 'QUALITY_PROBLEM',
    BookingProblem: 'BOOKING_PROBLEM',
    Other: 'OTHER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateTransactionFeedbackRequestCategoryEnum = typeof CreateTransactionFeedbackRequestCategoryEnum[keyof typeof CreateTransactionFeedbackRequestCategoryEnum];


/**
 * Check if a given object implements the CreateTransactionFeedbackRequest interface.
 */
export function instanceOfCreateTransactionFeedbackRequest(value: object): value is CreateTransactionFeedbackRequest {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('sourceEntityId' in value) || value['sourceEntityId'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    return true;
}

export function CreateTransactionFeedbackRequestFromJSON(json: any): CreateTransactionFeedbackRequest {
    return CreateTransactionFeedbackRequestFromJSONTyped(json, false);
}

export function CreateTransactionFeedbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionFeedbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'sourceEntityId': json['sourceEntityId'],
        'outcome': json['outcome'],
        'category': json['category'] === undefined ? undefined : json['category'] === null ? null : json['category'],
        'comment': json['comment'] === undefined ? undefined : json['comment'] === null ? null : json['comment'],
    };
}

export function CreateTransactionFeedbackRequestToJSON(json: any): CreateTransactionFeedbackRequest {
    return CreateTransactionFeedbackRequestToJSONTyped(json, false);
}

export function CreateTransactionFeedbackRequestToJSONTyped(value?: CreateTransactionFeedbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'sourceEntityId': value['sourceEntityId'],
        'outcome': value['outcome'],
        'category': value['category'],
        'comment': value['comment'],
    };
}

