/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdentityProvider } from './IdentityProvider';
import {
    IdentityProviderFromJSON,
    IdentityProviderFromJSONTyped,
    IdentityProviderToJSON,
    IdentityProviderToJSONTyped,
} from './IdentityProvider';

/**
 * 
 * @export
 * @interface CreateNativeChallengeRequest
 */
export interface CreateNativeChallengeRequest {
    /**
     * 
     */
    provider: IdentityProvider;
    /**
     * 
     */
    clientType: CreateNativeChallengeRequestClientTypeEnum;
}


/**
 * @export
 */
export const CreateNativeChallengeRequestClientTypeEnum = {
    Ios: 'IOS',
    Android: 'ANDROID',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateNativeChallengeRequestClientTypeEnum = typeof CreateNativeChallengeRequestClientTypeEnum[keyof typeof CreateNativeChallengeRequestClientTypeEnum];


/**
 * Check if a given object implements the CreateNativeChallengeRequest interface.
 */
export function instanceOfCreateNativeChallengeRequest(value: object): value is CreateNativeChallengeRequest {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('clientType' in value) || value['clientType'] === undefined) return false;
    return true;
}

export function CreateNativeChallengeRequestFromJSON(json: any): CreateNativeChallengeRequest {
    return CreateNativeChallengeRequestFromJSONTyped(json, false);
}

export function CreateNativeChallengeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNativeChallengeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': IdentityProviderFromJSON(json['provider']),
        'clientType': json['clientType'],
    };
}

export function CreateNativeChallengeRequestToJSON(json: any): CreateNativeChallengeRequest {
    return CreateNativeChallengeRequestToJSONTyped(json, false);
}

export function CreateNativeChallengeRequestToJSONTyped(value?: CreateNativeChallengeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': IdentityProviderToJSON(value['provider']),
        'clientType': value['clientType'],
    };
}

