/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCleaningOrderRequest
 */
export interface CreateCleaningOrderRequest {
    /**
     * 
     */
    area: CreateCleaningOrderRequestAreaEnum;
    /**
     * 
     */
    address: string;
    /**
     * 
     */
    apartmentType: CreateCleaningOrderRequestApartmentTypeEnum;
    /**
     * 
     */
    duplex: boolean;
    /**
     * 
     */
    cleaningType: CreateCleaningOrderRequestCleaningTypeEnum;
    /**
     * 
     */
    requestedDate: Date;
    /**
     * 
     */
    phone: string;
    /**
     * 
     */
    comment?: string | null;
    /**
     * 
     */
    referralCode?: string | null;
    /**
     * 
     */
    rentalCleaningPromoCode?: string | null;
    /**
     * 
     */
    repeatFromOrderId?: number | null;
}


/**
 * @export
 */
export const CreateCleaningOrderRequestAreaEnum = {
    Mahmutlar: 'MAHMUTLAR',
    Kargicak: 'KARGICAK',
    Kestel: 'KESTEL',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateCleaningOrderRequestAreaEnum = typeof CreateCleaningOrderRequestAreaEnum[keyof typeof CreateCleaningOrderRequestAreaEnum];

/**
 * @export
 */
export const CreateCleaningOrderRequestApartmentTypeEnum = {
    Studio: 'STUDIO',
    OnePlusOne: 'ONE_PLUS_ONE',
    TwoPlusOne: 'TWO_PLUS_ONE',
    ThreePlusOne: 'THREE_PLUS_ONE',
    FourPlusOne: 'FOUR_PLUS_ONE',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateCleaningOrderRequestApartmentTypeEnum = typeof CreateCleaningOrderRequestApartmentTypeEnum[keyof typeof CreateCleaningOrderRequestApartmentTypeEnum];

/**
 * @export
 */
export const CreateCleaningOrderRequestCleaningTypeEnum = {
    Regular: 'REGULAR',
    Deep: 'DEEP',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateCleaningOrderRequestCleaningTypeEnum = typeof CreateCleaningOrderRequestCleaningTypeEnum[keyof typeof CreateCleaningOrderRequestCleaningTypeEnum];


/**
 * Check if a given object implements the CreateCleaningOrderRequest interface.
 */
export function instanceOfCreateCleaningOrderRequest(value: object): value is CreateCleaningOrderRequest {
    if (!('area' in value) || value['area'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('apartmentType' in value) || value['apartmentType'] === undefined) return false;
    if (!('duplex' in value) || value['duplex'] === undefined) return false;
    if (!('cleaningType' in value) || value['cleaningType'] === undefined) return false;
    if (!('requestedDate' in value) || value['requestedDate'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function CreateCleaningOrderRequestFromJSON(json: any): CreateCleaningOrderRequest {
    return CreateCleaningOrderRequestFromJSONTyped(json, false);
}

export function CreateCleaningOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCleaningOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'area': json['area'],
        'address': json['address'],
        'apartmentType': json['apartmentType'],
        'duplex': json['duplex'],
        'cleaningType': json['cleaningType'],
        'requestedDate': (json['requestedDate'] == null ? json['requestedDate'] : parseDate(json['requestedDate'])),
        'phone': json['phone'],
        'comment': json['comment'] === undefined ? undefined : json['comment'] === null ? null : json['comment'],
        'referralCode': json['referralCode'] === undefined ? undefined : json['referralCode'] === null ? null : json['referralCode'],
        'rentalCleaningPromoCode': json['rentalCleaningPromoCode'] === undefined ? undefined : json['rentalCleaningPromoCode'] === null ? null : json['rentalCleaningPromoCode'],
        'repeatFromOrderId': json['repeatFromOrderId'] === undefined ? undefined : json['repeatFromOrderId'] === null ? null : json['repeatFromOrderId'],
    };
}

export function CreateCleaningOrderRequestToJSON(json: any): CreateCleaningOrderRequest {
    return CreateCleaningOrderRequestToJSONTyped(json, false);
}

export function CreateCleaningOrderRequestToJSONTyped(value?: CreateCleaningOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'area': value['area'],
        'address': value['address'],
        'apartmentType': value['apartmentType'],
        'duplex': value['duplex'],
        'cleaningType': value['cleaningType'],
        'requestedDate': value['requestedDate'] == null ? value['requestedDate'] : serializeDate(value['requestedDate']),
        'phone': value['phone'],
        'comment': value['comment'],
        'referralCode': value['referralCode'],
        'rentalCleaningPromoCode': value['rentalCleaningPromoCode'],
        'repeatFromOrderId': value['repeatFromOrderId'],
    };
}

