/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RentalTransferSourceRequest } from './RentalTransferSourceRequest';
import {
    RentalTransferSourceRequestFromJSON,
    RentalTransferSourceRequestFromJSONTyped,
    RentalTransferSourceRequestToJSON,
    RentalTransferSourceRequestToJSONTyped,
} from './RentalTransferSourceRequest';

/**
 * 
 * @export
 * @interface CreateTransferBookingRequest
 */
export interface CreateTransferBookingRequest {
    /**
     * 
     */
    direction: CreateTransferBookingRequestDirectionEnum;
    /**
     * 
     */
    airportId: number;
    /**
     * 
     */
    vehicleTypeId: number;
    /**
     * 
     */
    pickupDate: Date;
    /**
     * 
     */
    pickupTime: string;
    /**
     * 
     */
    address: string;
    /**
     * 
     */
    passengerCount: number;
    /**
     * 
     */
    luggageCount: number;
    /**
     * 
     */
    flightNumber?: string | null;
    /**
     * 
     */
    scheduledArrivalTime?: string | null;
    /**
     * 
     */
    phone: string;
    /**
     * 
     */
    comment?: string | null;
    /**
     * 
     */
    repeatFromBookingId?: number | null;
    /**
     * 
     */
    rentalSource?: RentalTransferSourceRequest | null;
    /**
     * 
     */
    benefit?: CreateTransferBookingRequestBenefitEnum | null;
}


/**
 * @export
 */
export const CreateTransferBookingRequestDirectionEnum = {
    ToAirport: 'TO_AIRPORT',
    FromAirport: 'FROM_AIRPORT',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateTransferBookingRequestDirectionEnum = typeof CreateTransferBookingRequestDirectionEnum[keyof typeof CreateTransferBookingRequestDirectionEnum];

/**
 * @export
 */
export const CreateTransferBookingRequestBenefitEnum = {
    RentalFirstTransfer: 'RENTAL_FIRST_TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateTransferBookingRequestBenefitEnum = typeof CreateTransferBookingRequestBenefitEnum[keyof typeof CreateTransferBookingRequestBenefitEnum];


/**
 * Check if a given object implements the CreateTransferBookingRequest interface.
 */
export function instanceOfCreateTransferBookingRequest(value: object): value is CreateTransferBookingRequest {
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('airportId' in value) || value['airportId'] === undefined) return false;
    if (!('vehicleTypeId' in value) || value['vehicleTypeId'] === undefined) return false;
    if (!('pickupDate' in value) || value['pickupDate'] === undefined) return false;
    if (!('pickupTime' in value) || value['pickupTime'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('passengerCount' in value) || value['passengerCount'] === undefined) return false;
    if (!('luggageCount' in value) || value['luggageCount'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function CreateTransferBookingRequestFromJSON(json: any): CreateTransferBookingRequest {
    return CreateTransferBookingRequestFromJSONTyped(json, false);
}

export function CreateTransferBookingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransferBookingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'direction': json['direction'],
        'airportId': json['airportId'],
        'vehicleTypeId': json['vehicleTypeId'],
        'pickupDate': (json['pickupDate'] == null ? json['pickupDate'] : parseDate(json['pickupDate'])),
        'pickupTime': json['pickupTime'],
        'address': json['address'],
        'passengerCount': json['passengerCount'],
        'luggageCount': json['luggageCount'],
        'flightNumber': json['flightNumber'] === undefined ? undefined : json['flightNumber'] === null ? null : json['flightNumber'],
        'scheduledArrivalTime': json['scheduledArrivalTime'] === undefined ? undefined : json['scheduledArrivalTime'] === null ? null : json['scheduledArrivalTime'],
        'phone': json['phone'],
        'comment': json['comment'] === undefined ? undefined : json['comment'] === null ? null : json['comment'],
        'repeatFromBookingId': json['repeatFromBookingId'] === undefined ? undefined : json['repeatFromBookingId'] === null ? null : json['repeatFromBookingId'],
        'rentalSource': json['rentalSource'] === undefined ? undefined : json['rentalSource'] === null ? null : RentalTransferSourceRequestFromJSON(json['rentalSource']),
        'benefit': json['benefit'] === undefined ? undefined : json['benefit'] === null ? null : json['benefit'],
    };
}

export function CreateTransferBookingRequestToJSON(json: any): CreateTransferBookingRequest {
    return CreateTransferBookingRequestToJSONTyped(json, false);
}

export function CreateTransferBookingRequestToJSONTyped(value?: CreateTransferBookingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'direction': value['direction'],
        'airportId': value['airportId'],
        'vehicleTypeId': value['vehicleTypeId'],
        'pickupDate': value['pickupDate'] == null ? value['pickupDate'] : serializeDate(value['pickupDate']),
        'pickupTime': value['pickupTime'],
        'address': value['address'],
        'passengerCount': value['passengerCount'],
        'luggageCount': value['luggageCount'],
        'flightNumber': value['flightNumber'],
        'scheduledArrivalTime': value['scheduledArrivalTime'],
        'phone': value['phone'],
        'comment': value['comment'],
        'repeatFromBookingId': value['repeatFromBookingId'],
        'rentalSource': RentalTransferSourceRequestToJSON(value['rentalSource']),
        'benefit': value['benefit'],
    };
}

