/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSupportCaseRequest
 */
export interface CreateSupportCaseRequest {
    /**
     * 
     */
    service: CreateSupportCaseRequestServiceEnum;
    /**
     * 
     */
    sourceEntityId: number;
    /**
     * 
     */
    category: CreateSupportCaseRequestCategoryEnum;
    /**
     * 
     */
    description?: string | null;
}


/**
 * @export
 */
export const CreateSupportCaseRequestServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateSupportCaseRequestServiceEnum = typeof CreateSupportCaseRequestServiceEnum[keyof typeof CreateSupportCaseRequestServiceEnum];

/**
 * @export
 */
export const CreateSupportCaseRequestCategoryEnum = {
    ProviderLate: 'PROVIDER_LATE',
    ProviderNoShow: 'PROVIDER_NO_SHOW',
    QualityProblem: 'QUALITY_PROBLEM',
    BookingProblem: 'BOOKING_PROBLEM',
    Other: 'OTHER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CreateSupportCaseRequestCategoryEnum = typeof CreateSupportCaseRequestCategoryEnum[keyof typeof CreateSupportCaseRequestCategoryEnum];


/**
 * Check if a given object implements the CreateSupportCaseRequest interface.
 */
export function instanceOfCreateSupportCaseRequest(value: object): value is CreateSupportCaseRequest {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('sourceEntityId' in value) || value['sourceEntityId'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function CreateSupportCaseRequestFromJSON(json: any): CreateSupportCaseRequest {
    return CreateSupportCaseRequestFromJSONTyped(json, false);
}

export function CreateSupportCaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSupportCaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'sourceEntityId': json['sourceEntityId'],
        'category': json['category'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
    };
}

export function CreateSupportCaseRequestToJSON(json: any): CreateSupportCaseRequest {
    return CreateSupportCaseRequestToJSONTyped(json, false);
}

export function CreateSupportCaseRequestToJSONTyped(value?: CreateSupportCaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'sourceEntityId': value['sourceEntityId'],
        'category': value['category'],
        'description': value['description'],
    };
}

