/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdentityProvider } from './IdentityProvider';
import {
    IdentityProviderFromJSON,
    IdentityProviderFromJSONTyped,
    IdentityProviderToJSON,
    IdentityProviderToJSONTyped,
} from './IdentityProvider';

/**
 * 
 * @export
 * @interface CreateIdentityLinkRequest
 */
export interface CreateIdentityLinkRequest {
    /**
     * 
     */
    provider: IdentityProvider;
}



/**
 * Check if a given object implements the CreateIdentityLinkRequest interface.
 */
export function instanceOfCreateIdentityLinkRequest(value: object): value is CreateIdentityLinkRequest {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function CreateIdentityLinkRequestFromJSON(json: any): CreateIdentityLinkRequest {
    return CreateIdentityLinkRequestFromJSONTyped(json, false);
}

export function CreateIdentityLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIdentityLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': IdentityProviderFromJSON(json['provider']),
    };
}

export function CreateIdentityLinkRequestToJSON(json: any): CreateIdentityLinkRequest {
    return CreateIdentityLinkRequestToJSONTyped(json, false);
}

export function CreateIdentityLinkRequestToJSONTyped(value?: CreateIdentityLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': IdentityProviderToJSON(value['provider']),
    };
}

