/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';

/**
 * 
 * @export
 * @interface CreatedTransaction
 */
export interface CreatedTransaction {
    [key: string]: any | any;
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    money: Money;
}

/**
 * Check if a given object implements the CreatedTransaction interface.
 */
export function instanceOfCreatedTransaction(value: object): value is CreatedTransaction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('money' in value) || value['money'] === undefined) return false;
    return true;
}

export function CreatedTransactionFromJSON(json: any): CreatedTransaction {
    return CreatedTransactionFromJSONTyped(json, false);
}

export function CreatedTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedTransaction {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'money': MoneyFromJSON(json['money']),
    };
}

export function CreatedTransactionToJSON(json: any): CreatedTransaction {
    return CreatedTransactionToJSONTyped(json, false);
}

export function CreatedTransactionToJSONTyped(value?: CreatedTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'money': MoneyToJSON(value['money']),
    };
}

