/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginProviders } from './LoginProviders';
import {
    LoginProvidersFromJSON,
    LoginProvidersFromJSONTyped,
    LoginProvidersToJSON,
    LoginProvidersToJSONTyped,
} from './LoginProviders';
import type { IdentityProvider } from './IdentityProvider';
import {
    IdentityProviderFromJSON,
    IdentityProviderFromJSONTyped,
    IdentityProviderToJSON,
    IdentityProviderToJSONTyped,
} from './IdentityProvider';

/**
 * 
 * @export
 * @interface CurrentAuthentication
 */
export interface CurrentAuthentication {
    /**
     * 
     */
    authenticated: boolean;
    /**
     * 
     */
    customerId?: number | null;
    /**
     * 
     */
    displayName?: string | null;
    /**
     * 
     */
    provider?: IdentityProvider | null;
    /**
     * 
     */
    roles: Set<CurrentAuthenticationRolesEnum>;
    /**
     * 
     */
    loginProviders: LoginProviders;
}


/**
 * @export
 */
export const CurrentAuthenticationRolesEnum = {
    Admin: 'ADMIN',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CurrentAuthenticationRolesEnum = typeof CurrentAuthenticationRolesEnum[keyof typeof CurrentAuthenticationRolesEnum];


/**
 * Check if a given object implements the CurrentAuthentication interface.
 */
export function instanceOfCurrentAuthentication(value: object): value is CurrentAuthentication {
    if (!('authenticated' in value) || value['authenticated'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('loginProviders' in value) || value['loginProviders'] === undefined) return false;
    return true;
}

export function CurrentAuthenticationFromJSON(json: any): CurrentAuthentication {
    return CurrentAuthenticationFromJSONTyped(json, false);
}

export function CurrentAuthenticationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentAuthentication {
    if (json == null) {
        return json;
    }
    return {
        
        'authenticated': json['authenticated'],
        'customerId': json['customerId'] === undefined ? undefined : json['customerId'] === null ? null : json['customerId'],
        'displayName': json['displayName'] === undefined ? undefined : json['displayName'] === null ? null : json['displayName'],
        'provider': json['provider'] === undefined ? undefined : json['provider'] === null ? null : IdentityProviderFromJSON(json['provider']),
        'roles': new Set(json['roles']),
        'loginProviders': LoginProvidersFromJSON(json['loginProviders']),
    };
}

export function CurrentAuthenticationToJSON(json: any): CurrentAuthentication {
    return CurrentAuthenticationToJSONTyped(json, false);
}

export function CurrentAuthenticationToJSONTyped(value?: CurrentAuthentication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authenticated': value['authenticated'],
        'customerId': value['customerId'],
        'displayName': value['displayName'],
        'provider': IdentityProviderToJSON(value['provider']),
        'roles': Array.from(value['roles'] as Set<any>),
        'loginProviders': LoginProvidersToJSON(value['loginProviders']),
    };
}

