/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerActivityItem } from './CustomerActivityItem';
import {
    CustomerActivityItemFromJSON,
    CustomerActivityItemFromJSONTyped,
    CustomerActivityItemToJSON,
    CustomerActivityItemToJSONTyped,
} from './CustomerActivityItem';

/**
 * 
 * @export
 * @interface CustomerActivity
 */
export interface CustomerActivity {
    /**
     * 
     */
    activeAndUpcoming: Array<CustomerActivityItem>;
    /**
     * 
     */
    history: Array<CustomerActivityItem>;
}

/**
 * Check if a given object implements the CustomerActivity interface.
 */
export function instanceOfCustomerActivity(value: object): value is CustomerActivity {
    if (!('activeAndUpcoming' in value) || value['activeAndUpcoming'] === undefined) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    return true;
}

export function CustomerActivityFromJSON(json: any): CustomerActivity {
    return CustomerActivityFromJSONTyped(json, false);
}

export function CustomerActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'activeAndUpcoming': ((json['activeAndUpcoming'] as Array<any>).map(CustomerActivityItemFromJSON)),
        'history': ((json['history'] as Array<any>).map(CustomerActivityItemFromJSON)),
    };
}

export function CustomerActivityToJSON(json: any): CustomerActivity {
    return CustomerActivityToJSONTyped(json, false);
}

export function CustomerActivityToJSONTyped(value?: CustomerActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeAndUpcoming': ((value['activeAndUpcoming'] as Array<any>).map(CustomerActivityItemToJSON)),
        'history': ((value['history'] as Array<any>).map(CustomerActivityItemToJSON)),
    };
}

