/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { ActionTarget } from './ActionTarget';
import {
    ActionTargetFromJSON,
    ActionTargetFromJSONTyped,
    ActionTargetToJSON,
    ActionTargetToJSONTyped,
} from './ActionTarget';

/**
 * 
 * @export
 * @interface CustomerActivityItem
 */
export interface CustomerActivityItem {
    /**
     * 
     */
    service: CustomerActivityItemServiceEnum;
    /**
     * 
     */
    entityId: number;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    titleRu: string;
    /**
     * 
     */
    titleEn: string;
    /**
     * 
     */
    subtitleRu: string;
    /**
     * 
     */
    subtitleEn: string;
    /**
     * 
     */
    scheduledDate: Date;
    /**
     * 
     */
    scheduledEndDate?: Date | null;
    /**
     * 
     */
    scheduledTime?: string | null;
    /**
     * 
     */
    occurredAt: Date;
    /**
     * 
     */
    money: Money;
    /**
     * 
     */
    action: ActionTarget;
}


/**
 * @export
 */
export const CustomerActivityItemServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CustomerActivityItemServiceEnum = typeof CustomerActivityItemServiceEnum[keyof typeof CustomerActivityItemServiceEnum];


/**
 * Check if a given object implements the CustomerActivityItem interface.
 */
export function instanceOfCustomerActivityItem(value: object): value is CustomerActivityItem {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('titleRu' in value) || value['titleRu'] === undefined) return false;
    if (!('titleEn' in value) || value['titleEn'] === undefined) return false;
    if (!('subtitleRu' in value) || value['subtitleRu'] === undefined) return false;
    if (!('subtitleEn' in value) || value['subtitleEn'] === undefined) return false;
    if (!('scheduledDate' in value) || value['scheduledDate'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('money' in value) || value['money'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function CustomerActivityItemFromJSON(json: any): CustomerActivityItem {
    return CustomerActivityItemFromJSONTyped(json, false);
}

export function CustomerActivityItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerActivityItem {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'entityId': json['entityId'],
        'status': json['status'],
        'titleRu': json['titleRu'],
        'titleEn': json['titleEn'],
        'subtitleRu': json['subtitleRu'],
        'subtitleEn': json['subtitleEn'],
        'scheduledDate': (json['scheduledDate'] == null ? json['scheduledDate'] : parseDate(json['scheduledDate'])),
        'scheduledEndDate': json['scheduledEndDate'] === undefined ? undefined : json['scheduledEndDate'] === null ? null : (parseDate(json['scheduledEndDate'])),
        'scheduledTime': json['scheduledTime'] === undefined ? undefined : json['scheduledTime'] === null ? null : json['scheduledTime'],
        'occurredAt': (json['occurredAt'] == null ? json['occurredAt'] : parseDateTime(json['occurredAt'])),
        'money': MoneyFromJSON(json['money']),
        'action': ActionTargetFromJSON(json['action']),
    };
}

export function CustomerActivityItemToJSON(json: any): CustomerActivityItem {
    return CustomerActivityItemToJSONTyped(json, false);
}

export function CustomerActivityItemToJSONTyped(value?: CustomerActivityItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'entityId': value['entityId'],
        'status': value['status'],
        'titleRu': value['titleRu'],
        'titleEn': value['titleEn'],
        'subtitleRu': value['subtitleRu'],
        'subtitleEn': value['subtitleEn'],
        'scheduledDate': value['scheduledDate'] == null ? value['scheduledDate'] : serializeDate(value['scheduledDate']),
        'scheduledEndDate': value['scheduledEndDate'] == null ? value['scheduledEndDate'] : serializeDate(value['scheduledEndDate']),
        'scheduledTime': value['scheduledTime'],
        'occurredAt': value['occurredAt'] == null ? value['occurredAt'] : serializeDateTime(value['occurredAt']),
        'money': MoneyToJSON(value['money']),
        'action': ActionTargetToJSON(value['action']),
    };
}

