/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RentalTransferBenefit } from './RentalTransferBenefit';
import {
    RentalTransferBenefitFromJSON,
    RentalTransferBenefitFromJSONTyped,
    RentalTransferBenefitToJSON,
    RentalTransferBenefitToJSONTyped,
} from './RentalTransferBenefit';
import type { ActionTarget } from './ActionTarget';
import {
    ActionTargetFromJSON,
    ActionTargetFromJSONTyped,
    ActionTargetToJSON,
    ActionTargetToJSONTyped,
} from './ActionTarget';

/**
 * 
 * @export
 * @interface CustomerHomePrimaryAction
 */
export interface CustomerHomePrimaryAction {
    /**
     * 
     */
    type: CustomerHomePrimaryActionTypeEnum;
    /**
     * 
     */
    sourceService: CustomerHomePrimaryActionSourceServiceEnum;
    /**
     * 
     */
    sourceEntityId: number;
    /**
     * 
     */
    targetService: CustomerHomePrimaryActionTargetServiceEnum;
    /**
     * 
     */
    relevantDate: Date;
    /**
     * 
     */
    eligibleFrom?: Date | null;
    /**
     * 
     */
    expiresOn?: Date | null;
    /**
     * 
     */
    action: ActionTarget;
    /**
     * 
     */
    benefit?: RentalTransferBenefit | null;
}


/**
 * @export
 */
export const CustomerHomePrimaryActionTypeEnum = {
    RentalTransferArrival: 'RENTAL_TRANSFER_ARRIVAL',
    RentalTransferCheckout: 'RENTAL_TRANSFER_CHECKOUT',
    RentalCleaning: 'RENTAL_CLEANING',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CustomerHomePrimaryActionTypeEnum = typeof CustomerHomePrimaryActionTypeEnum[keyof typeof CustomerHomePrimaryActionTypeEnum];

/**
 * @export
 */
export const CustomerHomePrimaryActionSourceServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CustomerHomePrimaryActionSourceServiceEnum = typeof CustomerHomePrimaryActionSourceServiceEnum[keyof typeof CustomerHomePrimaryActionSourceServiceEnum];

/**
 * @export
 */
export const CustomerHomePrimaryActionTargetServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CustomerHomePrimaryActionTargetServiceEnum = typeof CustomerHomePrimaryActionTargetServiceEnum[keyof typeof CustomerHomePrimaryActionTargetServiceEnum];


/**
 * Check if a given object implements the CustomerHomePrimaryAction interface.
 */
export function instanceOfCustomerHomePrimaryAction(value: object): value is CustomerHomePrimaryAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('sourceService' in value) || value['sourceService'] === undefined) return false;
    if (!('sourceEntityId' in value) || value['sourceEntityId'] === undefined) return false;
    if (!('targetService' in value) || value['targetService'] === undefined) return false;
    if (!('relevantDate' in value) || value['relevantDate'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function CustomerHomePrimaryActionFromJSON(json: any): CustomerHomePrimaryAction {
    return CustomerHomePrimaryActionFromJSONTyped(json, false);
}

export function CustomerHomePrimaryActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerHomePrimaryAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'sourceService': json['sourceService'],
        'sourceEntityId': json['sourceEntityId'],
        'targetService': json['targetService'],
        'relevantDate': (json['relevantDate'] == null ? json['relevantDate'] : parseDate(json['relevantDate'])),
        'eligibleFrom': json['eligibleFrom'] === undefined ? undefined : json['eligibleFrom'] === null ? null : (parseDate(json['eligibleFrom'])),
        'expiresOn': json['expiresOn'] === undefined ? undefined : json['expiresOn'] === null ? null : (parseDate(json['expiresOn'])),
        'action': ActionTargetFromJSON(json['action']),
        'benefit': json['benefit'] === undefined ? undefined : json['benefit'] === null ? null : RentalTransferBenefitFromJSON(json['benefit']),
    };
}

export function CustomerHomePrimaryActionToJSON(json: any): CustomerHomePrimaryAction {
    return CustomerHomePrimaryActionToJSONTyped(json, false);
}

export function CustomerHomePrimaryActionToJSONTyped(value?: CustomerHomePrimaryAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'sourceService': value['sourceService'],
        'sourceEntityId': value['sourceEntityId'],
        'targetService': value['targetService'],
        'relevantDate': value['relevantDate'] == null ? value['relevantDate'] : serializeDate(value['relevantDate']),
        'eligibleFrom': value['eligibleFrom'] == null ? value['eligibleFrom'] : serializeDate(value['eligibleFrom']),
        'expiresOn': value['expiresOn'] == null ? value['expiresOn'] : serializeDate(value['expiresOn']),
        'action': ActionTargetToJSON(value['action']),
        'benefit': RentalTransferBenefitToJSON(value['benefit']),
    };
}

