/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { ActionTarget } from './ActionTarget';
import {
    ActionTargetFromJSON,
    ActionTargetFromJSONTyped,
    ActionTargetToJSON,
    ActionTargetToJSONTyped,
} from './ActionTarget';

/**
 * 
 * @export
 * @interface CustomerHomeRepeatOpportunity
 */
export interface CustomerHomeRepeatOpportunity {
    /**
     * 
     */
    service: CustomerHomeRepeatOpportunityServiceEnum;
    /**
     * 
     */
    sourceEntityId: number;
    /**
     * 
     */
    sourceCompletedAt: Date;
    /**
     * 
     */
    action: ActionTarget;
}


/**
 * @export
 */
export const CustomerHomeRepeatOpportunityServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type CustomerHomeRepeatOpportunityServiceEnum = typeof CustomerHomeRepeatOpportunityServiceEnum[keyof typeof CustomerHomeRepeatOpportunityServiceEnum];


/**
 * Check if a given object implements the CustomerHomeRepeatOpportunity interface.
 */
export function instanceOfCustomerHomeRepeatOpportunity(value: object): value is CustomerHomeRepeatOpportunity {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('sourceEntityId' in value) || value['sourceEntityId'] === undefined) return false;
    if (!('sourceCompletedAt' in value) || value['sourceCompletedAt'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function CustomerHomeRepeatOpportunityFromJSON(json: any): CustomerHomeRepeatOpportunity {
    return CustomerHomeRepeatOpportunityFromJSONTyped(json, false);
}

export function CustomerHomeRepeatOpportunityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerHomeRepeatOpportunity {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'sourceEntityId': json['sourceEntityId'],
        'sourceCompletedAt': (json['sourceCompletedAt'] == null ? json['sourceCompletedAt'] : parseDateTime(json['sourceCompletedAt'])),
        'action': ActionTargetFromJSON(json['action']),
    };
}

export function CustomerHomeRepeatOpportunityToJSON(json: any): CustomerHomeRepeatOpportunity {
    return CustomerHomeRepeatOpportunityToJSONTyped(json, false);
}

export function CustomerHomeRepeatOpportunityToJSONTyped(value?: CustomerHomeRepeatOpportunity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'sourceEntityId': value['sourceEntityId'],
        'sourceCompletedAt': value['sourceCompletedAt'] == null ? value['sourceCompletedAt'] : serializeDateTime(value['sourceCompletedAt']),
        'action': ActionTargetToJSON(value['action']),
    };
}

