/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerHomePrimaryAction } from './CustomerHomePrimaryAction';
import {
    CustomerHomePrimaryActionFromJSON,
    CustomerHomePrimaryActionFromJSONTyped,
    CustomerHomePrimaryActionToJSON,
    CustomerHomePrimaryActionToJSONTyped,
} from './CustomerHomePrimaryAction';
import type { CustomerActivityItem } from './CustomerActivityItem';
import {
    CustomerActivityItemFromJSON,
    CustomerActivityItemFromJSONTyped,
    CustomerActivityItemToJSON,
    CustomerActivityItemToJSONTyped,
} from './CustomerActivityItem';
import type { CustomerHomeRepeatOpportunity } from './CustomerHomeRepeatOpportunity';
import {
    CustomerHomeRepeatOpportunityFromJSON,
    CustomerHomeRepeatOpportunityFromJSONTyped,
    CustomerHomeRepeatOpportunityToJSON,
    CustomerHomeRepeatOpportunityToJSONTyped,
} from './CustomerHomeRepeatOpportunity';

/**
 * 
 * @export
 * @interface CustomerHome
 */
export interface CustomerHome {
    /**
     * 
     */
    hasActivity: boolean;
    /**
     * 
     */
    activeTransaction?: CustomerActivityItem | null;
    /**
     * 
     */
    activeTransactionCount: number;
    /**
     * 
     */
    primaryAction?: CustomerHomePrimaryAction | null;
    /**
     * 
     */
    repeatOpportunity?: CustomerHomeRepeatOpportunity | null;
}

/**
 * Check if a given object implements the CustomerHome interface.
 */
export function instanceOfCustomerHome(value: object): value is CustomerHome {
    if (!('hasActivity' in value) || value['hasActivity'] === undefined) return false;
    if (!('activeTransactionCount' in value) || value['activeTransactionCount'] === undefined) return false;
    return true;
}

export function CustomerHomeFromJSON(json: any): CustomerHome {
    return CustomerHomeFromJSONTyped(json, false);
}

export function CustomerHomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerHome {
    if (json == null) {
        return json;
    }
    return {
        
        'hasActivity': json['hasActivity'],
        'activeTransaction': json['activeTransaction'] === undefined ? undefined : json['activeTransaction'] === null ? null : CustomerActivityItemFromJSON(json['activeTransaction']),
        'activeTransactionCount': json['activeTransactionCount'],
        'primaryAction': json['primaryAction'] === undefined ? undefined : json['primaryAction'] === null ? null : CustomerHomePrimaryActionFromJSON(json['primaryAction']),
        'repeatOpportunity': json['repeatOpportunity'] === undefined ? undefined : json['repeatOpportunity'] === null ? null : CustomerHomeRepeatOpportunityFromJSON(json['repeatOpportunity']),
    };
}

export function CustomerHomeToJSON(json: any): CustomerHome {
    return CustomerHomeToJSONTyped(json, false);
}

export function CustomerHomeToJSONTyped(value?: CustomerHome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasActivity': value['hasActivity'],
        'activeTransaction': CustomerActivityItemToJSON(value['activeTransaction']),
        'activeTransactionCount': value['activeTransactionCount'],
        'primaryAction': CustomerHomePrimaryActionToJSON(value['primaryAction']),
        'repeatOpportunity': CustomerHomeRepeatOpportunityToJSON(value['repeatOpportunity']),
    };
}

