/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountIdentity } from './AccountIdentity';
import {
    AccountIdentityFromJSON,
    AccountIdentityFromJSONTyped,
    AccountIdentityToJSON,
    AccountIdentityToJSONTyped,
} from './AccountIdentity';

/**
 * 
 * @export
 * @interface GetAccountIdentities200Response
 */
export interface GetAccountIdentities200Response {
    /**
     * 
     */
    identities: Array<AccountIdentity>;
}

/**
 * Check if a given object implements the GetAccountIdentities200Response interface.
 */
export function instanceOfGetAccountIdentities200Response(value: object): value is GetAccountIdentities200Response {
    if (!('identities' in value) || value['identities'] === undefined) return false;
    return true;
}

export function GetAccountIdentities200ResponseFromJSON(json: any): GetAccountIdentities200Response {
    return GetAccountIdentities200ResponseFromJSONTyped(json, false);
}

export function GetAccountIdentities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountIdentities200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'identities': ((json['identities'] as Array<any>).map(AccountIdentityFromJSON)),
    };
}

export function GetAccountIdentities200ResponseToJSON(json: any): GetAccountIdentities200Response {
    return GetAccountIdentities200ResponseToJSONTyped(json, false);
}

export function GetAccountIdentities200ResponseToJSONTyped(value?: GetAccountIdentities200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identities': ((value['identities'] as Array<any>).map(AccountIdentityToJSON)),
    };
}

