/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const IdentityProvider = {
    Google: 'GOOGLE',
    Apple: 'APPLE',
    Telegram: 'TELEGRAM',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type IdentityProvider = typeof IdentityProvider[keyof typeof IdentityProvider];


export function instanceOfIdentityProvider(value: any): boolean {
    for (const key in IdentityProvider) {
        if (Object.prototype.hasOwnProperty.call(IdentityProvider, key)) {
            if (IdentityProvider[key as keyof typeof IdentityProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IdentityProviderFromJSON(json: any): IdentityProvider {
    return IdentityProviderFromJSONTyped(json, false);
}

export function IdentityProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityProvider {
    return json as IdentityProvider;
}

export function IdentityProviderToJSON(value?: IdentityProvider | null): any {
    return value as any;
}

export function IdentityProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): IdentityProvider {
    return value as IdentityProvider;
}

