/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginProviderAvailability
 */
export interface LoginProviderAvailability {
    /**
     * 
     */
    available: boolean;
}

/**
 * Check if a given object implements the LoginProviderAvailability interface.
 */
export function instanceOfLoginProviderAvailability(value: object): value is LoginProviderAvailability {
    if (!('available' in value) || value['available'] === undefined) return false;
    return true;
}

export function LoginProviderAvailabilityFromJSON(json: any): LoginProviderAvailability {
    return LoginProviderAvailabilityFromJSONTyped(json, false);
}

export function LoginProviderAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginProviderAvailability {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'],
    };
}

export function LoginProviderAvailabilityToJSON(json: any): LoginProviderAvailability {
    return LoginProviderAvailabilityToJSONTyped(json, false);
}

export function LoginProviderAvailabilityToJSONTyped(value?: LoginProviderAvailability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
    };
}

