/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginProviderAvailability } from './LoginProviderAvailability';
import {
    LoginProviderAvailabilityFromJSON,
    LoginProviderAvailabilityFromJSONTyped,
    LoginProviderAvailabilityToJSON,
    LoginProviderAvailabilityToJSONTyped,
} from './LoginProviderAvailability';

/**
 * 
 * @export
 * @interface LoginProviders
 */
export interface LoginProviders {
    /**
     * 
     */
    google: LoginProviderAvailability;
}

/**
 * Check if a given object implements the LoginProviders interface.
 */
export function instanceOfLoginProviders(value: object): value is LoginProviders {
    if (!('google' in value) || value['google'] === undefined) return false;
    return true;
}

export function LoginProvidersFromJSON(json: any): LoginProviders {
    return LoginProvidersFromJSONTyped(json, false);
}

export function LoginProvidersFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginProviders {
    if (json == null) {
        return json;
    }
    return {
        
        'google': LoginProviderAvailabilityFromJSON(json['google']),
    };
}

export function LoginProvidersToJSON(json: any): LoginProviders {
    return LoginProvidersToJSONTyped(json, false);
}

export function LoginProvidersToJSONTyped(value?: LoginProviders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'google': LoginProviderAvailabilityToJSON(value['google']),
    };
}

