/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NativeProviderLoginRequest
 */
export interface NativeProviderLoginRequest {
    /**
     * 
     */
    challengeId: string;
    /**
     * 
     */
    clientType: NativeProviderLoginRequestClientTypeEnum;
    /**
     * 
     */
    identityToken: string;
    /**
     * 
     */
    authorizationCode?: string | null;
}


/**
 * @export
 */
export const NativeProviderLoginRequestClientTypeEnum = {
    Ios: 'IOS',
    Android: 'ANDROID',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type NativeProviderLoginRequestClientTypeEnum = typeof NativeProviderLoginRequestClientTypeEnum[keyof typeof NativeProviderLoginRequestClientTypeEnum];


/**
 * Check if a given object implements the NativeProviderLoginRequest interface.
 */
export function instanceOfNativeProviderLoginRequest(value: object): value is NativeProviderLoginRequest {
    if (!('challengeId' in value) || value['challengeId'] === undefined) return false;
    if (!('clientType' in value) || value['clientType'] === undefined) return false;
    if (!('identityToken' in value) || value['identityToken'] === undefined) return false;
    return true;
}

export function NativeProviderLoginRequestFromJSON(json: any): NativeProviderLoginRequest {
    return NativeProviderLoginRequestFromJSONTyped(json, false);
}

export function NativeProviderLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NativeProviderLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'challengeId': json['challengeId'],
        'clientType': json['clientType'],
        'identityToken': json['identityToken'],
        'authorizationCode': json['authorizationCode'] === undefined ? undefined : json['authorizationCode'] === null ? null : json['authorizationCode'],
    };
}

export function NativeProviderLoginRequestToJSON(json: any): NativeProviderLoginRequest {
    return NativeProviderLoginRequestToJSONTyped(json, false);
}

export function NativeProviderLoginRequestToJSONTyped(value?: NativeProviderLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challengeId': value['challengeId'],
        'clientType': value['clientType'],
        'identityToken': value['identityToken'],
        'authorizationCode': value['authorizationCode'],
    };
}

