/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { IdentityProvider } from './IdentityProvider';
import {
    IdentityProviderFromJSON,
    IdentityProviderFromJSONTyped,
    IdentityProviderToJSON,
    IdentityProviderToJSONTyped,
} from './IdentityProvider';

/**
 * 
 * @export
 * @interface NativeChallenge
 */
export interface NativeChallenge {
    /**
     * 
     */
    challengeId: string;
    /**
     * 
     */
    provider: IdentityProvider;
    /**
     * 
     */
    nonce: string;
    /**
     * 
     */
    expiresAt: Date;
}



/**
 * Check if a given object implements the NativeChallenge interface.
 */
export function instanceOfNativeChallenge(value: object): value is NativeChallenge {
    if (!('challengeId' in value) || value['challengeId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function NativeChallengeFromJSON(json: any): NativeChallenge {
    return NativeChallengeFromJSONTyped(json, false);
}

export function NativeChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NativeChallenge {
    if (json == null) {
        return json;
    }
    return {
        
        'challengeId': json['challengeId'],
        'provider': IdentityProviderFromJSON(json['provider']),
        'nonce': json['nonce'],
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
    };
}

export function NativeChallengeToJSON(json: any): NativeChallenge {
    return NativeChallengeToJSONTyped(json, false);
}

export function NativeChallengeToJSONTyped(value?: NativeChallenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challengeId': value['challengeId'],
        'provider': IdentityProviderToJSON(value['provider']),
        'nonce': value['nonce'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
    };
}

