/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationPreferences
 */
export interface NotificationPreferences {
    /**
     * 
     */
    telegramEnabled: boolean;
    /**
     * 
     */
    pushEnabled: boolean;
}

/**
 * Check if a given object implements the NotificationPreferences interface.
 */
export function instanceOfNotificationPreferences(value: object): value is NotificationPreferences {
    if (!('telegramEnabled' in value) || value['telegramEnabled'] === undefined) return false;
    if (!('pushEnabled' in value) || value['pushEnabled'] === undefined) return false;
    return true;
}

export function NotificationPreferencesFromJSON(json: any): NotificationPreferences {
    return NotificationPreferencesFromJSONTyped(json, false);
}

export function NotificationPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationPreferences {
    if (json == null) {
        return json;
    }
    return {
        
        'telegramEnabled': json['telegramEnabled'],
        'pushEnabled': json['pushEnabled'],
    };
}

export function NotificationPreferencesToJSON(json: any): NotificationPreferences {
    return NotificationPreferencesToJSONTyped(json, false);
}

export function NotificationPreferencesToJSONTyped(value?: NotificationPreferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'telegramEnabled': value['telegramEnabled'],
        'pushEnabled': value['pushEnabled'],
    };
}

