/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationUnreadCount
 */
export interface NotificationUnreadCount {
    /**
     * 
     */
    unreadCount: number;
}

/**
 * Check if a given object implements the NotificationUnreadCount interface.
 */
export function instanceOfNotificationUnreadCount(value: object): value is NotificationUnreadCount {
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    return true;
}

export function NotificationUnreadCountFromJSON(json: any): NotificationUnreadCount {
    return NotificationUnreadCountFromJSONTyped(json, false);
}

export function NotificationUnreadCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationUnreadCount {
    if (json == null) {
        return json;
    }
    return {
        
        'unreadCount': json['unreadCount'],
    };
}

export function NotificationUnreadCountToJSON(json: any): NotificationUnreadCount {
    return NotificationUnreadCountToJSONTyped(json, false);
}

export function NotificationUnreadCountToJSONTyped(value?: NotificationUnreadCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unreadCount': value['unreadCount'],
    };
}

