/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenTransactionAction
 */
export interface OpenTransactionAction {
    /**
     * 
     */
    type: OpenTransactionActionTypeEnum;
    /**
     * 
     */
    service: OpenTransactionActionServiceEnum;
    /**
     * 
     */
    entityId: number;
}


/**
 * @export
 */
export const OpenTransactionActionTypeEnum = {
    OpenTransaction: 'OPEN_TRANSACTION',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type OpenTransactionActionTypeEnum = typeof OpenTransactionActionTypeEnum[keyof typeof OpenTransactionActionTypeEnum];

/**
 * @export
 */
export const OpenTransactionActionServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type OpenTransactionActionServiceEnum = typeof OpenTransactionActionServiceEnum[keyof typeof OpenTransactionActionServiceEnum];


/**
 * Check if a given object implements the OpenTransactionAction interface.
 */
export function instanceOfOpenTransactionAction(value: object): value is OpenTransactionAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'OPEN_TRANSACTION') return false;
    
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    return true;
}

export function OpenTransactionActionFromJSON(json: any): OpenTransactionAction {
    return OpenTransactionActionFromJSONTyped(json, false);
}

export function OpenTransactionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenTransactionAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'service': json['service'],
        'entityId': json['entityId'],
    };
}

export function OpenTransactionActionToJSON(json: any): OpenTransactionAction {
    return OpenTransactionActionToJSONTyped(json, false);
}

export function OpenTransactionActionToJSONTyped(value?: OpenTransactionAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'service': value['service'],
        'entityId': value['entityId'],
    };
}

