/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenSupportCaseAction
 */
export interface OpenSupportCaseAction {
    /**
     * 
     */
    type: OpenSupportCaseActionTypeEnum;
    /**
     * 
     */
    caseId: number;
}


/**
 * @export
 */
export const OpenSupportCaseActionTypeEnum = {
    OpenSupportCase: 'OPEN_SUPPORT_CASE',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type OpenSupportCaseActionTypeEnum = typeof OpenSupportCaseActionTypeEnum[keyof typeof OpenSupportCaseActionTypeEnum];


/**
 * Check if a given object implements the OpenSupportCaseAction interface.
 */
export function instanceOfOpenSupportCaseAction(value: object): value is OpenSupportCaseAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'OPEN_SUPPORT_CASE') return false;
    
    if (!('caseId' in value) || value['caseId'] === undefined) return false;
    return true;
}

export function OpenSupportCaseActionFromJSON(json: any): OpenSupportCaseAction {
    return OpenSupportCaseActionFromJSONTyped(json, false);
}

export function OpenSupportCaseActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenSupportCaseAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'caseId': json['caseId'],
    };
}

export function OpenSupportCaseActionToJSON(json: any): OpenSupportCaseAction {
    return OpenSupportCaseActionToJSONTyped(json, false);
}

export function OpenSupportCaseActionToJSONTyped(value?: OpenSupportCaseAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'caseId': value['caseId'],
    };
}

