/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenCleaningHistoryAction
 */
export interface OpenCleaningHistoryAction {
    /**
     * 
     */
    type: OpenCleaningHistoryActionTypeEnum;
}


/**
 * @export
 */
export const OpenCleaningHistoryActionTypeEnum = {
    OpenCleaningHistory: 'OPEN_CLEANING_HISTORY',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type OpenCleaningHistoryActionTypeEnum = typeof OpenCleaningHistoryActionTypeEnum[keyof typeof OpenCleaningHistoryActionTypeEnum];


/**
 * Check if a given object implements the OpenCleaningHistoryAction interface.
 */
export function instanceOfOpenCleaningHistoryAction(value: object): value is OpenCleaningHistoryAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'OPEN_CLEANING_HISTORY') return false;
    
    return true;
}

export function OpenCleaningHistoryActionFromJSON(json: any): OpenCleaningHistoryAction {
    return OpenCleaningHistoryActionFromJSONTyped(json, false);
}

export function OpenCleaningHistoryActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenCleaningHistoryAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function OpenCleaningHistoryActionToJSON(json: any): OpenCleaningHistoryAction {
    return OpenCleaningHistoryActionToJSONTyped(json, false);
}

export function OpenCleaningHistoryActionToJSONTyped(value?: OpenCleaningHistoryAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

