/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformServiceState
 */
export interface PlatformServiceState {
    /**
     * 
     */
    service: PlatformServiceStateServiceEnum;
    /**
     * 
     */
    status: PlatformServiceStateStatusEnum;
    /**
     * 
     */
    displayOrder: number;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    updatedByCustomerId?: number | null;
    /**
     * 
     */
    version: number;
}


/**
 * @export
 */
export const PlatformServiceStateServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type PlatformServiceStateServiceEnum = typeof PlatformServiceStateServiceEnum[keyof typeof PlatformServiceStateServiceEnum];

/**
 * @export
 */
export const PlatformServiceStateStatusEnum = {
    Enabled: 'ENABLED',
    InTest: 'IN_TEST',
    Disabled: 'DISABLED',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type PlatformServiceStateStatusEnum = typeof PlatformServiceStateStatusEnum[keyof typeof PlatformServiceStateStatusEnum];


/**
 * Check if a given object implements the PlatformServiceState interface.
 */
export function instanceOfPlatformServiceState(value: object): value is PlatformServiceState {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('displayOrder' in value) || value['displayOrder'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PlatformServiceStateFromJSON(json: any): PlatformServiceState {
    return PlatformServiceStateFromJSONTyped(json, false);
}

export function PlatformServiceStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformServiceState {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'status': json['status'],
        'displayOrder': json['displayOrder'],
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
        'updatedByCustomerId': json['updatedByCustomerId'] === undefined ? undefined : json['updatedByCustomerId'] === null ? null : json['updatedByCustomerId'],
        'version': json['version'],
    };
}

export function PlatformServiceStateToJSON(json: any): PlatformServiceState {
    return PlatformServiceStateToJSONTyped(json, false);
}

export function PlatformServiceStateToJSONTyped(value?: PlatformServiceState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'status': value['status'],
        'displayOrder': value['displayOrder'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'updatedByCustomerId': value['updatedByCustomerId'],
        'version': value['version'],
    };
}

