/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReferralSummary
 */
export interface ReferralSummary {
    /**
     * 
     */
    referralCode?: string | null;
    /**
     * 
     */
    availableRewards: number;
    /**
     * 
     */
    referralProgramUnlocked: boolean;
}

/**
 * Check if a given object implements the ReferralSummary interface.
 */
export function instanceOfReferralSummary(value: object): value is ReferralSummary {
    if (!('availableRewards' in value) || value['availableRewards'] === undefined) return false;
    if (!('referralProgramUnlocked' in value) || value['referralProgramUnlocked'] === undefined) return false;
    return true;
}

export function ReferralSummaryFromJSON(json: any): ReferralSummary {
    return ReferralSummaryFromJSONTyped(json, false);
}

export function ReferralSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'referralCode': json['referralCode'] === undefined ? undefined : json['referralCode'] === null ? null : json['referralCode'],
        'availableRewards': json['availableRewards'],
        'referralProgramUnlocked': json['referralProgramUnlocked'],
    };
}

export function ReferralSummaryToJSON(json: any): ReferralSummary {
    return ReferralSummaryToJSONTyped(json, false);
}

export function ReferralSummaryToJSONTyped(value?: ReferralSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referralCode': value['referralCode'],
        'availableRewards': value['availableRewards'],
        'referralProgramUnlocked': value['referralProgramUnlocked'],
    };
}

