/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshSessionRequest
 */
export interface RefreshSessionRequest {
    /**
     * 
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshSessionRequest interface.
 */
export function instanceOfRefreshSessionRequest(value: object): value is RefreshSessionRequest {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshSessionRequestFromJSON(json: any): RefreshSessionRequest {
    return RefreshSessionRequestFromJSONTyped(json, false);
}

export function RefreshSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshSessionRequestToJSON(json: any): RefreshSessionRequest {
    return RefreshSessionRequestToJSONTyped(json, false);
}

export function RefreshSessionRequestToJSONTyped(value?: RefreshSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

