/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RentalTransferBenefit } from './RentalTransferBenefit';
import {
    RentalTransferBenefitFromJSON,
    RentalTransferBenefitFromJSONTyped,
    RentalTransferBenefitToJSON,
    RentalTransferBenefitToJSONTyped,
} from './RentalTransferBenefit';

/**
 * 
 * @export
 * @interface RentalTransferContextOption
 */
export interface RentalTransferContextOption {
    /**
     * 
     */
    context: RentalTransferContextOptionContextEnum;
    /**
     * 
     */
    availability: RentalTransferContextOptionAvailabilityEnum;
    /**
     * 
     */
    direction: RentalTransferContextOptionDirectionEnum;
    /**
     * 
     */
    suggestedDate: Date;
    /**
     * 
     */
    address: string;
    /**
     * 
     */
    availableFromDate: Date | null;
    /**
     * 
     */
    benefit: RentalTransferBenefit | null;
}


/**
 * @export
 */
export const RentalTransferContextOptionContextEnum = {
    Arrival: 'ARRIVAL',
    Checkout: 'CHECKOUT',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalTransferContextOptionContextEnum = typeof RentalTransferContextOptionContextEnum[keyof typeof RentalTransferContextOptionContextEnum];

/**
 * @export
 */
export const RentalTransferContextOptionAvailabilityEnum = {
    Bookable: 'BOOKABLE',
    AvailableLater: 'AVAILABLE_LATER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalTransferContextOptionAvailabilityEnum = typeof RentalTransferContextOptionAvailabilityEnum[keyof typeof RentalTransferContextOptionAvailabilityEnum];

/**
 * @export
 */
export const RentalTransferContextOptionDirectionEnum = {
    ToAirport: 'TO_AIRPORT',
    FromAirport: 'FROM_AIRPORT',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalTransferContextOptionDirectionEnum = typeof RentalTransferContextOptionDirectionEnum[keyof typeof RentalTransferContextOptionDirectionEnum];


/**
 * Check if a given object implements the RentalTransferContextOption interface.
 */
export function instanceOfRentalTransferContextOption(value: object): value is RentalTransferContextOption {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('availability' in value) || value['availability'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('suggestedDate' in value) || value['suggestedDate'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('availableFromDate' in value) || value['availableFromDate'] === undefined) return false;
    if (!('benefit' in value) || value['benefit'] === undefined) return false;
    return true;
}

export function RentalTransferContextOptionFromJSON(json: any): RentalTransferContextOption {
    return RentalTransferContextOptionFromJSONTyped(json, false);
}

export function RentalTransferContextOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalTransferContextOption {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['context'],
        'availability': json['availability'],
        'direction': json['direction'],
        'suggestedDate': (json['suggestedDate'] == null ? json['suggestedDate'] : parseDate(json['suggestedDate'])),
        'address': json['address'],
        'availableFromDate': (json['availableFromDate'] == null ? null : parseDate(json['availableFromDate'])),
        'benefit': RentalTransferBenefitFromJSON(json['benefit']),
    };
}

export function RentalTransferContextOptionToJSON(json: any): RentalTransferContextOption {
    return RentalTransferContextOptionToJSONTyped(json, false);
}

export function RentalTransferContextOptionToJSONTyped(value?: RentalTransferContextOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': value['context'],
        'availability': value['availability'],
        'direction': value['direction'],
        'suggestedDate': value['suggestedDate'] == null ? value['suggestedDate'] : serializeDate(value['suggestedDate']),
        'address': value['address'],
        'availableFromDate': value['availableFromDate'] == null ? value['availableFromDate'] : serializeDate(value['availableFromDate']),
        'benefit': RentalTransferBenefitToJSON(value['benefit']),
    };
}

