/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentalPropertyMedia
 */
export interface RentalPropertyMedia {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    mediaAssetId: number;
    /**
     * 
     */
    sortOrder: number;
    /**
     * 
     */
    cover: boolean;
    /**
     * 
     */
    url: string;
    /**
     * 
     */
    cardUrl: string;
    /**
     * 
     */
    thumbnailUrl: string;
}

/**
 * Check if a given object implements the RentalPropertyMedia interface.
 */
export function instanceOfRentalPropertyMedia(value: object): value is RentalPropertyMedia {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mediaAssetId' in value) || value['mediaAssetId'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('cover' in value) || value['cover'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('cardUrl' in value) || value['cardUrl'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    return true;
}

export function RentalPropertyMediaFromJSON(json: any): RentalPropertyMedia {
    return RentalPropertyMediaFromJSONTyped(json, false);
}

export function RentalPropertyMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalPropertyMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mediaAssetId': json['mediaAssetId'],
        'sortOrder': json['sortOrder'],
        'cover': json['cover'],
        'url': json['url'],
        'cardUrl': json['cardUrl'],
        'thumbnailUrl': json['thumbnailUrl'],
    };
}

export function RentalPropertyMediaToJSON(json: any): RentalPropertyMedia {
    return RentalPropertyMediaToJSONTyped(json, false);
}

export function RentalPropertyMediaToJSONTyped(value?: RentalPropertyMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'mediaAssetId': value['mediaAssetId'],
        'sortOrder': value['sortOrder'],
        'cover': value['cover'],
        'url': value['url'],
        'cardUrl': value['cardUrl'],
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

