/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RentalPrice } from './RentalPrice';
import {
    RentalPriceFromJSON,
    RentalPriceFromJSONTyped,
    RentalPriceToJSON,
    RentalPriceToJSONTyped,
} from './RentalPrice';
import type { RentalBookingProperty } from './RentalBookingProperty';
import {
    RentalBookingPropertyFromJSON,
    RentalBookingPropertyFromJSONTyped,
    RentalBookingPropertyToJSON,
    RentalBookingPropertyToJSONTyped,
} from './RentalBookingProperty';
import type { RentalSearchCriteria } from './RentalSearchCriteria';
import {
    RentalSearchCriteriaFromJSON,
    RentalSearchCriteriaFromJSONTyped,
    RentalSearchCriteriaToJSON,
    RentalSearchCriteriaToJSONTyped,
} from './RentalSearchCriteria';

/**
 * 
 * @export
 * @interface RentalQuote
 */
export interface RentalQuote {
    /**
     * 
     */
    property: RentalBookingProperty;
    /**
     * 
     */
    criteria: RentalSearchCriteria;
    /**
     * 
     */
    price: RentalPrice;
}

/**
 * Check if a given object implements the RentalQuote interface.
 */
export function instanceOfRentalQuote(value: object): value is RentalQuote {
    if (!('property' in value) || value['property'] === undefined) return false;
    if (!('criteria' in value) || value['criteria'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function RentalQuoteFromJSON(json: any): RentalQuote {
    return RentalQuoteFromJSONTyped(json, false);
}

export function RentalQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalQuote {
    if (json == null) {
        return json;
    }
    return {
        
        'property': RentalBookingPropertyFromJSON(json['property']),
        'criteria': RentalSearchCriteriaFromJSON(json['criteria']),
        'price': RentalPriceFromJSON(json['price']),
    };
}

export function RentalQuoteToJSON(json: any): RentalQuote {
    return RentalQuoteToJSONTyped(json, false);
}

export function RentalQuoteToJSONTyped(value?: RentalQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property': RentalBookingPropertyToJSON(value['property']),
        'criteria': RentalSearchCriteriaToJSON(value['criteria']),
        'price': RentalPriceToJSON(value['price']),
    };
}

