/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RentalSearchProperty } from './RentalSearchProperty';
import {
    RentalSearchPropertyFromJSON,
    RentalSearchPropertyFromJSONTyped,
    RentalSearchPropertyToJSON,
    RentalSearchPropertyToJSONTyped,
} from './RentalSearchProperty';
import type { RentalSearchCriteria } from './RentalSearchCriteria';
import {
    RentalSearchCriteriaFromJSON,
    RentalSearchCriteriaFromJSONTyped,
    RentalSearchCriteriaToJSON,
    RentalSearchCriteriaToJSONTyped,
} from './RentalSearchCriteria';

/**
 * 
 * @export
 * @interface RentalSearch
 */
export interface RentalSearch {
    /**
     * 
     */
    searchExecutionId: string;
    /**
     * 
     */
    criteria: RentalSearchCriteria;
    /**
     * 
     */
    calculatedAt: Date;
    /**
     * 
     */
    properties: Array<RentalSearchProperty>;
}

/**
 * Check if a given object implements the RentalSearch interface.
 */
export function instanceOfRentalSearch(value: object): value is RentalSearch {
    if (!('searchExecutionId' in value) || value['searchExecutionId'] === undefined) return false;
    if (!('criteria' in value) || value['criteria'] === undefined) return false;
    if (!('calculatedAt' in value) || value['calculatedAt'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function RentalSearchFromJSON(json: any): RentalSearch {
    return RentalSearchFromJSONTyped(json, false);
}

export function RentalSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'searchExecutionId': json['searchExecutionId'],
        'criteria': RentalSearchCriteriaFromJSON(json['criteria']),
        'calculatedAt': (json['calculatedAt'] == null ? json['calculatedAt'] : parseDateTime(json['calculatedAt'])),
        'properties': ((json['properties'] as Array<any>).map(RentalSearchPropertyFromJSON)),
    };
}

export function RentalSearchToJSON(json: any): RentalSearch {
    return RentalSearchToJSONTyped(json, false);
}

export function RentalSearchToJSONTyped(value?: RentalSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchExecutionId': value['searchExecutionId'],
        'criteria': RentalSearchCriteriaToJSON(value['criteria']),
        'calculatedAt': value['calculatedAt'] == null ? value['calculatedAt'] : serializeDateTime(value['calculatedAt']),
        'properties': ((value['properties'] as Array<any>).map(RentalSearchPropertyToJSON)),
    };
}

