/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentalTransferBenefit
 */
export interface RentalTransferBenefit {
    /**
     * 
     */
    type: RentalTransferBenefitTypeEnum;
    /**
     * 
     */
    discountRate: number;
}


/**
 * @export
 */
export const RentalTransferBenefitTypeEnum = {
    RentalFirstTransfer: 'RENTAL_FIRST_TRANSFER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalTransferBenefitTypeEnum = typeof RentalTransferBenefitTypeEnum[keyof typeof RentalTransferBenefitTypeEnum];


/**
 * Check if a given object implements the RentalTransferBenefit interface.
 */
export function instanceOfRentalTransferBenefit(value: object): value is RentalTransferBenefit {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'RENTAL_FIRST_TRANSFER') return false;
    
    if (!('discountRate' in value) || value['discountRate'] === undefined) return false;
    return true;
}

export function RentalTransferBenefitFromJSON(json: any): RentalTransferBenefit {
    return RentalTransferBenefitFromJSONTyped(json, false);
}

export function RentalTransferBenefitFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalTransferBenefit {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'discountRate': json['discountRate'],
    };
}

export function RentalTransferBenefitToJSON(json: any): RentalTransferBenefit {
    return RentalTransferBenefitToJSONTyped(json, false);
}

export function RentalTransferBenefitToJSONTyped(value?: RentalTransferBenefit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'discountRate': value['discountRate'],
    };
}

