/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentalFirstCardRequest
 */
export interface RentalFirstCardRequest {
    /**
     * 
     */
    durationMs: number;
}

/**
 * Check if a given object implements the RentalFirstCardRequest interface.
 */
export function instanceOfRentalFirstCardRequest(value: object): value is RentalFirstCardRequest {
    if (!('durationMs' in value) || value['durationMs'] === undefined) return false;
    return true;
}

export function RentalFirstCardRequestFromJSON(json: any): RentalFirstCardRequest {
    return RentalFirstCardRequestFromJSONTyped(json, false);
}

export function RentalFirstCardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalFirstCardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMs': json['durationMs'],
    };
}

export function RentalFirstCardRequestToJSON(json: any): RentalFirstCardRequest {
    return RentalFirstCardRequestToJSONTyped(json, false);
}

export function RentalFirstCardRequestToJSONTyped(value?: RentalFirstCardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'durationMs': value['durationMs'],
    };
}

