/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface RentalConfiguration
 */
export interface RentalConfiguration {
    /**
     * 
     */
    minStayDays: number;
    /**
     * 
     */
    longTermMinDays: number;
    /**
     * 
     */
    longTermDiscountRate: number;
    /**
     * 
     */
    maxStayDays: number;
    /**
     * 
     */
    bookingStartMonthsAhead: number;
    /**
     * 
     */
    maxActiveBookingsPerCustomer: number;
    /**
     * 
     */
    today: Date;
    /**
     * 
     */
    latestCheckInDate: Date;
}

/**
 * Check if a given object implements the RentalConfiguration interface.
 */
export function instanceOfRentalConfiguration(value: object): value is RentalConfiguration {
    if (!('minStayDays' in value) || value['minStayDays'] === undefined) return false;
    if (!('longTermMinDays' in value) || value['longTermMinDays'] === undefined) return false;
    if (!('longTermDiscountRate' in value) || value['longTermDiscountRate'] === undefined) return false;
    if (!('maxStayDays' in value) || value['maxStayDays'] === undefined) return false;
    if (!('bookingStartMonthsAhead' in value) || value['bookingStartMonthsAhead'] === undefined) return false;
    if (!('maxActiveBookingsPerCustomer' in value) || value['maxActiveBookingsPerCustomer'] === undefined) return false;
    if (!('today' in value) || value['today'] === undefined) return false;
    if (!('latestCheckInDate' in value) || value['latestCheckInDate'] === undefined) return false;
    return true;
}

export function RentalConfigurationFromJSON(json: any): RentalConfiguration {
    return RentalConfigurationFromJSONTyped(json, false);
}

export function RentalConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'minStayDays': json['minStayDays'],
        'longTermMinDays': json['longTermMinDays'],
        'longTermDiscountRate': json['longTermDiscountRate'],
        'maxStayDays': json['maxStayDays'],
        'bookingStartMonthsAhead': json['bookingStartMonthsAhead'],
        'maxActiveBookingsPerCustomer': json['maxActiveBookingsPerCustomer'],
        'today': (json['today'] == null ? json['today'] : parseDate(json['today'])),
        'latestCheckInDate': (json['latestCheckInDate'] == null ? json['latestCheckInDate'] : parseDate(json['latestCheckInDate'])),
    };
}

export function RentalConfigurationToJSON(json: any): RentalConfiguration {
    return RentalConfigurationToJSONTyped(json, false);
}

export function RentalConfigurationToJSONTyped(value?: RentalConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minStayDays': value['minStayDays'],
        'longTermMinDays': value['longTermMinDays'],
        'longTermDiscountRate': value['longTermDiscountRate'],
        'maxStayDays': value['maxStayDays'],
        'bookingStartMonthsAhead': value['bookingStartMonthsAhead'],
        'maxActiveBookingsPerCustomer': value['maxActiveBookingsPerCustomer'],
        'today': value['today'] == null ? value['today'] : serializeDate(value['today']),
        'latestCheckInDate': value['latestCheckInDate'] == null ? value['latestCheckInDate'] : serializeDate(value['latestCheckInDate']),
    };
}

