/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RentalTermType } from './RentalTermType';
import {
    RentalTermTypeFromJSON,
    RentalTermTypeFromJSONTyped,
    RentalTermTypeToJSON,
    RentalTermTypeToJSONTyped,
} from './RentalTermType';

/**
 * 
 * @export
 * @interface RentalSearchCriteria
 */
export interface RentalSearchCriteria {
    /**
     * 
     */
    mode: RentalSearchCriteriaModeEnum;
    /**
     * 
     */
    termType: RentalTermType | null;
    /**
     * 
     */
    checkInDate: Date | null;
    /**
     * 
     */
    checkOutDate: Date | null;
    /**
     * 
     */
    rentalMonths: number | null;
    /**
     * 
     */
    durationDays: number | null;
    /**
     * 
     */
    guests: number | null;
}


/**
 * @export
 */
export const RentalSearchCriteriaModeEnum = {
    DateRange: 'DATE_RANGE',
    Monthly: 'MONTHLY',
    BrowseAll: 'BROWSE_ALL',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalSearchCriteriaModeEnum = typeof RentalSearchCriteriaModeEnum[keyof typeof RentalSearchCriteriaModeEnum];


/**
 * Check if a given object implements the RentalSearchCriteria interface.
 */
export function instanceOfRentalSearchCriteria(value: object): value is RentalSearchCriteria {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('termType' in value) || value['termType'] === undefined) return false;
    if (!('checkInDate' in value) || value['checkInDate'] === undefined) return false;
    if (!('checkOutDate' in value) || value['checkOutDate'] === undefined) return false;
    if (!('rentalMonths' in value) || value['rentalMonths'] === undefined) return false;
    if (!('durationDays' in value) || value['durationDays'] === undefined) return false;
    if (!('guests' in value) || value['guests'] === undefined) return false;
    return true;
}

export function RentalSearchCriteriaFromJSON(json: any): RentalSearchCriteria {
    return RentalSearchCriteriaFromJSONTyped(json, false);
}

export function RentalSearchCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalSearchCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'termType': RentalTermTypeFromJSON(json['termType']),
        'checkInDate': (json['checkInDate'] == null ? null : parseDate(json['checkInDate'])),
        'checkOutDate': (json['checkOutDate'] == null ? null : parseDate(json['checkOutDate'])),
        'rentalMonths': json['rentalMonths'],
        'durationDays': json['durationDays'],
        'guests': json['guests'],
    };
}

export function RentalSearchCriteriaToJSON(json: any): RentalSearchCriteria {
    return RentalSearchCriteriaToJSONTyped(json, false);
}

export function RentalSearchCriteriaToJSONTyped(value?: RentalSearchCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'termType': RentalTermTypeToJSON(value['termType']),
        'checkInDate': value['checkInDate'] == null ? value['checkInDate'] : serializeDate(value['checkInDate']),
        'checkOutDate': value['checkOutDate'] == null ? value['checkOutDate'] : serializeDate(value['checkOutDate']),
        'rentalMonths': value['rentalMonths'],
        'durationDays': value['durationDays'],
        'guests': value['guests'],
    };
}

