/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface RentalCleaningContext
 */
export interface RentalCleaningContext {
    /**
     * 
     */
    rentalBookingId: number;
    /**
     * 
     */
    address: string;
    /**
     * 
     */
    phone: string;
    /**
     * 
     */
    checkOutDate: Date;
    /**
     * 
     */
    earliestBenefitCleaningDate: Date;
    /**
     * 
     */
    benefitStatus: RentalCleaningContextBenefitStatusEnum | null;
    /**
     * 
     */
    promoCode: string | null;
    /**
     * 
     */
    cleaningFlowAvailable: boolean;
}


/**
 * @export
 */
export const RentalCleaningContextBenefitStatusEnum = {
    Available: 'AVAILABLE',
    Reserved: 'RESERVED',
    Redeemed: 'REDEEMED',
    Revoked: 'REVOKED',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalCleaningContextBenefitStatusEnum = typeof RentalCleaningContextBenefitStatusEnum[keyof typeof RentalCleaningContextBenefitStatusEnum];


/**
 * Check if a given object implements the RentalCleaningContext interface.
 */
export function instanceOfRentalCleaningContext(value: object): value is RentalCleaningContext {
    if (!('rentalBookingId' in value) || value['rentalBookingId'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('checkOutDate' in value) || value['checkOutDate'] === undefined) return false;
    if (!('earliestBenefitCleaningDate' in value) || value['earliestBenefitCleaningDate'] === undefined) return false;
    if (!('benefitStatus' in value) || value['benefitStatus'] === undefined) return false;
    if (!('promoCode' in value) || value['promoCode'] === undefined) return false;
    if (!('cleaningFlowAvailable' in value) || value['cleaningFlowAvailable'] === undefined) return false;
    return true;
}

export function RentalCleaningContextFromJSON(json: any): RentalCleaningContext {
    return RentalCleaningContextFromJSONTyped(json, false);
}

export function RentalCleaningContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalCleaningContext {
    if (json == null) {
        return json;
    }
    return {
        
        'rentalBookingId': json['rentalBookingId'],
        'address': json['address'],
        'phone': json['phone'],
        'checkOutDate': (json['checkOutDate'] == null ? json['checkOutDate'] : parseDate(json['checkOutDate'])),
        'earliestBenefitCleaningDate': (json['earliestBenefitCleaningDate'] == null ? json['earliestBenefitCleaningDate'] : parseDate(json['earliestBenefitCleaningDate'])),
        'benefitStatus': json['benefitStatus'],
        'promoCode': json['promoCode'],
        'cleaningFlowAvailable': json['cleaningFlowAvailable'],
    };
}

export function RentalCleaningContextToJSON(json: any): RentalCleaningContext {
    return RentalCleaningContextToJSONTyped(json, false);
}

export function RentalCleaningContextToJSONTyped(value?: RentalCleaningContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rentalBookingId': value['rentalBookingId'],
        'address': value['address'],
        'phone': value['phone'],
        'checkOutDate': value['checkOutDate'] == null ? value['checkOutDate'] : serializeDate(value['checkOutDate']),
        'earliestBenefitCleaningDate': value['earliestBenefitCleaningDate'] == null ? value['earliestBenefitCleaningDate'] : serializeDate(value['earliestBenefitCleaningDate']),
        'benefitStatus': value['benefitStatus'],
        'promoCode': value['promoCode'],
        'cleaningFlowAvailable': value['cleaningFlowAvailable'],
    };
}

