/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RentalTransferBenefit } from './RentalTransferBenefit';
import {
    RentalTransferBenefitFromJSON,
    RentalTransferBenefitFromJSONTyped,
    RentalTransferBenefitToJSON,
    RentalTransferBenefitToJSONTyped,
} from './RentalTransferBenefit';

/**
 * 
 * @export
 * @interface RentalTransferPrefill
 */
export interface RentalTransferPrefill {
    /**
     * 
     */
    rentalBookingId: number;
    /**
     * 
     */
    context: RentalTransferPrefillContextEnum;
    /**
     * 
     */
    direction: RentalTransferPrefillDirectionEnum;
    /**
     * 
     */
    suggestedDate: Date;
    /**
     * 
     */
    address: string;
    /**
     * 
     */
    benefit: RentalTransferBenefit | null;
}


/**
 * @export
 */
export const RentalTransferPrefillContextEnum = {
    Arrival: 'ARRIVAL',
    Checkout: 'CHECKOUT',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalTransferPrefillContextEnum = typeof RentalTransferPrefillContextEnum[keyof typeof RentalTransferPrefillContextEnum];

/**
 * @export
 */
export const RentalTransferPrefillDirectionEnum = {
    ToAirport: 'TO_AIRPORT',
    FromAirport: 'FROM_AIRPORT',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalTransferPrefillDirectionEnum = typeof RentalTransferPrefillDirectionEnum[keyof typeof RentalTransferPrefillDirectionEnum];


/**
 * Check if a given object implements the RentalTransferPrefill interface.
 */
export function instanceOfRentalTransferPrefill(value: object): value is RentalTransferPrefill {
    if (!('rentalBookingId' in value) || value['rentalBookingId'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('suggestedDate' in value) || value['suggestedDate'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('benefit' in value) || value['benefit'] === undefined) return false;
    return true;
}

export function RentalTransferPrefillFromJSON(json: any): RentalTransferPrefill {
    return RentalTransferPrefillFromJSONTyped(json, false);
}

export function RentalTransferPrefillFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalTransferPrefill {
    if (json == null) {
        return json;
    }
    return {
        
        'rentalBookingId': json['rentalBookingId'],
        'context': json['context'],
        'direction': json['direction'],
        'suggestedDate': (json['suggestedDate'] == null ? json['suggestedDate'] : parseDate(json['suggestedDate'])),
        'address': json['address'],
        'benefit': RentalTransferBenefitFromJSON(json['benefit']),
    };
}

export function RentalTransferPrefillToJSON(json: any): RentalTransferPrefill {
    return RentalTransferPrefillToJSONTyped(json, false);
}

export function RentalTransferPrefillToJSONTyped(value?: RentalTransferPrefill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rentalBookingId': value['rentalBookingId'],
        'context': value['context'],
        'direction': value['direction'],
        'suggestedDate': value['suggestedDate'] == null ? value['suggestedDate'] : serializeDate(value['suggestedDate']),
        'address': value['address'],
        'benefit': RentalTransferBenefitToJSON(value['benefit']),
    };
}

