/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RentalBooking } from './RentalBooking';
import {
    RentalBookingFromJSON,
    RentalBookingFromJSONTyped,
    RentalBookingToJSON,
    RentalBookingToJSONTyped,
} from './RentalBooking';

/**
 * 
 * @export
 * @interface RentalBookingCursorPage
 */
export interface RentalBookingCursorPage {
    /**
     * 
     */
    items: Array<RentalBooking>;
    /**
     * 
     */
    nextCursor?: string | null;
    /**
     * 
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the RentalBookingCursorPage interface.
 */
export function instanceOfRentalBookingCursorPage(value: object): value is RentalBookingCursorPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function RentalBookingCursorPageFromJSON(json: any): RentalBookingCursorPage {
    return RentalBookingCursorPageFromJSONTyped(json, false);
}

export function RentalBookingCursorPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalBookingCursorPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(RentalBookingFromJSON)),
        'nextCursor': json['nextCursor'] === undefined ? undefined : json['nextCursor'] === null ? null : json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function RentalBookingCursorPageToJSON(json: any): RentalBookingCursorPage {
    return RentalBookingCursorPageToJSONTyped(json, false);
}

export function RentalBookingCursorPageToJSONTyped(value?: RentalBookingCursorPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(RentalBookingToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

