/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { RentalTermType } from './RentalTermType';
import {
    RentalTermTypeFromJSON,
    RentalTermTypeFromJSONTyped,
    RentalTermTypeToJSON,
    RentalTermTypeToJSONTyped,
} from './RentalTermType';
import type { RentalBookingProperty } from './RentalBookingProperty';
import {
    RentalBookingPropertyFromJSON,
    RentalBookingPropertyFromJSONTyped,
    RentalBookingPropertyToJSON,
    RentalBookingPropertyToJSONTyped,
} from './RentalBookingProperty';

/**
 * 
 * @export
 * @interface RentalBooking
 */
export interface RentalBooking {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    property: RentalBookingProperty;
    /**
     * 
     */
    termType: RentalTermType;
    /**
     * 
     */
    checkInDate: Date;
    /**
     * 
     */
    checkOutDate: Date;
    /**
     * 
     */
    rentalMonths: number | null;
    /**
     * 
     */
    durationDays: number;
    /**
     * 
     */
    customerName: string;
    /**
     * 
     */
    phone: string;
    /**
     * 
     */
    guests: number;
    /**
     * 
     */
    comment: string | null;
    /**
     * 
     */
    baseDailyPriceSnapshot: number;
    /**
     * 
     */
    baseMonthlyPriceSnapshot: number | null;
    /**
     * 
     */
    monthlyPriceSnapshot: number | null;
    /**
     * 
     */
    longTermDiscountRateSnapshot: number;
    /**
     * 
     */
    discountAmount: number;
    /**
     * 
     */
    totalPrice: number;
    /**
     * 
     */
    currency: string;
    /**
     * 
     */
    status: RentalBookingStatusEnum;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    cancelledAt: Date | null;
    /**
     * 
     */
    cancellationReason: string | null;
    /**
     * 
     */
    completedAt: Date | null;
    /**
     * 
     */
    money: Money;
}


/**
 * @export
 */
export const RentalBookingStatusEnum = {
    Confirmed: 'CONFIRMED',
    CancelledByCustomer: 'CANCELLED_BY_CUSTOMER',
    CancelledByAdmin: 'CANCELLED_BY_ADMIN',
    Completed: 'COMPLETED',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalBookingStatusEnum = typeof RentalBookingStatusEnum[keyof typeof RentalBookingStatusEnum];


/**
 * Check if a given object implements the RentalBooking interface.
 */
export function instanceOfRentalBooking(value: object): value is RentalBooking {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('property' in value) || value['property'] === undefined) return false;
    if (!('termType' in value) || value['termType'] === undefined) return false;
    if (!('checkInDate' in value) || value['checkInDate'] === undefined) return false;
    if (!('checkOutDate' in value) || value['checkOutDate'] === undefined) return false;
    if (!('rentalMonths' in value) || value['rentalMonths'] === undefined) return false;
    if (!('durationDays' in value) || value['durationDays'] === undefined) return false;
    if (!('customerName' in value) || value['customerName'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('guests' in value) || value['guests'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('baseDailyPriceSnapshot' in value) || value['baseDailyPriceSnapshot'] === undefined) return false;
    if (!('baseMonthlyPriceSnapshot' in value) || value['baseMonthlyPriceSnapshot'] === undefined) return false;
    if (!('monthlyPriceSnapshot' in value) || value['monthlyPriceSnapshot'] === undefined) return false;
    if (!('longTermDiscountRateSnapshot' in value) || value['longTermDiscountRateSnapshot'] === undefined) return false;
    if (!('discountAmount' in value) || value['discountAmount'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('cancelledAt' in value) || value['cancelledAt'] === undefined) return false;
    if (!('cancellationReason' in value) || value['cancellationReason'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('money' in value) || value['money'] === undefined) return false;
    return true;
}

export function RentalBookingFromJSON(json: any): RentalBooking {
    return RentalBookingFromJSONTyped(json, false);
}

export function RentalBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalBooking {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'property': RentalBookingPropertyFromJSON(json['property']),
        'termType': RentalTermTypeFromJSON(json['termType']),
        'checkInDate': (json['checkInDate'] == null ? json['checkInDate'] : parseDate(json['checkInDate'])),
        'checkOutDate': (json['checkOutDate'] == null ? json['checkOutDate'] : parseDate(json['checkOutDate'])),
        'rentalMonths': json['rentalMonths'],
        'durationDays': json['durationDays'],
        'customerName': json['customerName'],
        'phone': json['phone'],
        'guests': json['guests'],
        'comment': json['comment'],
        'baseDailyPriceSnapshot': json['baseDailyPriceSnapshot'],
        'baseMonthlyPriceSnapshot': json['baseMonthlyPriceSnapshot'],
        'monthlyPriceSnapshot': json['monthlyPriceSnapshot'],
        'longTermDiscountRateSnapshot': json['longTermDiscountRateSnapshot'],
        'discountAmount': json['discountAmount'],
        'totalPrice': json['totalPrice'],
        'currency': json['currency'],
        'status': json['status'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'cancelledAt': (json['cancelledAt'] == null ? null : parseDateTime(json['cancelledAt'])),
        'cancellationReason': json['cancellationReason'],
        'completedAt': (json['completedAt'] == null ? null : parseDateTime(json['completedAt'])),
        'money': MoneyFromJSON(json['money']),
    };
}

export function RentalBookingToJSON(json: any): RentalBooking {
    return RentalBookingToJSONTyped(json, false);
}

export function RentalBookingToJSONTyped(value?: RentalBooking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'property': RentalBookingPropertyToJSON(value['property']),
        'termType': RentalTermTypeToJSON(value['termType']),
        'checkInDate': value['checkInDate'] == null ? value['checkInDate'] : serializeDate(value['checkInDate']),
        'checkOutDate': value['checkOutDate'] == null ? value['checkOutDate'] : serializeDate(value['checkOutDate']),
        'rentalMonths': value['rentalMonths'],
        'durationDays': value['durationDays'],
        'customerName': value['customerName'],
        'phone': value['phone'],
        'guests': value['guests'],
        'comment': value['comment'],
        'baseDailyPriceSnapshot': value['baseDailyPriceSnapshot'],
        'baseMonthlyPriceSnapshot': value['baseMonthlyPriceSnapshot'],
        'monthlyPriceSnapshot': value['monthlyPriceSnapshot'],
        'longTermDiscountRateSnapshot': value['longTermDiscountRateSnapshot'],
        'discountAmount': value['discountAmount'],
        'totalPrice': value['totalPrice'],
        'currency': value['currency'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : serializeDateTime(value['cancelledAt']),
        'cancellationReason': value['cancellationReason'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : serializeDateTime(value['completedAt']),
        'money': MoneyToJSON(value['money']),
    };
}

