/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentalBookingProperty
 */
export interface RentalBookingProperty {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    titleRu: string | null;
    /**
     * 
     */
    titleEn: string;
    /**
     * 
     */
    area: string;
}

/**
 * Check if a given object implements the RentalBookingProperty interface.
 */
export function instanceOfRentalBookingProperty(value: object): value is RentalBookingProperty {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('titleRu' in value) || value['titleRu'] === undefined) return false;
    if (!('titleEn' in value) || value['titleEn'] === undefined) return false;
    if (!('area' in value) || value['area'] === undefined) return false;
    return true;
}

export function RentalBookingPropertyFromJSON(json: any): RentalBookingProperty {
    return RentalBookingPropertyFromJSONTyped(json, false);
}

export function RentalBookingPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalBookingProperty {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'titleRu': json['titleRu'],
        'titleEn': json['titleEn'],
        'area': json['area'],
    };
}

export function RentalBookingPropertyToJSON(json: any): RentalBookingProperty {
    return RentalBookingPropertyToJSONTyped(json, false);
}

export function RentalBookingPropertyToJSONTyped(value?: RentalBookingProperty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'titleRu': value['titleRu'],
        'titleEn': value['titleEn'],
        'area': value['area'],
    };
}

