/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RentalTermType = {
    DateRange: 'DATE_RANGE',
    Monthly: 'MONTHLY',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RentalTermType = typeof RentalTermType[keyof typeof RentalTermType];


export function instanceOfRentalTermType(value: any): boolean {
    for (const key in RentalTermType) {
        if (Object.prototype.hasOwnProperty.call(RentalTermType, key)) {
            if (RentalTermType[key as keyof typeof RentalTermType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RentalTermTypeFromJSON(json: any): RentalTermType {
    return RentalTermTypeFromJSONTyped(json, false);
}

export function RentalTermTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentalTermType {
    return json as RentalTermType;
}

export function RentalTermTypeToJSON(value?: RentalTermType | null): any {
    return value as any;
}

export function RentalTermTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RentalTermType {
    return value as RentalTermType;
}

