/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepeatCleaningAction
 */
export interface RepeatCleaningAction {
    /**
     * 
     */
    type: RepeatCleaningActionTypeEnum;
    /**
     * 
     */
    sourceOrderId: number;
}


/**
 * @export
 */
export const RepeatCleaningActionTypeEnum = {
    RepeatCleaning: 'REPEAT_CLEANING',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RepeatCleaningActionTypeEnum = typeof RepeatCleaningActionTypeEnum[keyof typeof RepeatCleaningActionTypeEnum];


/**
 * Check if a given object implements the RepeatCleaningAction interface.
 */
export function instanceOfRepeatCleaningAction(value: object): value is RepeatCleaningAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'REPEAT_CLEANING') return false;
    
    if (!('sourceOrderId' in value) || value['sourceOrderId'] === undefined) return false;
    return true;
}

export function RepeatCleaningActionFromJSON(json: any): RepeatCleaningAction {
    return RepeatCleaningActionFromJSONTyped(json, false);
}

export function RepeatCleaningActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepeatCleaningAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'sourceOrderId': json['sourceOrderId'],
    };
}

export function RepeatCleaningActionToJSON(json: any): RepeatCleaningAction {
    return RepeatCleaningActionToJSONTyped(json, false);
}

export function RepeatCleaningActionToJSONTyped(value?: RepeatCleaningAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'sourceOrderId': value['sourceOrderId'],
    };
}

