/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepeatTransferAction
 */
export interface RepeatTransferAction {
    /**
     * 
     */
    type: RepeatTransferActionTypeEnum;
    /**
     * 
     */
    sourceBookingId: number;
}


/**
 * @export
 */
export const RepeatTransferActionTypeEnum = {
    RepeatTransfer: 'REPEAT_TRANSFER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RepeatTransferActionTypeEnum = typeof RepeatTransferActionTypeEnum[keyof typeof RepeatTransferActionTypeEnum];


/**
 * Check if a given object implements the RepeatTransferAction interface.
 */
export function instanceOfRepeatTransferAction(value: object): value is RepeatTransferAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'REPEAT_TRANSFER') return false;
    
    if (!('sourceBookingId' in value) || value['sourceBookingId'] === undefined) return false;
    return true;
}

export function RepeatTransferActionFromJSON(json: any): RepeatTransferAction {
    return RepeatTransferActionFromJSONTyped(json, false);
}

export function RepeatTransferActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepeatTransferAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'sourceBookingId': json['sourceBookingId'],
    };
}

export function RepeatTransferActionToJSON(json: any): RepeatTransferAction {
    return RepeatTransferActionToJSONTyped(json, false);
}

export function RepeatTransferActionToJSONTyped(value?: RepeatTransferAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'sourceBookingId': value['sourceBookingId'],
    };
}

