/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensitiveProof
 */
export interface SensitiveProof {
    /**
     * 
     */
    challengeId: string;
    /**
     * 
     */
    identityToken?: string | null;
    /**
     * 
     */
    telegramInitData?: string | null;
}

/**
 * Check if a given object implements the SensitiveProof interface.
 */
export function instanceOfSensitiveProof(value: object): value is SensitiveProof {
    if (!('challengeId' in value) || value['challengeId'] === undefined) return false;
    return true;
}

export function SensitiveProofFromJSON(json: any): SensitiveProof {
    return SensitiveProofFromJSONTyped(json, false);
}

export function SensitiveProofFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensitiveProof {
    if (json == null) {
        return json;
    }
    return {
        
        'challengeId': json['challengeId'],
        'identityToken': json['identityToken'] === undefined ? undefined : json['identityToken'] === null ? null : json['identityToken'],
        'telegramInitData': json['telegramInitData'] === undefined ? undefined : json['telegramInitData'] === null ? null : json['telegramInitData'],
    };
}

export function SensitiveProofToJSON(json: any): SensitiveProof {
    return SensitiveProofToJSONTyped(json, false);
}

export function SensitiveProofToJSONTyped(value?: SensitiveProof | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challengeId': value['challengeId'],
        'identityToken': value['identityToken'],
        'telegramInitData': value['telegramInitData'],
    };
}

