/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SessionTokens
 */
export interface SessionTokens {
    /**
     * 
     */
    sessionId: string;
    /**
     * 
     */
    tokenType: SessionTokensTokenTypeEnum;
    /**
     * 
     */
    accessToken: string;
    /**
     * 
     */
    refreshToken: string;
    /**
     * 
     */
    accessExpiresAt: Date;
    /**
     * 
     */
    refreshExpiresAt: Date;
    /**
     * 
     */
    absoluteExpiresAt: Date;
}


/**
 * @export
 */
export const SessionTokensTokenTypeEnum = {
    Bearer: 'Bearer',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type SessionTokensTokenTypeEnum = typeof SessionTokensTokenTypeEnum[keyof typeof SessionTokensTokenTypeEnum];


/**
 * Check if a given object implements the SessionTokens interface.
 */
export function instanceOfSessionTokens(value: object): value is SessionTokens {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (value['tokenType'] !== 'Bearer') return false;
    
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('accessExpiresAt' in value) || value['accessExpiresAt'] === undefined) return false;
    if (!('refreshExpiresAt' in value) || value['refreshExpiresAt'] === undefined) return false;
    if (!('absoluteExpiresAt' in value) || value['absoluteExpiresAt'] === undefined) return false;
    return true;
}

export function SessionTokensFromJSON(json: any): SessionTokens {
    return SessionTokensFromJSONTyped(json, false);
}

export function SessionTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'tokenType': json['tokenType'],
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'accessExpiresAt': (json['accessExpiresAt'] == null ? json['accessExpiresAt'] : parseDateTime(json['accessExpiresAt'])),
        'refreshExpiresAt': (json['refreshExpiresAt'] == null ? json['refreshExpiresAt'] : parseDateTime(json['refreshExpiresAt'])),
        'absoluteExpiresAt': (json['absoluteExpiresAt'] == null ? json['absoluteExpiresAt'] : parseDateTime(json['absoluteExpiresAt'])),
    };
}

export function SessionTokensToJSON(json: any): SessionTokens {
    return SessionTokensToJSONTyped(json, false);
}

export function SessionTokensToJSONTyped(value?: SessionTokens | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'tokenType': value['tokenType'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'accessExpiresAt': value['accessExpiresAt'] == null ? value['accessExpiresAt'] : serializeDateTime(value['accessExpiresAt']),
        'refreshExpiresAt': value['refreshExpiresAt'] == null ? value['refreshExpiresAt'] : serializeDateTime(value['refreshExpiresAt']),
        'absoluteExpiresAt': value['absoluteExpiresAt'] == null ? value['absoluteExpiresAt'] : serializeDateTime(value['absoluteExpiresAt']),
    };
}

