/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartRentalTransferAction
 */
export interface StartRentalTransferAction {
    /**
     * 
     */
    type: StartRentalTransferActionTypeEnum;
    /**
     * 
     */
    rentalBookingId: number;
    /**
     * 
     */
    context: StartRentalTransferActionContextEnum;
}


/**
 * @export
 */
export const StartRentalTransferActionTypeEnum = {
    StartRentalTransfer: 'START_RENTAL_TRANSFER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type StartRentalTransferActionTypeEnum = typeof StartRentalTransferActionTypeEnum[keyof typeof StartRentalTransferActionTypeEnum];

/**
 * @export
 */
export const StartRentalTransferActionContextEnum = {
    Arrival: 'ARRIVAL',
    Checkout: 'CHECKOUT',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type StartRentalTransferActionContextEnum = typeof StartRentalTransferActionContextEnum[keyof typeof StartRentalTransferActionContextEnum];


/**
 * Check if a given object implements the StartRentalTransferAction interface.
 */
export function instanceOfStartRentalTransferAction(value: object): value is StartRentalTransferAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'START_RENTAL_TRANSFER') return false;
    
    if (!('rentalBookingId' in value) || value['rentalBookingId'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    return true;
}

export function StartRentalTransferActionFromJSON(json: any): StartRentalTransferAction {
    return StartRentalTransferActionFromJSONTyped(json, false);
}

export function StartRentalTransferActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartRentalTransferAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'rentalBookingId': json['rentalBookingId'],
        'context': json['context'],
    };
}

export function StartRentalTransferActionToJSON(json: any): StartRentalTransferAction {
    return StartRentalTransferActionToJSONTyped(json, false);
}

export function StartRentalTransferActionToJSONTyped(value?: StartRentalTransferAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'rentalBookingId': value['rentalBookingId'],
        'context': value['context'],
    };
}

