/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartRentalCleaningAction
 */
export interface StartRentalCleaningAction {
    /**
     * 
     */
    type: StartRentalCleaningActionTypeEnum;
    /**
     * 
     */
    rentalBookingId: number;
}


/**
 * @export
 */
export const StartRentalCleaningActionTypeEnum = {
    StartRentalCleaning: 'START_RENTAL_CLEANING',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type StartRentalCleaningActionTypeEnum = typeof StartRentalCleaningActionTypeEnum[keyof typeof StartRentalCleaningActionTypeEnum];


/**
 * Check if a given object implements the StartRentalCleaningAction interface.
 */
export function instanceOfStartRentalCleaningAction(value: object): value is StartRentalCleaningAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'START_RENTAL_CLEANING') return false;
    
    if (!('rentalBookingId' in value) || value['rentalBookingId'] === undefined) return false;
    return true;
}

export function StartRentalCleaningActionFromJSON(json: any): StartRentalCleaningAction {
    return StartRentalCleaningActionFromJSONTyped(json, false);
}

export function StartRentalCleaningActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartRentalCleaningAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'rentalBookingId': json['rentalBookingId'],
    };
}

export function StartRentalCleaningActionToJSON(json: any): StartRentalCleaningAction {
    return StartRentalCleaningActionToJSONTyped(json, false);
}

export function StartRentalCleaningActionToJSONTyped(value?: StartRentalCleaningAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'rentalBookingId': value['rentalBookingId'],
    };
}

