/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SupportCase
 */
export interface SupportCase {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    service: SupportCaseServiceEnum;
    /**
     * 
     */
    sourceEntityId: number;
    /**
     * 
     */
    category: SupportCaseCategoryEnum;
    /**
     * 
     */
    status: SupportCaseStatusEnum;
    /**
     * 
     */
    description: string | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    resolvedAt: Date | null;
    /**
     * 
     */
    resolutionComment: string | null;
}


/**
 * @export
 */
export const SupportCaseServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type SupportCaseServiceEnum = typeof SupportCaseServiceEnum[keyof typeof SupportCaseServiceEnum];

/**
 * @export
 */
export const SupportCaseCategoryEnum = {
    ProviderLate: 'PROVIDER_LATE',
    ProviderNoShow: 'PROVIDER_NO_SHOW',
    QualityProblem: 'QUALITY_PROBLEM',
    BookingProblem: 'BOOKING_PROBLEM',
    Other: 'OTHER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type SupportCaseCategoryEnum = typeof SupportCaseCategoryEnum[keyof typeof SupportCaseCategoryEnum];

/**
 * @export
 */
export const SupportCaseStatusEnum = {
    Open: 'OPEN',
    Resolved: 'RESOLVED',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type SupportCaseStatusEnum = typeof SupportCaseStatusEnum[keyof typeof SupportCaseStatusEnum];


/**
 * Check if a given object implements the SupportCase interface.
 */
export function instanceOfSupportCase(value: object): value is SupportCase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('sourceEntityId' in value) || value['sourceEntityId'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('resolvedAt' in value) || value['resolvedAt'] === undefined) return false;
    if (!('resolutionComment' in value) || value['resolutionComment'] === undefined) return false;
    return true;
}

export function SupportCaseFromJSON(json: any): SupportCase {
    return SupportCaseFromJSONTyped(json, false);
}

export function SupportCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportCase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'service': json['service'],
        'sourceEntityId': json['sourceEntityId'],
        'category': json['category'],
        'status': json['status'],
        'description': json['description'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'resolvedAt': (json['resolvedAt'] == null ? null : parseDateTime(json['resolvedAt'])),
        'resolutionComment': json['resolutionComment'],
    };
}

export function SupportCaseToJSON(json: any): SupportCase {
    return SupportCaseToJSONTyped(json, false);
}

export function SupportCaseToJSONTyped(value?: SupportCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'service': value['service'],
        'sourceEntityId': value['sourceEntityId'],
        'category': value['category'],
        'status': value['status'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'resolvedAt': value['resolvedAt'] == null ? value['resolvedAt'] : serializeDateTime(value['resolvedAt']),
        'resolutionComment': value['resolutionComment'],
    };
}

