/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TelegramLoginAttempt
 */
export interface TelegramLoginAttempt {
    /**
     * 
     */
    attemptId: string;
    /**
     * 
     */
    botUrl: string;
    /**
     * 
     */
    verifier: string;
    /**
     * 
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the TelegramLoginAttempt interface.
 */
export function instanceOfTelegramLoginAttempt(value: object): value is TelegramLoginAttempt {
    if (!('attemptId' in value) || value['attemptId'] === undefined) return false;
    if (!('botUrl' in value) || value['botUrl'] === undefined) return false;
    if (!('verifier' in value) || value['verifier'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function TelegramLoginAttemptFromJSON(json: any): TelegramLoginAttempt {
    return TelegramLoginAttemptFromJSONTyped(json, false);
}

export function TelegramLoginAttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelegramLoginAttempt {
    if (json == null) {
        return json;
    }
    return {
        
        'attemptId': json['attemptId'],
        'botUrl': json['botUrl'],
        'verifier': json['verifier'],
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
    };
}

export function TelegramLoginAttemptToJSON(json: any): TelegramLoginAttempt {
    return TelegramLoginAttemptToJSONTyped(json, false);
}

export function TelegramLoginAttemptToJSONTyped(value?: TelegramLoginAttempt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attemptId': value['attemptId'],
        'botUrl': value['botUrl'],
        'verifier': value['verifier'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
    };
}

