/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferQuote
 */
export interface TransferQuote {
    /**
     * 
     */
    baseAmount: number;
    /**
     * 
     */
    discountAmount: number;
    /**
     * 
     */
    payableAmount: number;
    /**
     * 
     */
    currency: string;
    /**
     * 
     */
    appliedBenefit: TransferQuoteAppliedBenefitEnum | null;
}


/**
 * @export
 */
export const TransferQuoteAppliedBenefitEnum = {
    RentalFirstTransfer: 'RENTAL_FIRST_TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type TransferQuoteAppliedBenefitEnum = typeof TransferQuoteAppliedBenefitEnum[keyof typeof TransferQuoteAppliedBenefitEnum];


/**
 * Check if a given object implements the TransferQuote interface.
 */
export function instanceOfTransferQuote(value: object): value is TransferQuote {
    if (!('baseAmount' in value) || value['baseAmount'] === undefined) return false;
    if (!('discountAmount' in value) || value['discountAmount'] === undefined) return false;
    if (!('payableAmount' in value) || value['payableAmount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('appliedBenefit' in value) || value['appliedBenefit'] === undefined) return false;
    return true;
}

export function TransferQuoteFromJSON(json: any): TransferQuote {
    return TransferQuoteFromJSONTyped(json, false);
}

export function TransferQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferQuote {
    if (json == null) {
        return json;
    }
    return {
        
        'baseAmount': json['baseAmount'],
        'discountAmount': json['discountAmount'],
        'payableAmount': json['payableAmount'],
        'currency': json['currency'],
        'appliedBenefit': json['appliedBenefit'],
    };
}

export function TransferQuoteToJSON(json: any): TransferQuote {
    return TransferQuoteToJSONTyped(json, false);
}

export function TransferQuoteToJSONTyped(value?: TransferQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseAmount': value['baseAmount'],
        'discountAmount': value['discountAmount'],
        'payableAmount': value['payableAmount'],
        'currency': value['currency'],
        'appliedBenefit': value['appliedBenefit'],
    };
}

