/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferPrice
 */
export interface TransferPrice {
    /**
     * 
     */
    airportId: number;
    /**
     * 
     */
    vehicleTypeId: number;
    /**
     * 
     */
    direction: TransferPriceDirectionEnum;
    /**
     * 
     */
    amount: number;
    /**
     * 
     */
    currency: string;
}


/**
 * @export
 */
export const TransferPriceDirectionEnum = {
    ToAirport: 'TO_AIRPORT',
    FromAirport: 'FROM_AIRPORT',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type TransferPriceDirectionEnum = typeof TransferPriceDirectionEnum[keyof typeof TransferPriceDirectionEnum];


/**
 * Check if a given object implements the TransferPrice interface.
 */
export function instanceOfTransferPrice(value: object): value is TransferPrice {
    if (!('airportId' in value) || value['airportId'] === undefined) return false;
    if (!('vehicleTypeId' in value) || value['vehicleTypeId'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function TransferPriceFromJSON(json: any): TransferPrice {
    return TransferPriceFromJSONTyped(json, false);
}

export function TransferPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'airportId': json['airportId'],
        'vehicleTypeId': json['vehicleTypeId'],
        'direction': json['direction'],
        'amount': json['amount'],
        'currency': json['currency'],
    };
}

export function TransferPriceToJSON(json: any): TransferPrice {
    return TransferPriceToJSONTyped(json, false);
}

export function TransferPriceToJSONTyped(value?: TransferPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'airportId': value['airportId'],
        'vehicleTypeId': value['vehicleTypeId'],
        'direction': value['direction'],
        'amount': value['amount'],
        'currency': value['currency'],
    };
}

