/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferVehicleType
 */
export interface TransferVehicleType {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    nameRu: string;
    /**
     * 
     */
    nameEn: string;
    /**
     * 
     */
    maxPassengers: number;
    /**
     * 
     */
    maxLuggage: number;
}

/**
 * Check if a given object implements the TransferVehicleType interface.
 */
export function instanceOfTransferVehicleType(value: object): value is TransferVehicleType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('nameRu' in value) || value['nameRu'] === undefined) return false;
    if (!('nameEn' in value) || value['nameEn'] === undefined) return false;
    if (!('maxPassengers' in value) || value['maxPassengers'] === undefined) return false;
    if (!('maxLuggage' in value) || value['maxLuggage'] === undefined) return false;
    return true;
}

export function TransferVehicleTypeFromJSON(json: any): TransferVehicleType {
    return TransferVehicleTypeFromJSONTyped(json, false);
}

export function TransferVehicleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferVehicleType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'nameRu': json['nameRu'],
        'nameEn': json['nameEn'],
        'maxPassengers': json['maxPassengers'],
        'maxLuggage': json['maxLuggage'],
    };
}

export function TransferVehicleTypeToJSON(json: any): TransferVehicleType {
    return TransferVehicleTypeToJSONTyped(json, false);
}

export function TransferVehicleTypeToJSONTyped(value?: TransferVehicleType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'nameRu': value['nameRu'],
        'nameEn': value['nameEn'],
        'maxPassengers': value['maxPassengers'],
        'maxLuggage': value['maxLuggage'],
    };
}

