/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferAirport
 */
export interface TransferAirport {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    nameRu: string;
    /**
     * 
     */
    nameEn: string;
}

/**
 * Check if a given object implements the TransferAirport interface.
 */
export function instanceOfTransferAirport(value: object): value is TransferAirport {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('nameRu' in value) || value['nameRu'] === undefined) return false;
    if (!('nameEn' in value) || value['nameEn'] === undefined) return false;
    return true;
}

export function TransferAirportFromJSON(json: any): TransferAirport {
    return TransferAirportFromJSONTyped(json, false);
}

export function TransferAirportFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferAirport {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'nameRu': json['nameRu'],
        'nameEn': json['nameEn'],
    };
}

export function TransferAirportToJSON(json: any): TransferAirport {
    return TransferAirportToJSONTyped(json, false);
}

export function TransferAirportToJSONTyped(value?: TransferAirport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'nameRu': value['nameRu'],
        'nameEn': value['nameEn'],
    };
}

