/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionFeedback
 */
export interface TransactionFeedback {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    outcome: TransactionFeedbackOutcomeEnum;
    /**
     * 
     */
    category: TransactionFeedbackCategoryEnum | null;
    /**
     * 
     */
    comment: string | null;
    /**
     * 
     */
    supportCaseId: number | null;
    /**
     * 
     */
    createdAt: Date;
}


/**
 * @export
 */
export const TransactionFeedbackOutcomeEnum = {
    Good: 'GOOD',
    Problem: 'PROBLEM',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type TransactionFeedbackOutcomeEnum = typeof TransactionFeedbackOutcomeEnum[keyof typeof TransactionFeedbackOutcomeEnum];

/**
 * @export
 */
export const TransactionFeedbackCategoryEnum = {
    ProviderLate: 'PROVIDER_LATE',
    ProviderNoShow: 'PROVIDER_NO_SHOW',
    QualityProblem: 'QUALITY_PROBLEM',
    BookingProblem: 'BOOKING_PROBLEM',
    Other: 'OTHER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type TransactionFeedbackCategoryEnum = typeof TransactionFeedbackCategoryEnum[keyof typeof TransactionFeedbackCategoryEnum];


/**
 * Check if a given object implements the TransactionFeedback interface.
 */
export function instanceOfTransactionFeedback(value: object): value is TransactionFeedback {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('supportCaseId' in value) || value['supportCaseId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TransactionFeedbackFromJSON(json: any): TransactionFeedback {
    return TransactionFeedbackFromJSONTyped(json, false);
}

export function TransactionFeedbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionFeedback {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'outcome': json['outcome'],
        'category': json['category'],
        'comment': json['comment'],
        'supportCaseId': json['supportCaseId'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function TransactionFeedbackToJSON(json: any): TransactionFeedback {
    return TransactionFeedbackToJSONTyped(json, false);
}

export function TransactionFeedbackToJSONTyped(value?: TransactionFeedback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'outcome': value['outcome'],
        'category': value['category'],
        'comment': value['comment'],
        'supportCaseId': value['supportCaseId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

