/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferBooking } from './TransferBooking';
import {
    TransferBookingFromJSON,
    TransferBookingFromJSONTyped,
    TransferBookingToJSON,
    TransferBookingToJSONTyped,
} from './TransferBooking';

/**
 * 
 * @export
 * @interface TransferBookingCursorPage
 */
export interface TransferBookingCursorPage {
    /**
     * 
     */
    items: Array<TransferBooking>;
    /**
     * 
     */
    nextCursor?: string | null;
    /**
     * 
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the TransferBookingCursorPage interface.
 */
export function instanceOfTransferBookingCursorPage(value: object): value is TransferBookingCursorPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function TransferBookingCursorPageFromJSON(json: any): TransferBookingCursorPage {
    return TransferBookingCursorPageFromJSONTyped(json, false);
}

export function TransferBookingCursorPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferBookingCursorPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TransferBookingFromJSON)),
        'nextCursor': json['nextCursor'] === undefined ? undefined : json['nextCursor'] === null ? null : json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function TransferBookingCursorPageToJSON(json: any): TransferBookingCursorPage {
    return TransferBookingCursorPageToJSONTyped(json, false);
}

export function TransferBookingCursorPageToJSONTyped(value?: TransferBookingCursorPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TransferBookingToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

