/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupportCase } from './SupportCase';
import {
    SupportCaseFromJSON,
    SupportCaseFromJSONTyped,
    SupportCaseToJSON,
    SupportCaseToJSONTyped,
} from './SupportCase';
import type { TransactionFeedback } from './TransactionFeedback';
import {
    TransactionFeedbackFromJSON,
    TransactionFeedbackFromJSONTyped,
    TransactionFeedbackToJSON,
    TransactionFeedbackToJSONTyped,
} from './TransactionFeedback';

/**
 * 
 * @export
 * @interface TransactionSupport
 */
export interface TransactionSupport {
    /**
     * 
     */
    service: TransactionSupportServiceEnum;
    /**
     * 
     */
    sourceEntityId: number;
    /**
     * 
     */
    feedbackEligible: boolean;
    /**
     * 
     */
    feedback: TransactionFeedback | null;
    /**
     * 
     */
    latestCase: SupportCase | null;
}


/**
 * @export
 */
export const TransactionSupportServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    Unknown: 'UNKNOWN',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type TransactionSupportServiceEnum = typeof TransactionSupportServiceEnum[keyof typeof TransactionSupportServiceEnum];


/**
 * Check if a given object implements the TransactionSupport interface.
 */
export function instanceOfTransactionSupport(value: object): value is TransactionSupport {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('sourceEntityId' in value) || value['sourceEntityId'] === undefined) return false;
    if (!('feedbackEligible' in value) || value['feedbackEligible'] === undefined) return false;
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    if (!('latestCase' in value) || value['latestCase'] === undefined) return false;
    return true;
}

export function TransactionSupportFromJSON(json: any): TransactionSupport {
    return TransactionSupportFromJSONTyped(json, false);
}

export function TransactionSupportFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionSupport {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'sourceEntityId': json['sourceEntityId'],
        'feedbackEligible': json['feedbackEligible'],
        'feedback': TransactionFeedbackFromJSON(json['feedback']),
        'latestCase': SupportCaseFromJSON(json['latestCase']),
    };
}

export function TransactionSupportToJSON(json: any): TransactionSupport {
    return TransactionSupportToJSONTyped(json, false);
}

export function TransactionSupportToJSONTyped(value?: TransactionSupport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'sourceEntityId': value['sourceEntityId'],
        'feedbackEligible': value['feedbackEligible'],
        'feedback': TransactionFeedbackToJSON(value['feedback']),
        'latestCase': SupportCaseToJSON(value['latestCase']),
    };
}

