/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyIdentityLinkRequest
 */
export interface VerifyIdentityLinkRequest {
    /**
     * 
     */
    identityToken?: string | null;
    /**
     * 
     */
    authorizationCode?: string | null;
}

/**
 * Check if a given object implements the VerifyIdentityLinkRequest interface.
 */
export function instanceOfVerifyIdentityLinkRequest(value: object): value is VerifyIdentityLinkRequest {
    return true;
}

export function VerifyIdentityLinkRequestFromJSON(json: any): VerifyIdentityLinkRequest {
    return VerifyIdentityLinkRequestFromJSONTyped(json, false);
}

export function VerifyIdentityLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyIdentityLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identityToken': json['identityToken'] === undefined ? undefined : json['identityToken'] === null ? null : json['identityToken'],
        'authorizationCode': json['authorizationCode'] === undefined ? undefined : json['authorizationCode'] === null ? null : json['authorizationCode'],
    };
}

export function VerifyIdentityLinkRequestToJSON(json: any): VerifyIdentityLinkRequest {
    return VerifyIdentityLinkRequestToJSONTyped(json, false);
}

export function VerifyIdentityLinkRequestToJSONTyped(value?: VerifyIdentityLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identityToken': value['identityToken'],
        'authorizationCode': value['authorizationCode'],
    };
}

