/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccountIdentities,
    AccountIdentitiesFromJSON,
    AccountIdentitiesToJSON,
} from '../models/AccountIdentities';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CommunicationEndpoint,
    CommunicationEndpointFromJSON,
    CommunicationEndpointToJSON,
} from '../models/CommunicationEndpoint';
import {
    type ConfirmIdentityLinkRequest,
    ConfirmIdentityLinkRequestFromJSON,
    ConfirmIdentityLinkRequestToJSON,
} from '../models/ConfirmIdentityLinkRequest';
import {
    type CreateIdentityLinkRequest,
    CreateIdentityLinkRequestFromJSON,
    CreateIdentityLinkRequestToJSON,
} from '../models/CreateIdentityLinkRequest';
import {
    type CustomerActivity,
    CustomerActivityFromJSON,
    CustomerActivityToJSON,
} from '../models/CustomerActivity';
import {
    type CustomerHome,
    CustomerHomeFromJSON,
    CustomerHomeToJSON,
} from '../models/CustomerHome';
import {
    type CustomerProfile,
    CustomerProfileFromJSON,
    CustomerProfileToJSON,
} from '../models/CustomerProfile';
import {
    type IdentityLinkAttempt,
    IdentityLinkAttemptFromJSON,
    IdentityLinkAttemptToJSON,
} from '../models/IdentityLinkAttempt';
import {
    type NotificationCursorPage,
    NotificationCursorPageFromJSON,
    NotificationCursorPageToJSON,
} from '../models/NotificationCursorPage';
import {
    type NotificationPreferences,
    NotificationPreferencesFromJSON,
    NotificationPreferencesToJSON,
} from '../models/NotificationPreferences';
import {
    type NotificationUnreadCount,
    NotificationUnreadCountFromJSON,
    NotificationUnreadCountToJSON,
} from '../models/NotificationUnreadCount';
import {
    type ReauthenticationChallenge,
    ReauthenticationChallengeFromJSON,
    ReauthenticationChallengeToJSON,
} from '../models/ReauthenticationChallenge';
import {
    type RegisterCommunicationEndpointRequest,
    RegisterCommunicationEndpointRequestFromJSON,
    RegisterCommunicationEndpointRequestToJSON,
} from '../models/RegisterCommunicationEndpointRequest';
import {
    type SensitiveProof,
    SensitiveProofFromJSON,
    SensitiveProofToJSON,
} from '../models/SensitiveProof';
import {
    type VerifyIdentityLinkRequest,
    VerifyIdentityLinkRequestFromJSON,
    VerifyIdentityLinkRequestToJSON,
} from '../models/VerifyIdentityLinkRequest';

export interface ConfirmAccountDeletionRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    sensitiveProof: SensitiveProof;
}

export interface ConfirmIdentityLinkOperationRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    confirmIdentityLinkRequest: ConfirmIdentityLinkRequest;
}

export interface CreateIdentityLinkOperationRequest {
    /**
     * 
     */
    createIdentityLinkRequest: CreateIdentityLinkRequest;
}

export interface GetNotificationsRequest {
    /**
     * 
     */
    cursor?: string;
    /**
     * 
     */
    size?: number;
}

export interface MarkNotificationReadRequest {
    /**
     * 
     */
    notificationId: number;
}

export interface RegisterCommunicationEndpointOperationRequest {
    /**
     * 
     */
    registerCommunicationEndpointRequest: RegisterCommunicationEndpointRequest;
}

export interface UnlinkIdentityRequest {
    /**
     * 
     */
    identityId: number;
    /**
     * 
     */
    sensitiveProof: SensitiveProof;
}

export interface UnregisterCommunicationEndpointByIdRequest {
    /**
     * 
     */
    id: string;
}

export interface UpdateNotificationPreferencesRequest {
    /**
     * 
     */
    notificationPreferences: NotificationPreferences;
}

export interface VerifyIdentityLinkOperationRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    verifyIdentityLinkRequest: VerifyIdentityLinkRequest;
}

/**
 * AccountApi - interface
 * 
 * @export
 * @interface AccountApiInterface
 */
export interface AccountApiInterface {
    /**
     * Creates request options for confirmAccountDeletion without sending the request
     * @param {string} id 
     * @param {SensitiveProof} sensitiveProof 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    confirmAccountDeletionRequestOpts(requestParameters: ConfirmAccountDeletionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {SensitiveProof} sensitiveProof 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    confirmAccountDeletionRaw(requestParameters: ConfirmAccountDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    confirmAccountDeletion(requestParameters: ConfirmAccountDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for confirmIdentityLink without sending the request
     * @param {string} id 
     * @param {ConfirmIdentityLinkRequest} confirmIdentityLinkRequest 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    confirmIdentityLinkRequestOpts(requestParameters: ConfirmIdentityLinkOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {ConfirmIdentityLinkRequest} confirmIdentityLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    confirmIdentityLinkRaw(requestParameters: ConfirmIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountIdentities>>;

    /**
     */
    confirmIdentityLink(requestParameters: ConfirmIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountIdentities>;

    /**
     * Creates request options for createAccountDeletionRequest without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    createAccountDeletionRequestRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    createAccountDeletionRequestRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReauthenticationChallenge>>;

    /**
     */
    createAccountDeletionRequest(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReauthenticationChallenge>;

    /**
     * Creates request options for createIdentityLink without sending the request
     * @param {CreateIdentityLinkRequest} createIdentityLinkRequest 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    createIdentityLinkRequestOpts(requestParameters: CreateIdentityLinkOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateIdentityLinkRequest} createIdentityLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    createIdentityLinkRaw(requestParameters: CreateIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdentityLinkAttempt>>;

    /**
     */
    createIdentityLink(requestParameters: CreateIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdentityLinkAttempt>;

    /**
     * Creates request options for getAccountIdentities without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getAccountIdentitiesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getAccountIdentitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountIdentities>>;

    /**
     */
    getAccountIdentities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountIdentities>;

    /**
     * Creates request options for getCustomerActivity without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getCustomerActivityRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getCustomerActivityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerActivity>>;

    /**
     */
    getCustomerActivity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerActivity>;

    /**
     * Creates request options for getCustomerHome without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getCustomerHomeRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getCustomerHomeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerHome>>;

    /**
     */
    getCustomerHome(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerHome>;

    /**
     * Creates request options for getCustomerProfile without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getCustomerProfileRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getCustomerProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerProfile>>;

    /**
     */
    getCustomerProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerProfile>;

    /**
     * Creates request options for getNotificationPreferences without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getNotificationPreferencesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getNotificationPreferencesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationPreferences>>;

    /**
     */
    getNotificationPreferences(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationPreferences>;

    /**
     * Creates request options for getNotificationUnreadCount without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getNotificationUnreadCountRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getNotificationUnreadCountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationUnreadCount>>;

    /**
     */
    getNotificationUnreadCount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationUnreadCount>;

    /**
     * Creates request options for getNotifications without sending the request
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getNotificationsRequestOpts(requestParameters: GetNotificationsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getNotificationsRaw(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationCursorPage>>;

    /**
     */
    getNotifications(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationCursorPage>;

    /**
     * Creates request options for markAllNotificationsRead without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    markAllNotificationsReadRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    markAllNotificationsReadRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    markAllNotificationsRead(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for markNotificationRead without sending the request
     * @param {number} notificationId 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    markNotificationReadRequestOpts(requestParameters: MarkNotificationReadRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} notificationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    markNotificationReadRaw(requestParameters: MarkNotificationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    markNotificationRead(requestParameters: MarkNotificationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for registerCommunicationEndpoint without sending the request
     * @param {RegisterCommunicationEndpointRequest} registerCommunicationEndpointRequest 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    registerCommunicationEndpointRequestOpts(requestParameters: RegisterCommunicationEndpointOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {RegisterCommunicationEndpointRequest} registerCommunicationEndpointRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    registerCommunicationEndpointRaw(requestParameters: RegisterCommunicationEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunicationEndpoint>>;

    /**
     */
    registerCommunicationEndpoint(requestParameters: RegisterCommunicationEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunicationEndpoint>;

    /**
     * Creates request options for unlinkIdentity without sending the request
     * @param {number} identityId 
     * @param {SensitiveProof} sensitiveProof 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    unlinkIdentityRequestOpts(requestParameters: UnlinkIdentityRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} identityId 
     * @param {SensitiveProof} sensitiveProof 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    unlinkIdentityRaw(requestParameters: UnlinkIdentityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountIdentities>>;

    /**
     */
    unlinkIdentity(requestParameters: UnlinkIdentityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountIdentities>;

    /**
     * Creates request options for unregisterCommunicationEndpoint without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    unregisterCommunicationEndpointRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    unregisterCommunicationEndpointRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    unregisterCommunicationEndpoint(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for unregisterCommunicationEndpointById without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    unregisterCommunicationEndpointByIdRequestOpts(requestParameters: UnregisterCommunicationEndpointByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    unregisterCommunicationEndpointByIdRaw(requestParameters: UnregisterCommunicationEndpointByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    unregisterCommunicationEndpointById(requestParameters: UnregisterCommunicationEndpointByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateNotificationPreferences without sending the request
     * @param {NotificationPreferences} notificationPreferences 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    updateNotificationPreferencesRequestOpts(requestParameters: UpdateNotificationPreferencesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {NotificationPreferences} notificationPreferences 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    updateNotificationPreferencesRaw(requestParameters: UpdateNotificationPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationPreferences>>;

    /**
     */
    updateNotificationPreferences(requestParameters: UpdateNotificationPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationPreferences>;

    /**
     * Creates request options for verifyIdentityLink without sending the request
     * @param {string} id 
     * @param {VerifyIdentityLinkRequest} verifyIdentityLinkRequest 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    verifyIdentityLinkRequestOpts(requestParameters: VerifyIdentityLinkOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {VerifyIdentityLinkRequest} verifyIdentityLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    verifyIdentityLinkRaw(requestParameters: VerifyIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    verifyIdentityLink(requestParameters: VerifyIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI implements AccountApiInterface {

    /**
     * Creates request options for confirmAccountDeletion without sending the request
     */
    async confirmAccountDeletionRequestOpts(requestParameters: ConfirmAccountDeletionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling confirmAccountDeletion().'
            );
        }

        if (requestParameters['sensitiveProof'] == null) {
            throw new runtime.RequiredError(
                'sensitiveProof',
                'Required parameter "sensitiveProof" was null or undefined when calling confirmAccountDeletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/deletion-requests/{id}/confirm`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SensitiveProofToJSON(requestParameters['sensitiveProof']),
        };
    }

    /**
     */
    async confirmAccountDeletionRaw(requestParameters: ConfirmAccountDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.confirmAccountDeletionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async confirmAccountDeletion(requestParameters: ConfirmAccountDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmAccountDeletionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for confirmIdentityLink without sending the request
     */
    async confirmIdentityLinkRequestOpts(requestParameters: ConfirmIdentityLinkOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling confirmIdentityLink().'
            );
        }

        if (requestParameters['confirmIdentityLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'confirmIdentityLinkRequest',
                'Required parameter "confirmIdentityLinkRequest" was null or undefined when calling confirmIdentityLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/identity-links/{id}/confirm`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmIdentityLinkRequestToJSON(requestParameters['confirmIdentityLinkRequest']),
        };
    }

    /**
     */
    async confirmIdentityLinkRaw(requestParameters: ConfirmIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountIdentities>> {
        const requestOptions = await this.confirmIdentityLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountIdentitiesFromJSON(jsonValue));
    }

    /**
     */
    async confirmIdentityLink(requestParameters: ConfirmIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountIdentities> {
        const response = await this.confirmIdentityLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAccountDeletionRequest without sending the request
     */
    async createAccountDeletionRequestRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/deletion-requests`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createAccountDeletionRequestRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReauthenticationChallenge>> {
        const requestOptions = await this.createAccountDeletionRequestRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReauthenticationChallengeFromJSON(jsonValue));
    }

    /**
     */
    async createAccountDeletionRequest(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReauthenticationChallenge> {
        const response = await this.createAccountDeletionRequestRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createIdentityLink without sending the request
     */
    async createIdentityLinkRequestOpts(requestParameters: CreateIdentityLinkOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createIdentityLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'createIdentityLinkRequest',
                'Required parameter "createIdentityLinkRequest" was null or undefined when calling createIdentityLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/identity-links`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateIdentityLinkRequestToJSON(requestParameters['createIdentityLinkRequest']),
        };
    }

    /**
     */
    async createIdentityLinkRaw(requestParameters: CreateIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdentityLinkAttempt>> {
        const requestOptions = await this.createIdentityLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdentityLinkAttemptFromJSON(jsonValue));
    }

    /**
     */
    async createIdentityLink(requestParameters: CreateIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdentityLinkAttempt> {
        const response = await this.createIdentityLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAccountIdentities without sending the request
     */
    async getAccountIdentitiesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/identities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAccountIdentitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountIdentities>> {
        const requestOptions = await this.getAccountIdentitiesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountIdentitiesFromJSON(jsonValue));
    }

    /**
     */
    async getAccountIdentities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountIdentities> {
        const response = await this.getAccountIdentitiesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCustomerActivity without sending the request
     */
    async getCustomerActivityRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/activity`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCustomerActivityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerActivity>> {
        const requestOptions = await this.getCustomerActivityRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerActivityFromJSON(jsonValue));
    }

    /**
     */
    async getCustomerActivity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerActivity> {
        const response = await this.getCustomerActivityRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCustomerHome without sending the request
     */
    async getCustomerHomeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/home`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCustomerHomeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerHome>> {
        const requestOptions = await this.getCustomerHomeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerHomeFromJSON(jsonValue));
    }

    /**
     */
    async getCustomerHome(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerHome> {
        const response = await this.getCustomerHomeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCustomerProfile without sending the request
     */
    async getCustomerProfileRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/customers/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCustomerProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerProfile>> {
        const requestOptions = await this.getCustomerProfileRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerProfileFromJSON(jsonValue));
    }

    /**
     */
    async getCustomerProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerProfile> {
        const response = await this.getCustomerProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotificationPreferences without sending the request
     */
    async getNotificationPreferencesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/notification-preferences`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationPreferencesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationPreferences>> {
        const requestOptions = await this.getNotificationPreferencesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationPreferencesFromJSON(jsonValue));
    }

    /**
     */
    async getNotificationPreferences(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationPreferences> {
        const response = await this.getNotificationPreferencesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotificationUnreadCount without sending the request
     */
    async getNotificationUnreadCountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/notifications/unread-count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationUnreadCountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationUnreadCount>> {
        const requestOptions = await this.getNotificationUnreadCountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationUnreadCountFromJSON(jsonValue));
    }

    /**
     */
    async getNotificationUnreadCount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationUnreadCount> {
        const response = await this.getNotificationUnreadCountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotifications without sending the request
     */
    async getNotificationsRequestOpts(requestParameters: GetNotificationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/notifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationsRaw(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationCursorPage>> {
        const requestOptions = await this.getNotificationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationCursorPageFromJSON(jsonValue));
    }

    /**
     */
    async getNotifications(requestParameters: GetNotificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationCursorPage> {
        const response = await this.getNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markAllNotificationsRead without sending the request
     */
    async markAllNotificationsReadRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/notifications/read-all`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async markAllNotificationsReadRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.markAllNotificationsReadRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async markAllNotificationsRead(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.markAllNotificationsReadRaw(initOverrides);
    }

    /**
     * Creates request options for markNotificationRead without sending the request
     */
    async markNotificationReadRequestOpts(requestParameters: MarkNotificationReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling markNotificationRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/notifications/{notificationId}/read`;
        urlPath = urlPath.replace('{notificationId}', encodeURIComponent(String(requestParameters['notificationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async markNotificationReadRaw(requestParameters: MarkNotificationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.markNotificationReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async markNotificationRead(requestParameters: MarkNotificationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.markNotificationReadRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for registerCommunicationEndpoint without sending the request
     */
    async registerCommunicationEndpointRequestOpts(requestParameters: RegisterCommunicationEndpointOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerCommunicationEndpointRequest'] == null) {
            throw new runtime.RequiredError(
                'registerCommunicationEndpointRequest',
                'Required parameter "registerCommunicationEndpointRequest" was null or undefined when calling registerCommunicationEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/communication-endpoints`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterCommunicationEndpointRequestToJSON(requestParameters['registerCommunicationEndpointRequest']),
        };
    }

    /**
     */
    async registerCommunicationEndpointRaw(requestParameters: RegisterCommunicationEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunicationEndpoint>> {
        const requestOptions = await this.registerCommunicationEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunicationEndpointFromJSON(jsonValue));
    }

    /**
     */
    async registerCommunicationEndpoint(requestParameters: RegisterCommunicationEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunicationEndpoint> {
        const response = await this.registerCommunicationEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unlinkIdentity without sending the request
     */
    async unlinkIdentityRequestOpts(requestParameters: UnlinkIdentityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['identityId'] == null) {
            throw new runtime.RequiredError(
                'identityId',
                'Required parameter "identityId" was null or undefined when calling unlinkIdentity().'
            );
        }

        if (requestParameters['sensitiveProof'] == null) {
            throw new runtime.RequiredError(
                'sensitiveProof',
                'Required parameter "sensitiveProof" was null or undefined when calling unlinkIdentity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/identities/{identityId}`;
        urlPath = urlPath.replace('{identityId}', encodeURIComponent(String(requestParameters['identityId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: SensitiveProofToJSON(requestParameters['sensitiveProof']),
        };
    }

    /**
     */
    async unlinkIdentityRaw(requestParameters: UnlinkIdentityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountIdentities>> {
        const requestOptions = await this.unlinkIdentityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountIdentitiesFromJSON(jsonValue));
    }

    /**
     */
    async unlinkIdentity(requestParameters: UnlinkIdentityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountIdentities> {
        const response = await this.unlinkIdentityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unregisterCommunicationEndpoint without sending the request
     */
    async unregisterCommunicationEndpointRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/communication-endpoints`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async unregisterCommunicationEndpointRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.unregisterCommunicationEndpointRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async unregisterCommunicationEndpoint(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unregisterCommunicationEndpointRaw(initOverrides);
    }

    /**
     * Creates request options for unregisterCommunicationEndpointById without sending the request
     */
    async unregisterCommunicationEndpointByIdRequestOpts(requestParameters: UnregisterCommunicationEndpointByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unregisterCommunicationEndpointById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/communication-endpoints/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async unregisterCommunicationEndpointByIdRaw(requestParameters: UnregisterCommunicationEndpointByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.unregisterCommunicationEndpointByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async unregisterCommunicationEndpointById(requestParameters: UnregisterCommunicationEndpointByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unregisterCommunicationEndpointByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateNotificationPreferences without sending the request
     */
    async updateNotificationPreferencesRequestOpts(requestParameters: UpdateNotificationPreferencesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationPreferences'] == null) {
            throw new runtime.RequiredError(
                'notificationPreferences',
                'Required parameter "notificationPreferences" was null or undefined when calling updateNotificationPreferences().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/notification-preferences`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationPreferencesToJSON(requestParameters['notificationPreferences']),
        };
    }

    /**
     */
    async updateNotificationPreferencesRaw(requestParameters: UpdateNotificationPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationPreferences>> {
        const requestOptions = await this.updateNotificationPreferencesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationPreferencesFromJSON(jsonValue));
    }

    /**
     */
    async updateNotificationPreferences(requestParameters: UpdateNotificationPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationPreferences> {
        const response = await this.updateNotificationPreferencesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyIdentityLink without sending the request
     */
    async verifyIdentityLinkRequestOpts(requestParameters: VerifyIdentityLinkOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling verifyIdentityLink().'
            );
        }

        if (requestParameters['verifyIdentityLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyIdentityLinkRequest',
                'Required parameter "verifyIdentityLinkRequest" was null or undefined when calling verifyIdentityLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/identity-links/{id}/verify`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyIdentityLinkRequestToJSON(requestParameters['verifyIdentityLinkRequest']),
        };
    }

    /**
     */
    async verifyIdentityLinkRaw(requestParameters: VerifyIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.verifyIdentityLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async verifyIdentityLink(requestParameters: VerifyIdentityLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.verifyIdentityLinkRaw(requestParameters, initOverrides);
    }

}
