/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateNativeChallengeRequest,
    CreateNativeChallengeRequestFromJSON,
    CreateNativeChallengeRequestToJSON,
} from '../models/CreateNativeChallengeRequest';
import {
    type CsrfToken,
    CsrfTokenFromJSON,
    CsrfTokenToJSON,
} from '../models/CsrfToken';
import {
    type CurrentAuthentication,
    CurrentAuthenticationFromJSON,
    CurrentAuthenticationToJSON,
} from '../models/CurrentAuthentication';
import {
    type ExchangeTelegramLoginAttemptRequest,
    ExchangeTelegramLoginAttemptRequestFromJSON,
    ExchangeTelegramLoginAttemptRequestToJSON,
} from '../models/ExchangeTelegramLoginAttemptRequest';
import {
    type NativeChallenge,
    NativeChallengeFromJSON,
    NativeChallengeToJSON,
} from '../models/NativeChallenge';
import {
    type NativeProviderLoginRequest,
    NativeProviderLoginRequestFromJSON,
    NativeProviderLoginRequestToJSON,
} from '../models/NativeProviderLoginRequest';
import {
    type RefreshSessionRequest,
    RefreshSessionRequestFromJSON,
    RefreshSessionRequestToJSON,
} from '../models/RefreshSessionRequest';
import {
    type SessionTokens,
    SessionTokensFromJSON,
    SessionTokensToJSON,
} from '../models/SessionTokens';
import {
    type TelegramLoginAttempt,
    TelegramLoginAttemptFromJSON,
    TelegramLoginAttemptToJSON,
} from '../models/TelegramLoginAttempt';

export interface CreateNativeChallengeOperationRequest {
    /**
     * 
     */
    createNativeChallengeRequest: CreateNativeChallengeRequest;
}

export interface ExchangeTelegramLoginAttemptOperationRequest {
    /**
     * 
     */
    attemptId: string;
    /**
     * 
     */
    exchangeTelegramLoginAttemptRequest: ExchangeTelegramLoginAttemptRequest;
}

export interface LoginWithAppleRequest {
    /**
     * 
     */
    nativeProviderLoginRequest: NativeProviderLoginRequest;
}

export interface LoginWithGoogleRequest {
    /**
     * 
     */
    nativeProviderLoginRequest: NativeProviderLoginRequest;
}

export interface RefreshSessionOperationRequest {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    refreshSessionRequest: RefreshSessionRequest;
}

/**
 * AuthenticationApi - interface
 * 
 * @export
 * @interface AuthenticationApiInterface
 */
export interface AuthenticationApiInterface {
    /**
     * Creates request options for createNativeChallenge without sending the request
     * @param {CreateNativeChallengeRequest} createNativeChallengeRequest 
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    createNativeChallengeRequestOpts(requestParameters: CreateNativeChallengeOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateNativeChallengeRequest} createNativeChallengeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    createNativeChallengeRaw(requestParameters: CreateNativeChallengeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NativeChallenge>>;

    /**
     */
    createNativeChallenge(requestParameters: CreateNativeChallengeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NativeChallenge>;

    /**
     * Creates request options for createTelegramLoginAttempt without sending the request
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    createTelegramLoginAttemptRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    createTelegramLoginAttemptRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelegramLoginAttempt>>;

    /**
     */
    createTelegramLoginAttempt(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelegramLoginAttempt>;

    /**
     * Creates request options for createTmaSession without sending the request
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    createTmaSessionRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    createTmaSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    createTmaSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for exchangeTelegramLoginAttempt without sending the request
     * @param {string} attemptId 
     * @param {ExchangeTelegramLoginAttemptRequest} exchangeTelegramLoginAttemptRequest 
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    exchangeTelegramLoginAttemptRequestOpts(requestParameters: ExchangeTelegramLoginAttemptOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} attemptId 
     * @param {ExchangeTelegramLoginAttemptRequest} exchangeTelegramLoginAttemptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    exchangeTelegramLoginAttemptRaw(requestParameters: ExchangeTelegramLoginAttemptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>>;

    /**
     */
    exchangeTelegramLoginAttempt(requestParameters: ExchangeTelegramLoginAttemptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens>;

    /**
     * Creates request options for getCsrfToken without sending the request
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    getCsrfTokenRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    getCsrfTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CsrfToken>>;

    /**
     */
    getCsrfToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CsrfToken>;

    /**
     * Creates request options for getCurrentAuthentication without sending the request
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    getCurrentAuthenticationRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    getCurrentAuthenticationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentAuthentication>>;

    /**
     */
    getCurrentAuthentication(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentAuthentication>;

    /**
     * Creates request options for loginWithApple without sending the request
     * @param {NativeProviderLoginRequest} nativeProviderLoginRequest 
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    loginWithAppleRequestOpts(requestParameters: LoginWithAppleRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {NativeProviderLoginRequest} nativeProviderLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    loginWithAppleRaw(requestParameters: LoginWithAppleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>>;

    /**
     */
    loginWithApple(requestParameters: LoginWithAppleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens>;

    /**
     * Creates request options for loginWithGoogle without sending the request
     * @param {NativeProviderLoginRequest} nativeProviderLoginRequest 
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    loginWithGoogleRequestOpts(requestParameters: LoginWithGoogleRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {NativeProviderLoginRequest} nativeProviderLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    loginWithGoogleRaw(requestParameters: LoginWithGoogleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>>;

    /**
     */
    loginWithGoogle(requestParameters: LoginWithGoogleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens>;

    /**
     * Creates request options for logoutCurrentSession without sending the request
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    logoutCurrentSessionRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    logoutCurrentSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    logoutCurrentSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for refreshSession without sending the request
     * @param {string} idempotencyKey 
     * @param {RefreshSessionRequest} refreshSessionRequest 
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    refreshSessionRequestOpts(requestParameters: RefreshSessionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {RefreshSessionRequest} refreshSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    refreshSessionRaw(requestParameters: RefreshSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>>;

    /**
     */
    refreshSession(requestParameters: RefreshSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens>;

    /**
     * Creates request options for revokeAllSessions without sending the request
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    revokeAllSessionsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    revokeAllSessionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    revokeAllSessions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI implements AuthenticationApiInterface {

    /**
     * Creates request options for createNativeChallenge without sending the request
     */
    async createNativeChallengeRequestOpts(requestParameters: CreateNativeChallengeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createNativeChallengeRequest'] == null) {
            throw new runtime.RequiredError(
                'createNativeChallengeRequest',
                'Required parameter "createNativeChallengeRequest" was null or undefined when calling createNativeChallenge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/native/challenges`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNativeChallengeRequestToJSON(requestParameters['createNativeChallengeRequest']),
        };
    }

    /**
     */
    async createNativeChallengeRaw(requestParameters: CreateNativeChallengeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NativeChallenge>> {
        const requestOptions = await this.createNativeChallengeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NativeChallengeFromJSON(jsonValue));
    }

    /**
     */
    async createNativeChallenge(requestParameters: CreateNativeChallengeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NativeChallenge> {
        const response = await this.createNativeChallengeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTelegramLoginAttempt without sending the request
     */
    async createTelegramLoginAttemptRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/native/telegram/attempts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createTelegramLoginAttemptRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelegramLoginAttempt>> {
        const requestOptions = await this.createTelegramLoginAttemptRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TelegramLoginAttemptFromJSON(jsonValue));
    }

    /**
     */
    async createTelegramLoginAttempt(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelegramLoginAttempt> {
        const response = await this.createTelegramLoginAttemptRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTmaSession without sending the request
     */
    async createTmaSessionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tmaBootstrap authentication
        }


        let urlPath = `/api/v1/auth/tma/session`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createTmaSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createTmaSessionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createTmaSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createTmaSessionRaw(initOverrides);
    }

    /**
     * Creates request options for exchangeTelegramLoginAttempt without sending the request
     */
    async exchangeTelegramLoginAttemptRequestOpts(requestParameters: ExchangeTelegramLoginAttemptOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['attemptId'] == null) {
            throw new runtime.RequiredError(
                'attemptId',
                'Required parameter "attemptId" was null or undefined when calling exchangeTelegramLoginAttempt().'
            );
        }

        if (requestParameters['exchangeTelegramLoginAttemptRequest'] == null) {
            throw new runtime.RequiredError(
                'exchangeTelegramLoginAttemptRequest',
                'Required parameter "exchangeTelegramLoginAttemptRequest" was null or undefined when calling exchangeTelegramLoginAttempt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/native/telegram/attempts/{attemptId}/exchange`;
        urlPath = urlPath.replace('{attemptId}', encodeURIComponent(String(requestParameters['attemptId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExchangeTelegramLoginAttemptRequestToJSON(requestParameters['exchangeTelegramLoginAttemptRequest']),
        };
    }

    /**
     */
    async exchangeTelegramLoginAttemptRaw(requestParameters: ExchangeTelegramLoginAttemptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>> {
        const requestOptions = await this.exchangeTelegramLoginAttemptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionTokensFromJSON(jsonValue));
    }

    /**
     */
    async exchangeTelegramLoginAttempt(requestParameters: ExchangeTelegramLoginAttemptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens> {
        const response = await this.exchangeTelegramLoginAttemptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCsrfToken without sending the request
     */
    async getCsrfTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/csrf`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCsrfTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CsrfToken>> {
        const requestOptions = await this.getCsrfTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CsrfTokenFromJSON(jsonValue));
    }

    /**
     */
    async getCsrfToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CsrfToken> {
        const response = await this.getCsrfTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCurrentAuthentication without sending the request
     */
    async getCurrentAuthenticationRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCurrentAuthenticationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentAuthentication>> {
        const requestOptions = await this.getCurrentAuthenticationRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentAuthenticationFromJSON(jsonValue));
    }

    /**
     */
    async getCurrentAuthentication(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentAuthentication> {
        const response = await this.getCurrentAuthenticationRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginWithApple without sending the request
     */
    async loginWithAppleRequestOpts(requestParameters: LoginWithAppleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nativeProviderLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'nativeProviderLoginRequest',
                'Required parameter "nativeProviderLoginRequest" was null or undefined when calling loginWithApple().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/native/apple`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NativeProviderLoginRequestToJSON(requestParameters['nativeProviderLoginRequest']),
        };
    }

    /**
     */
    async loginWithAppleRaw(requestParameters: LoginWithAppleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>> {
        const requestOptions = await this.loginWithAppleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionTokensFromJSON(jsonValue));
    }

    /**
     */
    async loginWithApple(requestParameters: LoginWithAppleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens> {
        const response = await this.loginWithAppleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginWithGoogle without sending the request
     */
    async loginWithGoogleRequestOpts(requestParameters: LoginWithGoogleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nativeProviderLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'nativeProviderLoginRequest',
                'Required parameter "nativeProviderLoginRequest" was null or undefined when calling loginWithGoogle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/native/google`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NativeProviderLoginRequestToJSON(requestParameters['nativeProviderLoginRequest']),
        };
    }

    /**
     */
    async loginWithGoogleRaw(requestParameters: LoginWithGoogleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>> {
        const requestOptions = await this.loginWithGoogleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionTokensFromJSON(jsonValue));
    }

    /**
     */
    async loginWithGoogle(requestParameters: LoginWithGoogleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens> {
        const response = await this.loginWithGoogleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logoutCurrentSession without sending the request
     */
    async logoutCurrentSessionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/sessions/current`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async logoutCurrentSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.logoutCurrentSessionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async logoutCurrentSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutCurrentSessionRaw(initOverrides);
    }

    /**
     * Creates request options for refreshSession without sending the request
     */
    async refreshSessionRequestOpts(requestParameters: RefreshSessionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling refreshSession().'
            );
        }

        if (requestParameters['refreshSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshSessionRequest',
                'Required parameter "refreshSessionRequest" was null or undefined when calling refreshSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/auth/sessions/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshSessionRequestToJSON(requestParameters['refreshSessionRequest']),
        };
    }

    /**
     */
    async refreshSessionRaw(requestParameters: RefreshSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionTokens>> {
        const requestOptions = await this.refreshSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionTokensFromJSON(jsonValue));
    }

    /**
     */
    async refreshSession(requestParameters: RefreshSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionTokens> {
        const response = await this.refreshSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeAllSessions without sending the request
     */
    async revokeAllSessionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/sessions`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async revokeAllSessionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeAllSessionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async revokeAllSessions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeAllSessionsRaw(initOverrides);
    }

}
