/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CleaningConfiguration,
    CleaningConfigurationFromJSON,
    CleaningConfigurationToJSON,
} from '../models/CleaningConfiguration';
import {
    type CleaningOrder,
    CleaningOrderFromJSON,
    CleaningOrderToJSON,
} from '../models/CleaningOrder';
import {
    type CleaningOrderCursorPage,
    CleaningOrderCursorPageFromJSON,
    CleaningOrderCursorPageToJSON,
} from '../models/CleaningOrderCursorPage';
import {
    type CleaningOrderQuote,
    CleaningOrderQuoteFromJSON,
    CleaningOrderQuoteToJSON,
} from '../models/CleaningOrderQuote';
import {
    type CleaningOrderQuoteRequest,
    CleaningOrderQuoteRequestFromJSON,
    CleaningOrderQuoteRequestToJSON,
} from '../models/CleaningOrderQuoteRequest';
import {
    type CleaningRepeatPrefill,
    CleaningRepeatPrefillFromJSON,
    CleaningRepeatPrefillToJSON,
} from '../models/CleaningRepeatPrefill';
import {
    type CleaningRepeatReminder,
    CleaningRepeatReminderFromJSON,
    CleaningRepeatReminderToJSON,
} from '../models/CleaningRepeatReminder';
import {
    type CleaningRepeatReminderRequest,
    CleaningRepeatReminderRequestFromJSON,
    CleaningRepeatReminderRequestToJSON,
} from '../models/CleaningRepeatReminderRequest';
import {
    type CleaningReport,
    CleaningReportFromJSON,
    CleaningReportToJSON,
} from '../models/CleaningReport';
import {
    type CreateCleaningOrderRequest,
    CreateCleaningOrderRequestFromJSON,
    CreateCleaningOrderRequestToJSON,
} from '../models/CreateCleaningOrderRequest';
import {
    type ReferralSummary,
    ReferralSummaryFromJSON,
    ReferralSummaryToJSON,
} from '../models/ReferralSummary';

export interface CancelCleaningOrderRequest {
    /**
     * 
     */
    orderId: number;
}

export interface CreateCleaningOrderOperationRequest {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    createCleaningOrderRequest: CreateCleaningOrderRequest;
}

export interface GetCleaningOrderRequest {
    /**
     * 
     */
    orderId: number;
}

export interface GetCleaningOrdersRequest {
    /**
     * 
     */
    cursor?: string;
    /**
     * 
     */
    size?: number;
}

export interface GetCleaningRepeatPrefillRequest {
    /**
     * 
     */
    orderId: number;
}

export interface GetCleaningRepeatReminderRequest {
    /**
     * 
     */
    orderId: number;
}

export interface GetCleaningReportRequest {
    /**
     * 
     */
    orderId: number;
}

export interface GetCleaningReportPhotoRequest {
    /**
     * 
     */
    orderId: number;
    /**
     * 
     */
    mediaId: number;
}

export interface QuoteCleaningOrderRequest {
    /**
     * 
     */
    cleaningOrderQuoteRequest: CleaningOrderQuoteRequest;
}

export interface RecordCleaningRepeatShownRequest {
    /**
     * 
     */
    orderId: number;
}

export interface UpdateCleaningRepeatReminderRequest {
    /**
     * 
     */
    orderId: number;
    /**
     * 
     */
    cleaningRepeatReminderRequest: CleaningRepeatReminderRequest;
}

/**
 * CleaningApi - interface
 * 
 * @export
 * @interface CleaningApiInterface
 */
export interface CleaningApiInterface {
    /**
     * Creates request options for cancelCleaningOrder without sending the request
     * @param {number} orderId 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    cancelCleaningOrderRequestOpts(requestParameters: CancelCleaningOrderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    cancelCleaningOrderRaw(requestParameters: CancelCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrder>>;

    /**
     */
    cancelCleaningOrder(requestParameters: CancelCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrder>;

    /**
     * Creates request options for createCleaningOrder without sending the request
     * @param {string} idempotencyKey 
     * @param {CreateCleaningOrderRequest} createCleaningOrderRequest 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    createCleaningOrderRequestOpts(requestParameters: CreateCleaningOrderOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {CreateCleaningOrderRequest} createCleaningOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    createCleaningOrderRaw(requestParameters: CreateCleaningOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrder>>;

    /**
     */
    createCleaningOrder(requestParameters: CreateCleaningOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrder>;

    /**
     * Creates request options for getCleaningConfiguration without sending the request
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningConfigurationRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningConfiguration>>;

    /**
     */
    getCleaningConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningConfiguration>;

    /**
     * Creates request options for getCleaningOrder without sending the request
     * @param {number} orderId 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningOrderRequestOpts(requestParameters: GetCleaningOrderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningOrderRaw(requestParameters: GetCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrder>>;

    /**
     */
    getCleaningOrder(requestParameters: GetCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrder>;

    /**
     * Creates request options for getCleaningOrders without sending the request
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningOrdersRequestOpts(requestParameters: GetCleaningOrdersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningOrdersRaw(requestParameters: GetCleaningOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrderCursorPage>>;

    /**
     */
    getCleaningOrders(requestParameters: GetCleaningOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrderCursorPage>;

    /**
     * Creates request options for getCleaningReferralSummary without sending the request
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningReferralSummaryRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningReferralSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReferralSummary>>;

    /**
     */
    getCleaningReferralSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReferralSummary>;

    /**
     * Creates request options for getCleaningRepeatPrefill without sending the request
     * @param {number} orderId 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningRepeatPrefillRequestOpts(requestParameters: GetCleaningRepeatPrefillRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningRepeatPrefillRaw(requestParameters: GetCleaningRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningRepeatPrefill>>;

    /**
     */
    getCleaningRepeatPrefill(requestParameters: GetCleaningRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningRepeatPrefill>;

    /**
     * Creates request options for getCleaningRepeatReminder without sending the request
     * @param {number} orderId 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningRepeatReminderRequestOpts(requestParameters: GetCleaningRepeatReminderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningRepeatReminderRaw(requestParameters: GetCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningRepeatReminder>>;

    /**
     */
    getCleaningRepeatReminder(requestParameters: GetCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningRepeatReminder>;

    /**
     * Creates request options for getCleaningReport without sending the request
     * @param {number} orderId 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningReportRequestOpts(requestParameters: GetCleaningReportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningReportRaw(requestParameters: GetCleaningReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningReport>>;

    /**
     */
    getCleaningReport(requestParameters: GetCleaningReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningReport>;

    /**
     * Creates request options for getCleaningReportPhoto without sending the request
     * @param {number} orderId 
     * @param {number} mediaId 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningReportPhotoRequestOpts(requestParameters: GetCleaningReportPhotoRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {number} mediaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    getCleaningReportPhotoRaw(requestParameters: GetCleaningReportPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     */
    getCleaningReportPhoto(requestParameters: GetCleaningReportPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for quoteCleaningOrder without sending the request
     * @param {CleaningOrderQuoteRequest} cleaningOrderQuoteRequest 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    quoteCleaningOrderRequestOpts(requestParameters: QuoteCleaningOrderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CleaningOrderQuoteRequest} cleaningOrderQuoteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    quoteCleaningOrderRaw(requestParameters: QuoteCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrderQuote>>;

    /**
     */
    quoteCleaningOrder(requestParameters: QuoteCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrderQuote>;

    /**
     * Creates request options for recordCleaningRepeatShown without sending the request
     * @param {number} orderId 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    recordCleaningRepeatShownRequestOpts(requestParameters: RecordCleaningRepeatShownRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    recordCleaningRepeatShownRaw(requestParameters: RecordCleaningRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    recordCleaningRepeatShown(requestParameters: RecordCleaningRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateCleaningRepeatReminder without sending the request
     * @param {number} orderId 
     * @param {CleaningRepeatReminderRequest} cleaningRepeatReminderRequest 
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    updateCleaningRepeatReminderRequestOpts(requestParameters: UpdateCleaningRepeatReminderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} orderId 
     * @param {CleaningRepeatReminderRequest} cleaningRepeatReminderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CleaningApiInterface
     */
    updateCleaningRepeatReminderRaw(requestParameters: UpdateCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningRepeatReminder>>;

    /**
     */
    updateCleaningRepeatReminder(requestParameters: UpdateCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningRepeatReminder>;

}

/**
 * 
 */
export class CleaningApi extends runtime.BaseAPI implements CleaningApiInterface {

    /**
     * Creates request options for cancelCleaningOrder without sending the request
     */
    async cancelCleaningOrderRequestOpts(requestParameters: CancelCleaningOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling cancelCleaningOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}/cancel`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async cancelCleaningOrderRaw(requestParameters: CancelCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrder>> {
        const requestOptions = await this.cancelCleaningOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningOrderFromJSON(jsonValue));
    }

    /**
     */
    async cancelCleaningOrder(requestParameters: CancelCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrder> {
        const response = await this.cancelCleaningOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCleaningOrder without sending the request
     */
    async createCleaningOrderRequestOpts(requestParameters: CreateCleaningOrderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createCleaningOrder().'
            );
        }

        if (requestParameters['createCleaningOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createCleaningOrderRequest',
                'Required parameter "createCleaningOrderRequest" was null or undefined when calling createCleaningOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCleaningOrderRequestToJSON(requestParameters['createCleaningOrderRequest']),
        };
    }

    /**
     */
    async createCleaningOrderRaw(requestParameters: CreateCleaningOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrder>> {
        const requestOptions = await this.createCleaningOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningOrderFromJSON(jsonValue));
    }

    /**
     */
    async createCleaningOrder(requestParameters: CreateCleaningOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrder> {
        const response = await this.createCleaningOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningConfiguration without sending the request
     */
    async getCleaningConfigurationRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/cleaning/configuration`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningConfiguration>> {
        const requestOptions = await this.getCleaningConfigurationRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningConfigurationFromJSON(jsonValue));
    }

    /**
     */
    async getCleaningConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningConfiguration> {
        const response = await this.getCleaningConfigurationRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningOrder without sending the request
     */
    async getCleaningOrderRequestOpts(requestParameters: GetCleaningOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getCleaningOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningOrderRaw(requestParameters: GetCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrder>> {
        const requestOptions = await this.getCleaningOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningOrderFromJSON(jsonValue));
    }

    /**
     */
    async getCleaningOrder(requestParameters: GetCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrder> {
        const response = await this.getCleaningOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningOrders without sending the request
     */
    async getCleaningOrdersRequestOpts(requestParameters: GetCleaningOrdersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningOrdersRaw(requestParameters: GetCleaningOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrderCursorPage>> {
        const requestOptions = await this.getCleaningOrdersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningOrderCursorPageFromJSON(jsonValue));
    }

    /**
     */
    async getCleaningOrders(requestParameters: GetCleaningOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrderCursorPage> {
        const response = await this.getCleaningOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningReferralSummary without sending the request
     */
    async getCleaningReferralSummaryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/referrals/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningReferralSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReferralSummary>> {
        const requestOptions = await this.getCleaningReferralSummaryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReferralSummaryFromJSON(jsonValue));
    }

    /**
     */
    async getCleaningReferralSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReferralSummary> {
        const response = await this.getCleaningReferralSummaryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningRepeatPrefill without sending the request
     */
    async getCleaningRepeatPrefillRequestOpts(requestParameters: GetCleaningRepeatPrefillRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getCleaningRepeatPrefill().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}/repeat-prefill`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningRepeatPrefillRaw(requestParameters: GetCleaningRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningRepeatPrefill>> {
        const requestOptions = await this.getCleaningRepeatPrefillRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningRepeatPrefillFromJSON(jsonValue));
    }

    /**
     */
    async getCleaningRepeatPrefill(requestParameters: GetCleaningRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningRepeatPrefill> {
        const response = await this.getCleaningRepeatPrefillRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningRepeatReminder without sending the request
     */
    async getCleaningRepeatReminderRequestOpts(requestParameters: GetCleaningRepeatReminderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getCleaningRepeatReminder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}/repeat-reminder`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningRepeatReminderRaw(requestParameters: GetCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningRepeatReminder>> {
        const requestOptions = await this.getCleaningRepeatReminderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningRepeatReminderFromJSON(jsonValue));
    }

    /**
     */
    async getCleaningRepeatReminder(requestParameters: GetCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningRepeatReminder> {
        const response = await this.getCleaningRepeatReminderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningReport without sending the request
     */
    async getCleaningReportRequestOpts(requestParameters: GetCleaningReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getCleaningReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}/report`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningReportRaw(requestParameters: GetCleaningReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningReport>> {
        const requestOptions = await this.getCleaningReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningReportFromJSON(jsonValue));
    }

    /**
     */
    async getCleaningReport(requestParameters: GetCleaningReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningReport> {
        const response = await this.getCleaningReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleaningReportPhoto without sending the request
     */
    async getCleaningReportPhotoRequestOpts(requestParameters: GetCleaningReportPhotoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getCleaningReportPhoto().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling getCleaningReportPhoto().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}/report/photos/{mediaId}`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCleaningReportPhotoRaw(requestParameters: GetCleaningReportPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getCleaningReportPhotoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async getCleaningReportPhoto(requestParameters: GetCleaningReportPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getCleaningReportPhotoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for quoteCleaningOrder without sending the request
     */
    async quoteCleaningOrderRequestOpts(requestParameters: QuoteCleaningOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cleaningOrderQuoteRequest'] == null) {
            throw new runtime.RequiredError(
                'cleaningOrderQuoteRequest',
                'Required parameter "cleaningOrderQuoteRequest" was null or undefined when calling quoteCleaningOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/quote`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CleaningOrderQuoteRequestToJSON(requestParameters['cleaningOrderQuoteRequest']),
        };
    }

    /**
     */
    async quoteCleaningOrderRaw(requestParameters: QuoteCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningOrderQuote>> {
        const requestOptions = await this.quoteCleaningOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningOrderQuoteFromJSON(jsonValue));
    }

    /**
     */
    async quoteCleaningOrder(requestParameters: QuoteCleaningOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningOrderQuote> {
        const response = await this.quoteCleaningOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recordCleaningRepeatShown without sending the request
     */
    async recordCleaningRepeatShownRequestOpts(requestParameters: RecordCleaningRepeatShownRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling recordCleaningRepeatShown().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}/repeat-shown`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async recordCleaningRepeatShownRaw(requestParameters: RecordCleaningRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.recordCleaningRepeatShownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async recordCleaningRepeatShown(requestParameters: RecordCleaningRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordCleaningRepeatShownRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateCleaningRepeatReminder without sending the request
     */
    async updateCleaningRepeatReminderRequestOpts(requestParameters: UpdateCleaningRepeatReminderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling updateCleaningRepeatReminder().'
            );
        }

        if (requestParameters['cleaningRepeatReminderRequest'] == null) {
            throw new runtime.RequiredError(
                'cleaningRepeatReminderRequest',
                'Required parameter "cleaningRepeatReminderRequest" was null or undefined when calling updateCleaningRepeatReminder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/cleaning/orders/{orderId}/repeat-reminder`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CleaningRepeatReminderRequestToJSON(requestParameters['cleaningRepeatReminderRequest']),
        };
    }

    /**
     */
    async updateCleaningRepeatReminderRaw(requestParameters: UpdateCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CleaningRepeatReminder>> {
        const requestOptions = await this.updateCleaningRepeatReminderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CleaningRepeatReminderFromJSON(jsonValue));
    }

    /**
     */
    async updateCleaningRepeatReminder(requestParameters: UpdateCleaningRepeatReminderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CleaningRepeatReminder> {
        const response = await this.updateCleaningRepeatReminderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
