/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PlatformServiceState,
    PlatformServiceStateFromJSON,
    PlatformServiceStateToJSON,
} from '../models/PlatformServiceState';

/**
 * PlatformApi - interface
 * 
 * @export
 * @interface PlatformApiInterface
 */
export interface PlatformApiInterface {
    /**
     * Creates request options for getPlatformServices without sending the request
     * @throws {RequiredError}
     * @memberof PlatformApiInterface
     */
    getPlatformServicesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlatformApiInterface
     */
    getPlatformServicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlatformServiceState>>>;

    /**
     */
    getPlatformServices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlatformServiceState>>;

}

/**
 * 
 */
export class PlatformApi extends runtime.BaseAPI implements PlatformApiInterface {

    /**
     * Creates request options for getPlatformServices without sending the request
     */
    async getPlatformServicesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/catalog/services`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPlatformServicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlatformServiceState>>> {
        const requestOptions = await this.getPlatformServicesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlatformServiceStateFromJSON));
    }

    /**
     */
    async getPlatformServices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlatformServiceState>> {
        const response = await this.getPlatformServicesRaw(initOverrides);
        return await response.value();
    }

}
