/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateRentalBookingRequest,
    CreateRentalBookingRequestFromJSON,
    CreateRentalBookingRequestToJSON,
} from '../models/CreateRentalBookingRequest';
import {
    type RentalAvailability,
    RentalAvailabilityFromJSON,
    RentalAvailabilityToJSON,
} from '../models/RentalAvailability';
import {
    type RentalBooking,
    RentalBookingFromJSON,
    RentalBookingToJSON,
} from '../models/RentalBooking';
import {
    type RentalBookingCursorPage,
    RentalBookingCursorPageFromJSON,
    RentalBookingCursorPageToJSON,
} from '../models/RentalBookingCursorPage';
import {
    type RentalCleaningContext,
    RentalCleaningContextFromJSON,
    RentalCleaningContextToJSON,
} from '../models/RentalCleaningContext';
import {
    type RentalConfiguration,
    RentalConfigurationFromJSON,
    RentalConfigurationToJSON,
} from '../models/RentalConfiguration';
import {
    type RentalFirstCardRequest,
    RentalFirstCardRequestFromJSON,
    RentalFirstCardRequestToJSON,
} from '../models/RentalFirstCardRequest';
import {
    type RentalProperty,
    RentalPropertyFromJSON,
    RentalPropertyToJSON,
} from '../models/RentalProperty';
import {
    type RentalQuote,
    RentalQuoteFromJSON,
    RentalQuoteToJSON,
} from '../models/RentalQuote';
import {
    type RentalSearch,
    RentalSearchFromJSON,
    RentalSearchToJSON,
} from '../models/RentalSearch';
import {
    type RentalTermType,
    RentalTermTypeFromJSON,
    RentalTermTypeToJSON,
} from '../models/RentalTermType';
import {
    type RentalTransferContext,
    RentalTransferContextFromJSON,
    RentalTransferContextToJSON,
} from '../models/RentalTransferContext';
import {
    type RentalTransferPrefill,
    RentalTransferPrefillFromJSON,
    RentalTransferPrefillToJSON,
} from '../models/RentalTransferPrefill';

export interface CancelRentalBookingRequest {
    /**
     * 
     */
    bookingId: number;
}

export interface CreateRentalBookingOperationRequest {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    createRentalBookingRequest: CreateRentalBookingRequest;
}

export interface GetRentalAvailabilityRequest {
    /**
     * 
     */
    propertyId: number;
    /**
     * 
     */
    fromDate: Date;
    /**
     * 
     */
    toDate: Date;
}

export interface GetRentalBookingRequest {
    /**
     * 
     */
    bookingId: number;
}

export interface GetRentalBookingsRequest {
    /**
     * 
     */
    cursor?: string;
    /**
     * 
     */
    size?: number;
}

export interface GetRentalCleaningContextRequest {
    /**
     * 
     */
    bookingId: number;
}

export interface GetRentalPropertyRequest {
    /**
     * 
     */
    slug: string;
}

export interface GetRentalPropertyMediaRequest {
    /**
     * 
     */
    propertyId: number;
    /**
     * 
     */
    mediaId: number;
    /**
     * 
     */
    v?: number;
}

export interface GetRentalPropertyMediaVariantRequest {
    /**
     * 
     */
    propertyId: number;
    /**
     * 
     */
    mediaId: number;
    /**
     * 
     */
    variant: GetRentalPropertyMediaVariantVariantEnum;
    /**
     * 
     */
    v?: number;
}

export interface GetRentalTransferContextRequest {
    /**
     * 
     */
    bookingId: number;
}

export interface GetRentalTransferPrefillRequest {
    /**
     * 
     */
    bookingId: number;
    /**
     * 
     */
    context: GetRentalTransferPrefillContextEnum;
}

export interface QuoteRentalPropertyRequest {
    /**
     * 
     */
    propertyId: number;
    /**
     * 
     */
    termType: RentalTermType;
    /**
     * 
     */
    checkInDate: Date;
    /**
     * 
     */
    guests: number;
    /**
     * 
     */
    checkOutDate?: Date;
    /**
     * 
     */
    months?: number;
}

export interface RecordRentalFirstCardRequest {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    rentalFirstCardRequest: RentalFirstCardRequest;
}

export interface RecordRentalSearchOpenedRequest {
    /**
     * 
     */
    executionId: string;
}

export interface RecordRentalTransferContextShownRequest {
    /**
     * 
     */
    bookingId: number;
    /**
     * 
     */
    context: RecordRentalTransferContextShownContextEnum;
}

export interface SearchRentalPropertiesRequest {
    /**
     * 
     */
    termType?: RentalTermType;
    /**
     * 
     */
    checkInDate?: Date;
    /**
     * 
     */
    checkOutDate?: Date;
    /**
     * 
     */
    months?: number;
    /**
     * 
     */
    guests?: number;
    /**
     * 
     */
    cursor?: string;
    /**
     * 
     */
    size?: number;
    /**
     * 
     */
    xRentalPreviousSearchId?: string;
}

/**
 * RentalApi - interface
 * 
 * @export
 * @interface RentalApiInterface
 */
export interface RentalApiInterface {
    /**
     * Creates request options for cancelRentalBooking without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    cancelRentalBookingRequestOpts(requestParameters: CancelRentalBookingRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    cancelRentalBookingRaw(requestParameters: CancelRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBooking>>;

    /**
     */
    cancelRentalBooking(requestParameters: CancelRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBooking>;

    /**
     * Creates request options for createRentalBooking without sending the request
     * @param {string} idempotencyKey 
     * @param {CreateRentalBookingRequest} createRentalBookingRequest 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    createRentalBookingRequestOpts(requestParameters: CreateRentalBookingOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {CreateRentalBookingRequest} createRentalBookingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    createRentalBookingRaw(requestParameters: CreateRentalBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBooking>>;

    /**
     */
    createRentalBooking(requestParameters: CreateRentalBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBooking>;

    /**
     * Creates request options for getRentalAvailability without sending the request
     * @param {number} propertyId 
     * @param {Date} fromDate 
     * @param {Date} toDate 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalAvailabilityRequestOpts(requestParameters: GetRentalAvailabilityRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} propertyId 
     * @param {Date} fromDate 
     * @param {Date} toDate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalAvailabilityRaw(requestParameters: GetRentalAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalAvailability>>;

    /**
     */
    getRentalAvailability(requestParameters: GetRentalAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalAvailability>;

    /**
     * Creates request options for getRentalBooking without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalBookingRequestOpts(requestParameters: GetRentalBookingRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalBookingRaw(requestParameters: GetRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBooking>>;

    /**
     */
    getRentalBooking(requestParameters: GetRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBooking>;

    /**
     * Creates request options for getRentalBookings without sending the request
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalBookingsRequestOpts(requestParameters: GetRentalBookingsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalBookingsRaw(requestParameters: GetRentalBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBookingCursorPage>>;

    /**
     */
    getRentalBookings(requestParameters: GetRentalBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBookingCursorPage>;

    /**
     * Creates request options for getRentalCleaningContext without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalCleaningContextRequestOpts(requestParameters: GetRentalCleaningContextRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalCleaningContextRaw(requestParameters: GetRentalCleaningContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalCleaningContext>>;

    /**
     */
    getRentalCleaningContext(requestParameters: GetRentalCleaningContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalCleaningContext>;

    /**
     * Creates request options for getRentalConfiguration without sending the request
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalConfigurationRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalConfiguration>>;

    /**
     */
    getRentalConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalConfiguration>;

    /**
     * Creates request options for getRentalProperty without sending the request
     * @param {string} slug 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalPropertyRequestOpts(requestParameters: GetRentalPropertyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalPropertyRaw(requestParameters: GetRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalProperty>>;

    /**
     */
    getRentalProperty(requestParameters: GetRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalProperty>;

    /**
     * Creates request options for getRentalPropertyMedia without sending the request
     * @param {number} propertyId 
     * @param {number} mediaId 
     * @param {number} [v] 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalPropertyMediaRequestOpts(requestParameters: GetRentalPropertyMediaRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} propertyId 
     * @param {number} mediaId 
     * @param {number} [v] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalPropertyMediaRaw(requestParameters: GetRentalPropertyMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     */
    getRentalPropertyMedia(requestParameters: GetRentalPropertyMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for getRentalPropertyMediaVariant without sending the request
     * @param {number} propertyId 
     * @param {number} mediaId 
     * @param {'card' | 'thumbnail'} variant 
     * @param {number} [v] 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalPropertyMediaVariantRequestOpts(requestParameters: GetRentalPropertyMediaVariantRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} propertyId 
     * @param {number} mediaId 
     * @param {'card' | 'thumbnail'} variant 
     * @param {number} [v] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalPropertyMediaVariantRaw(requestParameters: GetRentalPropertyMediaVariantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     */
    getRentalPropertyMediaVariant(requestParameters: GetRentalPropertyMediaVariantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for getRentalTransferContext without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalTransferContextRequestOpts(requestParameters: GetRentalTransferContextRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalTransferContextRaw(requestParameters: GetRentalTransferContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalTransferContext>>;

    /**
     */
    getRentalTransferContext(requestParameters: GetRentalTransferContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalTransferContext>;

    /**
     * Creates request options for getRentalTransferPrefill without sending the request
     * @param {number} bookingId 
     * @param {'ARRIVAL' | 'CHECKOUT'} context 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalTransferPrefillRequestOpts(requestParameters: GetRentalTransferPrefillRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {'ARRIVAL' | 'CHECKOUT'} context 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    getRentalTransferPrefillRaw(requestParameters: GetRentalTransferPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalTransferPrefill>>;

    /**
     */
    getRentalTransferPrefill(requestParameters: GetRentalTransferPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalTransferPrefill>;

    /**
     * Creates request options for quoteRentalProperty without sending the request
     * @param {number} propertyId 
     * @param {RentalTermType} termType 
     * @param {Date} checkInDate 
     * @param {number} guests 
     * @param {Date} [checkOutDate] 
     * @param {number} [months] 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    quoteRentalPropertyRequestOpts(requestParameters: QuoteRentalPropertyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} propertyId 
     * @param {RentalTermType} termType 
     * @param {Date} checkInDate 
     * @param {number} guests 
     * @param {Date} [checkOutDate] 
     * @param {number} [months] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    quoteRentalPropertyRaw(requestParameters: QuoteRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalQuote>>;

    /**
     */
    quoteRentalProperty(requestParameters: QuoteRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalQuote>;

    /**
     * Creates request options for recordRentalFirstCard without sending the request
     * @param {string} executionId 
     * @param {RentalFirstCardRequest} rentalFirstCardRequest 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    recordRentalFirstCardRequestOpts(requestParameters: RecordRentalFirstCardRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} executionId 
     * @param {RentalFirstCardRequest} rentalFirstCardRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    recordRentalFirstCardRaw(requestParameters: RecordRentalFirstCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    recordRentalFirstCard(requestParameters: RecordRentalFirstCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for recordRentalSearchOpened without sending the request
     * @param {string} executionId 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    recordRentalSearchOpenedRequestOpts(requestParameters: RecordRentalSearchOpenedRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} executionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    recordRentalSearchOpenedRaw(requestParameters: RecordRentalSearchOpenedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    recordRentalSearchOpened(requestParameters: RecordRentalSearchOpenedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for recordRentalTransferContextShown without sending the request
     * @param {number} bookingId 
     * @param {'ARRIVAL' | 'CHECKOUT'} context 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    recordRentalTransferContextShownRequestOpts(requestParameters: RecordRentalTransferContextShownRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {'ARRIVAL' | 'CHECKOUT'} context 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    recordRentalTransferContextShownRaw(requestParameters: RecordRentalTransferContextShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    recordRentalTransferContextShown(requestParameters: RecordRentalTransferContextShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for searchRentalProperties without sending the request
     * @param {RentalTermType} [termType] 
     * @param {Date} [checkInDate] 
     * @param {Date} [checkOutDate] 
     * @param {number} [months] 
     * @param {number} [guests] 
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @param {string} [xRentalPreviousSearchId] 
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    searchRentalPropertiesRequestOpts(requestParameters: SearchRentalPropertiesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {RentalTermType} [termType] 
     * @param {Date} [checkInDate] 
     * @param {Date} [checkOutDate] 
     * @param {number} [months] 
     * @param {number} [guests] 
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @param {string} [xRentalPreviousSearchId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalApiInterface
     */
    searchRentalPropertiesRaw(requestParameters: SearchRentalPropertiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalSearch>>;

    /**
     */
    searchRentalProperties(requestParameters: SearchRentalPropertiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalSearch>;

}

/**
 * 
 */
export class RentalApi extends runtime.BaseAPI implements RentalApiInterface {

    /**
     * Creates request options for cancelRentalBooking without sending the request
     */
    async cancelRentalBookingRequestOpts(requestParameters: CancelRentalBookingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling cancelRentalBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings/{bookingId}/cancel`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async cancelRentalBookingRaw(requestParameters: CancelRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBooking>> {
        const requestOptions = await this.cancelRentalBookingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalBookingFromJSON(jsonValue));
    }

    /**
     */
    async cancelRentalBooking(requestParameters: CancelRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBooking> {
        const response = await this.cancelRentalBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRentalBooking without sending the request
     */
    async createRentalBookingRequestOpts(requestParameters: CreateRentalBookingOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createRentalBooking().'
            );
        }

        if (requestParameters['createRentalBookingRequest'] == null) {
            throw new runtime.RequiredError(
                'createRentalBookingRequest',
                'Required parameter "createRentalBookingRequest" was null or undefined when calling createRentalBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRentalBookingRequestToJSON(requestParameters['createRentalBookingRequest']),
        };
    }

    /**
     */
    async createRentalBookingRaw(requestParameters: CreateRentalBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBooking>> {
        const requestOptions = await this.createRentalBookingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalBookingFromJSON(jsonValue));
    }

    /**
     */
    async createRentalBooking(requestParameters: CreateRentalBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBooking> {
        const response = await this.createRentalBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalAvailability without sending the request
     */
    async getRentalAvailabilityRequestOpts(requestParameters: GetRentalAvailabilityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getRentalAvailability().'
            );
        }

        if (requestParameters['fromDate'] == null) {
            throw new runtime.RequiredError(
                'fromDate',
                'Required parameter "fromDate" was null or undefined when calling getRentalAvailability().'
            );
        }

        if (requestParameters['toDate'] == null) {
            throw new runtime.RequiredError(
                'toDate',
                'Required parameter "toDate" was null or undefined when calling getRentalAvailability().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fromDate'] != null) {
            queryParameters['fromDate'] = runtime.serializeDate(requestParameters['fromDate'] as any);
        }

        if (requestParameters['toDate'] != null) {
            queryParameters['toDate'] = runtime.serializeDate(requestParameters['toDate'] as any);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/rental/properties/{propertyId}/availability`;
        urlPath = urlPath.replace('{propertyId}', encodeURIComponent(String(requestParameters['propertyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalAvailabilityRaw(requestParameters: GetRentalAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalAvailability>> {
        const requestOptions = await this.getRentalAvailabilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalAvailabilityFromJSON(jsonValue));
    }

    /**
     */
    async getRentalAvailability(requestParameters: GetRentalAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalAvailability> {
        const response = await this.getRentalAvailabilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalBooking without sending the request
     */
    async getRentalBookingRequestOpts(requestParameters: GetRentalBookingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling getRentalBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings/{bookingId}`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalBookingRaw(requestParameters: GetRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBooking>> {
        const requestOptions = await this.getRentalBookingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalBookingFromJSON(jsonValue));
    }

    /**
     */
    async getRentalBooking(requestParameters: GetRentalBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBooking> {
        const response = await this.getRentalBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalBookings without sending the request
     */
    async getRentalBookingsRequestOpts(requestParameters: GetRentalBookingsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalBookingsRaw(requestParameters: GetRentalBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalBookingCursorPage>> {
        const requestOptions = await this.getRentalBookingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalBookingCursorPageFromJSON(jsonValue));
    }

    /**
     */
    async getRentalBookings(requestParameters: GetRentalBookingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalBookingCursorPage> {
        const response = await this.getRentalBookingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalCleaningContext without sending the request
     */
    async getRentalCleaningContextRequestOpts(requestParameters: GetRentalCleaningContextRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling getRentalCleaningContext().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings/{bookingId}/cleaning-context`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalCleaningContextRaw(requestParameters: GetRentalCleaningContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalCleaningContext>> {
        const requestOptions = await this.getRentalCleaningContextRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalCleaningContextFromJSON(jsonValue));
    }

    /**
     */
    async getRentalCleaningContext(requestParameters: GetRentalCleaningContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalCleaningContext> {
        const response = await this.getRentalCleaningContextRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalConfiguration without sending the request
     */
    async getRentalConfigurationRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/rental/configuration`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalConfiguration>> {
        const requestOptions = await this.getRentalConfigurationRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalConfigurationFromJSON(jsonValue));
    }

    /**
     */
    async getRentalConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalConfiguration> {
        const response = await this.getRentalConfigurationRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalProperty without sending the request
     */
    async getRentalPropertyRequestOpts(requestParameters: GetRentalPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getRentalProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/rental/properties/{slug}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalPropertyRaw(requestParameters: GetRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalProperty>> {
        const requestOptions = await this.getRentalPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalPropertyFromJSON(jsonValue));
    }

    /**
     */
    async getRentalProperty(requestParameters: GetRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalProperty> {
        const response = await this.getRentalPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalPropertyMedia without sending the request
     */
    async getRentalPropertyMediaRequestOpts(requestParameters: GetRentalPropertyMediaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getRentalPropertyMedia().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling getRentalPropertyMedia().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['v'] != null) {
            queryParameters['v'] = requestParameters['v'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/rental/properties/{propertyId}/media/{mediaId}`;
        urlPath = urlPath.replace('{propertyId}', encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalPropertyMediaRaw(requestParameters: GetRentalPropertyMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getRentalPropertyMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async getRentalPropertyMedia(requestParameters: GetRentalPropertyMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getRentalPropertyMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalPropertyMediaVariant without sending the request
     */
    async getRentalPropertyMediaVariantRequestOpts(requestParameters: GetRentalPropertyMediaVariantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getRentalPropertyMediaVariant().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling getRentalPropertyMediaVariant().'
            );
        }

        if (requestParameters['variant'] == null) {
            throw new runtime.RequiredError(
                'variant',
                'Required parameter "variant" was null or undefined when calling getRentalPropertyMediaVariant().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['v'] != null) {
            queryParameters['v'] = requestParameters['v'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/rental/properties/{propertyId}/media/{mediaId}/{variant}`;
        urlPath = urlPath.replace('{propertyId}', encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));
        urlPath = urlPath.replace('{variant}', encodeURIComponent(String(requestParameters['variant'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalPropertyMediaVariantRaw(requestParameters: GetRentalPropertyMediaVariantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getRentalPropertyMediaVariantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async getRentalPropertyMediaVariant(requestParameters: GetRentalPropertyMediaVariantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getRentalPropertyMediaVariantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalTransferContext without sending the request
     */
    async getRentalTransferContextRequestOpts(requestParameters: GetRentalTransferContextRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling getRentalTransferContext().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings/{bookingId}/transfer-context`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalTransferContextRaw(requestParameters: GetRentalTransferContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalTransferContext>> {
        const requestOptions = await this.getRentalTransferContextRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalTransferContextFromJSON(jsonValue));
    }

    /**
     */
    async getRentalTransferContext(requestParameters: GetRentalTransferContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalTransferContext> {
        const response = await this.getRentalTransferContextRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRentalTransferPrefill without sending the request
     */
    async getRentalTransferPrefillRequestOpts(requestParameters: GetRentalTransferPrefillRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling getRentalTransferPrefill().'
            );
        }

        if (requestParameters['context'] == null) {
            throw new runtime.RequiredError(
                'context',
                'Required parameter "context" was null or undefined when calling getRentalTransferPrefill().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings/{bookingId}/transfer-context/{context}/prefill`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));
        urlPath = urlPath.replace('{context}', encodeURIComponent(String(requestParameters['context'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRentalTransferPrefillRaw(requestParameters: GetRentalTransferPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalTransferPrefill>> {
        const requestOptions = await this.getRentalTransferPrefillRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalTransferPrefillFromJSON(jsonValue));
    }

    /**
     */
    async getRentalTransferPrefill(requestParameters: GetRentalTransferPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalTransferPrefill> {
        const response = await this.getRentalTransferPrefillRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for quoteRentalProperty without sending the request
     */
    async quoteRentalPropertyRequestOpts(requestParameters: QuoteRentalPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling quoteRentalProperty().'
            );
        }

        if (requestParameters['termType'] == null) {
            throw new runtime.RequiredError(
                'termType',
                'Required parameter "termType" was null or undefined when calling quoteRentalProperty().'
            );
        }

        if (requestParameters['checkInDate'] == null) {
            throw new runtime.RequiredError(
                'checkInDate',
                'Required parameter "checkInDate" was null or undefined when calling quoteRentalProperty().'
            );
        }

        if (requestParameters['guests'] == null) {
            throw new runtime.RequiredError(
                'guests',
                'Required parameter "guests" was null or undefined when calling quoteRentalProperty().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['termType'] != null) {
            queryParameters['termType'] = requestParameters['termType'];
        }

        if (requestParameters['checkInDate'] != null) {
            queryParameters['checkInDate'] = runtime.serializeDate(requestParameters['checkInDate'] as any);
        }

        if (requestParameters['checkOutDate'] != null) {
            queryParameters['checkOutDate'] = runtime.serializeDate(requestParameters['checkOutDate'] as any);
        }

        if (requestParameters['months'] != null) {
            queryParameters['months'] = requestParameters['months'];
        }

        if (requestParameters['guests'] != null) {
            queryParameters['guests'] = requestParameters['guests'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/rental/properties/{propertyId}/quote`;
        urlPath = urlPath.replace('{propertyId}', encodeURIComponent(String(requestParameters['propertyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async quoteRentalPropertyRaw(requestParameters: QuoteRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalQuote>> {
        const requestOptions = await this.quoteRentalPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalQuoteFromJSON(jsonValue));
    }

    /**
     */
    async quoteRentalProperty(requestParameters: QuoteRentalPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalQuote> {
        const response = await this.quoteRentalPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recordRentalFirstCard without sending the request
     */
    async recordRentalFirstCardRequestOpts(requestParameters: RecordRentalFirstCardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['executionId'] == null) {
            throw new runtime.RequiredError(
                'executionId',
                'Required parameter "executionId" was null or undefined when calling recordRentalFirstCard().'
            );
        }

        if (requestParameters['rentalFirstCardRequest'] == null) {
            throw new runtime.RequiredError(
                'rentalFirstCardRequest',
                'Required parameter "rentalFirstCardRequest" was null or undefined when calling recordRentalFirstCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/rental/searches/{executionId}/first-card`;
        urlPath = urlPath.replace('{executionId}', encodeURIComponent(String(requestParameters['executionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RentalFirstCardRequestToJSON(requestParameters['rentalFirstCardRequest']),
        };
    }

    /**
     */
    async recordRentalFirstCardRaw(requestParameters: RecordRentalFirstCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.recordRentalFirstCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async recordRentalFirstCard(requestParameters: RecordRentalFirstCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordRentalFirstCardRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for recordRentalSearchOpened without sending the request
     */
    async recordRentalSearchOpenedRequestOpts(requestParameters: RecordRentalSearchOpenedRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['executionId'] == null) {
            throw new runtime.RequiredError(
                'executionId',
                'Required parameter "executionId" was null or undefined when calling recordRentalSearchOpened().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/rental/searches/{executionId}/opened`;
        urlPath = urlPath.replace('{executionId}', encodeURIComponent(String(requestParameters['executionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async recordRentalSearchOpenedRaw(requestParameters: RecordRentalSearchOpenedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.recordRentalSearchOpenedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async recordRentalSearchOpened(requestParameters: RecordRentalSearchOpenedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordRentalSearchOpenedRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for recordRentalTransferContextShown without sending the request
     */
    async recordRentalTransferContextShownRequestOpts(requestParameters: RecordRentalTransferContextShownRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling recordRentalTransferContextShown().'
            );
        }

        if (requestParameters['context'] == null) {
            throw new runtime.RequiredError(
                'context',
                'Required parameter "context" was null or undefined when calling recordRentalTransferContextShown().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rental/bookings/{bookingId}/transfer-context/{context}/shown`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));
        urlPath = urlPath.replace('{context}', encodeURIComponent(String(requestParameters['context'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async recordRentalTransferContextShownRaw(requestParameters: RecordRentalTransferContextShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.recordRentalTransferContextShownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async recordRentalTransferContextShown(requestParameters: RecordRentalTransferContextShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordRentalTransferContextShownRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for searchRentalProperties without sending the request
     */
    async searchRentalPropertiesRequestOpts(requestParameters: SearchRentalPropertiesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['termType'] != null) {
            queryParameters['termType'] = requestParameters['termType'];
        }

        if (requestParameters['checkInDate'] != null) {
            queryParameters['checkInDate'] = runtime.serializeDate(requestParameters['checkInDate'] as any);
        }

        if (requestParameters['checkOutDate'] != null) {
            queryParameters['checkOutDate'] = runtime.serializeDate(requestParameters['checkOutDate'] as any);
        }

        if (requestParameters['months'] != null) {
            queryParameters['months'] = requestParameters['months'];
        }

        if (requestParameters['guests'] != null) {
            queryParameters['guests'] = requestParameters['guests'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRentalPreviousSearchId'] != null) {
            headerParameters['X-Rental-Previous-Search-Id'] = String(requestParameters['xRentalPreviousSearchId']);
        }


        let urlPath = `/api/v1/rental/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async searchRentalPropertiesRaw(requestParameters: SearchRentalPropertiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RentalSearch>> {
        const requestOptions = await this.searchRentalPropertiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RentalSearchFromJSON(jsonValue));
    }

    /**
     */
    async searchRentalProperties(requestParameters: SearchRentalPropertiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RentalSearch> {
        const response = await this.searchRentalPropertiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetRentalPropertyMediaVariantVariantEnum = {
    Card: 'card',
    Thumbnail: 'thumbnail',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type GetRentalPropertyMediaVariantVariantEnum = typeof GetRentalPropertyMediaVariantVariantEnum[keyof typeof GetRentalPropertyMediaVariantVariantEnum];
/**
 * @export
 */
export const GetRentalTransferPrefillContextEnum = {
    Arrival: 'ARRIVAL',
    Checkout: 'CHECKOUT',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type GetRentalTransferPrefillContextEnum = typeof GetRentalTransferPrefillContextEnum[keyof typeof GetRentalTransferPrefillContextEnum];
/**
 * @export
 */
export const RecordRentalTransferContextShownContextEnum = {
    Arrival: 'ARRIVAL',
    Checkout: 'CHECKOUT',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type RecordRentalTransferContextShownContextEnum = typeof RecordRentalTransferContextShownContextEnum[keyof typeof RecordRentalTransferContextShownContextEnum];
