/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateSupportCaseRequest,
    CreateSupportCaseRequestFromJSON,
    CreateSupportCaseRequestToJSON,
} from '../models/CreateSupportCaseRequest';
import {
    type CreateTransactionFeedbackRequest,
    CreateTransactionFeedbackRequestFromJSON,
    CreateTransactionFeedbackRequestToJSON,
} from '../models/CreateTransactionFeedbackRequest';
import {
    type SupportCase,
    SupportCaseFromJSON,
    SupportCaseToJSON,
} from '../models/SupportCase';
import {
    type TransactionSupport,
    TransactionSupportFromJSON,
    TransactionSupportToJSON,
} from '../models/TransactionSupport';

export interface CreateSupportCaseOperationRequest {
    /**
     * 
     */
    createSupportCaseRequest: CreateSupportCaseRequest;
}

export interface GetTransactionSupportRequest {
    /**
     * 
     */
    service: GetTransactionSupportServiceEnum;
    /**
     * 
     */
    sourceEntityId: number;
}

export interface SubmitTransactionFeedbackRequest {
    /**
     * 
     */
    createTransactionFeedbackRequest: CreateTransactionFeedbackRequest;
}

/**
 * SupportApi - interface
 * 
 * @export
 * @interface SupportApiInterface
 */
export interface SupportApiInterface {
    /**
     * Creates request options for createSupportCase without sending the request
     * @param {CreateSupportCaseRequest} createSupportCaseRequest 
     * @throws {RequiredError}
     * @memberof SupportApiInterface
     */
    createSupportCaseRequestOpts(requestParameters: CreateSupportCaseOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateSupportCaseRequest} createSupportCaseRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportApiInterface
     */
    createSupportCaseRaw(requestParameters: CreateSupportCaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupportCase>>;

    /**
     */
    createSupportCase(requestParameters: CreateSupportCaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupportCase>;

    /**
     * Creates request options for getTransactionSupport without sending the request
     * @param {'CLEANING' | 'RENTAL' | 'TRANSFER'} service 
     * @param {number} sourceEntityId 
     * @throws {RequiredError}
     * @memberof SupportApiInterface
     */
    getTransactionSupportRequestOpts(requestParameters: GetTransactionSupportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {'CLEANING' | 'RENTAL' | 'TRANSFER'} service 
     * @param {number} sourceEntityId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportApiInterface
     */
    getTransactionSupportRaw(requestParameters: GetTransactionSupportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionSupport>>;

    /**
     */
    getTransactionSupport(requestParameters: GetTransactionSupportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionSupport>;

    /**
     * Creates request options for submitTransactionFeedback without sending the request
     * @param {CreateTransactionFeedbackRequest} createTransactionFeedbackRequest 
     * @throws {RequiredError}
     * @memberof SupportApiInterface
     */
    submitTransactionFeedbackRequestOpts(requestParameters: SubmitTransactionFeedbackRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateTransactionFeedbackRequest} createTransactionFeedbackRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportApiInterface
     */
    submitTransactionFeedbackRaw(requestParameters: SubmitTransactionFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionSupport>>;

    /**
     */
    submitTransactionFeedback(requestParameters: SubmitTransactionFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionSupport>;

}

/**
 * 
 */
export class SupportApi extends runtime.BaseAPI implements SupportApiInterface {

    /**
     * Creates request options for createSupportCase without sending the request
     */
    async createSupportCaseRequestOpts(requestParameters: CreateSupportCaseOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSupportCaseRequest'] == null) {
            throw new runtime.RequiredError(
                'createSupportCaseRequest',
                'Required parameter "createSupportCaseRequest" was null or undefined when calling createSupportCase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/support/cases`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSupportCaseRequestToJSON(requestParameters['createSupportCaseRequest']),
        };
    }

    /**
     */
    async createSupportCaseRaw(requestParameters: CreateSupportCaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupportCase>> {
        const requestOptions = await this.createSupportCaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupportCaseFromJSON(jsonValue));
    }

    /**
     */
    async createSupportCase(requestParameters: CreateSupportCaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupportCase> {
        const response = await this.createSupportCaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransactionSupport without sending the request
     */
    async getTransactionSupportRequestOpts(requestParameters: GetTransactionSupportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling getTransactionSupport().'
            );
        }

        if (requestParameters['sourceEntityId'] == null) {
            throw new runtime.RequiredError(
                'sourceEntityId',
                'Required parameter "sourceEntityId" was null or undefined when calling getTransactionSupport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/support/sources/{service}/{sourceEntityId}`;
        urlPath = urlPath.replace('{service}', encodeURIComponent(String(requestParameters['service'])));
        urlPath = urlPath.replace('{sourceEntityId}', encodeURIComponent(String(requestParameters['sourceEntityId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTransactionSupportRaw(requestParameters: GetTransactionSupportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionSupport>> {
        const requestOptions = await this.getTransactionSupportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionSupportFromJSON(jsonValue));
    }

    /**
     */
    async getTransactionSupport(requestParameters: GetTransactionSupportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionSupport> {
        const response = await this.getTransactionSupportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitTransactionFeedback without sending the request
     */
    async submitTransactionFeedbackRequestOpts(requestParameters: SubmitTransactionFeedbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTransactionFeedbackRequest'] == null) {
            throw new runtime.RequiredError(
                'createTransactionFeedbackRequest',
                'Required parameter "createTransactionFeedbackRequest" was null or undefined when calling submitTransactionFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/support/feedback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTransactionFeedbackRequestToJSON(requestParameters['createTransactionFeedbackRequest']),
        };
    }

    /**
     */
    async submitTransactionFeedbackRaw(requestParameters: SubmitTransactionFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionSupport>> {
        const requestOptions = await this.submitTransactionFeedbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionSupportFromJSON(jsonValue));
    }

    /**
     */
    async submitTransactionFeedback(requestParameters: SubmitTransactionFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionSupport> {
        const response = await this.submitTransactionFeedbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetTransactionSupportServiceEnum = {
    Cleaning: 'CLEANING',
    Rental: 'RENTAL',
    Transfer: 'TRANSFER',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type GetTransactionSupportServiceEnum = typeof GetTransactionSupportServiceEnum[keyof typeof GetTransactionSupportServiceEnum];
