/* tslint:disable */
/* eslint-disable */
/**
 * Loco Place Public API
 * Channel-neutral public contract for web, Telegram Mini App and native clients. Unknown enum values must be preserved by generated clients as UNKNOWN rather than causing decoding failure. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateTransferBookingRequest,
    CreateTransferBookingRequestFromJSON,
    CreateTransferBookingRequestToJSON,
} from '../models/CreateTransferBookingRequest';
import {
    type TransferBooking,
    TransferBookingFromJSON,
    TransferBookingToJSON,
} from '../models/TransferBooking';
import {
    type TransferBookingCursorPage,
    TransferBookingCursorPageFromJSON,
    TransferBookingCursorPageToJSON,
} from '../models/TransferBookingCursorPage';
import {
    type TransferConfiguration,
    TransferConfigurationFromJSON,
    TransferConfigurationToJSON,
} from '../models/TransferConfiguration';
import {
    type TransferQuote,
    TransferQuoteFromJSON,
    TransferQuoteToJSON,
} from '../models/TransferQuote';
import {
    type TransferQuoteRequest,
    TransferQuoteRequestFromJSON,
    TransferQuoteRequestToJSON,
} from '../models/TransferQuoteRequest';
import {
    type TransferRepeatPrefill,
    TransferRepeatPrefillFromJSON,
    TransferRepeatPrefillToJSON,
} from '../models/TransferRepeatPrefill';

export interface CancelTransferBookingRequest {
    /**
     * 
     */
    bookingId: number;
}

export interface CreateTransferBookingOperationRequest {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    createTransferBookingRequest: CreateTransferBookingRequest;
}

export interface GetTransferBookingRequest {
    /**
     * 
     */
    bookingId: number;
}

export interface GetTransferBookingsRequest {
    /**
     * 
     */
    cursor?: string;
    /**
     * 
     */
    size?: number;
}

export interface GetTransferRepeatPrefillRequest {
    /**
     * 
     */
    bookingId: number;
}

export interface QuoteTransferRequest {
    /**
     * 
     */
    transferQuoteRequest: TransferQuoteRequest;
}

export interface RecordTransferRepeatShownRequest {
    /**
     * 
     */
    bookingId: number;
}

/**
 * TransferApi - interface
 * 
 * @export
 * @interface TransferApiInterface
 */
export interface TransferApiInterface {
    /**
     * Creates request options for cancelTransferBooking without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    cancelTransferBookingRequestOpts(requestParameters: CancelTransferBookingRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    cancelTransferBookingRaw(requestParameters: CancelTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBooking>>;

    /**
     */
    cancelTransferBooking(requestParameters: CancelTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBooking>;

    /**
     * Creates request options for createTransferBooking without sending the request
     * @param {string} idempotencyKey 
     * @param {CreateTransferBookingRequest} createTransferBookingRequest 
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    createTransferBookingRequestOpts(requestParameters: CreateTransferBookingOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {CreateTransferBookingRequest} createTransferBookingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    createTransferBookingRaw(requestParameters: CreateTransferBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBooking>>;

    /**
     */
    createTransferBooking(requestParameters: CreateTransferBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBooking>;

    /**
     * Creates request options for getTransferBooking without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferBookingRequestOpts(requestParameters: GetTransferBookingRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferBookingRaw(requestParameters: GetTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBooking>>;

    /**
     */
    getTransferBooking(requestParameters: GetTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBooking>;

    /**
     * Creates request options for getTransferBookings without sending the request
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferBookingsRequestOpts(requestParameters: GetTransferBookingsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [cursor] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferBookingsRaw(requestParameters: GetTransferBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBookingCursorPage>>;

    /**
     */
    getTransferBookings(requestParameters: GetTransferBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBookingCursorPage>;

    /**
     * Creates request options for getTransferConfiguration without sending the request
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferConfigurationRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferConfiguration>>;

    /**
     */
    getTransferConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferConfiguration>;

    /**
     * Creates request options for getTransferRepeatPrefill without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferRepeatPrefillRequestOpts(requestParameters: GetTransferRepeatPrefillRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    getTransferRepeatPrefillRaw(requestParameters: GetTransferRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferRepeatPrefill>>;

    /**
     */
    getTransferRepeatPrefill(requestParameters: GetTransferRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferRepeatPrefill>;

    /**
     * Creates request options for quoteTransfer without sending the request
     * @param {TransferQuoteRequest} transferQuoteRequest 
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    quoteTransferRequestOpts(requestParameters: QuoteTransferRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {TransferQuoteRequest} transferQuoteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    quoteTransferRaw(requestParameters: QuoteTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferQuote>>;

    /**
     */
    quoteTransfer(requestParameters: QuoteTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferQuote>;

    /**
     * Creates request options for recordTransferRepeatShown without sending the request
     * @param {number} bookingId 
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    recordTransferRepeatShownRequestOpts(requestParameters: RecordTransferRepeatShownRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} bookingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    recordTransferRepeatShownRaw(requestParameters: RecordTransferRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    recordTransferRepeatShown(requestParameters: RecordTransferRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class TransferApi extends runtime.BaseAPI implements TransferApiInterface {

    /**
     * Creates request options for cancelTransferBooking without sending the request
     */
    async cancelTransferBookingRequestOpts(requestParameters: CancelTransferBookingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling cancelTransferBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/bookings/{bookingId}/cancel`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async cancelTransferBookingRaw(requestParameters: CancelTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBooking>> {
        const requestOptions = await this.cancelTransferBookingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferBookingFromJSON(jsonValue));
    }

    /**
     */
    async cancelTransferBooking(requestParameters: CancelTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBooking> {
        const response = await this.cancelTransferBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTransferBooking without sending the request
     */
    async createTransferBookingRequestOpts(requestParameters: CreateTransferBookingOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createTransferBooking().'
            );
        }

        if (requestParameters['createTransferBookingRequest'] == null) {
            throw new runtime.RequiredError(
                'createTransferBookingRequest',
                'Required parameter "createTransferBookingRequest" was null or undefined when calling createTransferBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/bookings`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTransferBookingRequestToJSON(requestParameters['createTransferBookingRequest']),
        };
    }

    /**
     */
    async createTransferBookingRaw(requestParameters: CreateTransferBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBooking>> {
        const requestOptions = await this.createTransferBookingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferBookingFromJSON(jsonValue));
    }

    /**
     */
    async createTransferBooking(requestParameters: CreateTransferBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBooking> {
        const response = await this.createTransferBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransferBooking without sending the request
     */
    async getTransferBookingRequestOpts(requestParameters: GetTransferBookingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling getTransferBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/bookings/{bookingId}`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTransferBookingRaw(requestParameters: GetTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBooking>> {
        const requestOptions = await this.getTransferBookingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferBookingFromJSON(jsonValue));
    }

    /**
     */
    async getTransferBooking(requestParameters: GetTransferBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBooking> {
        const response = await this.getTransferBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransferBookings without sending the request
     */
    async getTransferBookingsRequestOpts(requestParameters: GetTransferBookingsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/bookings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTransferBookingsRaw(requestParameters: GetTransferBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBookingCursorPage>> {
        const requestOptions = await this.getTransferBookingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferBookingCursorPageFromJSON(jsonValue));
    }

    /**
     */
    async getTransferBookings(requestParameters: GetTransferBookingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBookingCursorPage> {
        const response = await this.getTransferBookingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransferConfiguration without sending the request
     */
    async getTransferConfigurationRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/configuration`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTransferConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferConfiguration>> {
        const requestOptions = await this.getTransferConfigurationRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferConfigurationFromJSON(jsonValue));
    }

    /**
     */
    async getTransferConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferConfiguration> {
        const response = await this.getTransferConfigurationRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransferRepeatPrefill without sending the request
     */
    async getTransferRepeatPrefillRequestOpts(requestParameters: GetTransferRepeatPrefillRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling getTransferRepeatPrefill().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/bookings/{bookingId}/repeat-prefill`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTransferRepeatPrefillRaw(requestParameters: GetTransferRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferRepeatPrefill>> {
        const requestOptions = await this.getTransferRepeatPrefillRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferRepeatPrefillFromJSON(jsonValue));
    }

    /**
     */
    async getTransferRepeatPrefill(requestParameters: GetTransferRepeatPrefillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferRepeatPrefill> {
        const response = await this.getTransferRepeatPrefillRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for quoteTransfer without sending the request
     */
    async quoteTransferRequestOpts(requestParameters: QuoteTransferRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transferQuoteRequest'] == null) {
            throw new runtime.RequiredError(
                'transferQuoteRequest',
                'Required parameter "transferQuoteRequest" was null or undefined when calling quoteTransfer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/quote`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferQuoteRequestToJSON(requestParameters['transferQuoteRequest']),
        };
    }

    /**
     */
    async quoteTransferRaw(requestParameters: QuoteTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferQuote>> {
        const requestOptions = await this.quoteTransferRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferQuoteFromJSON(jsonValue));
    }

    /**
     */
    async quoteTransfer(requestParameters: QuoteTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferQuote> {
        const response = await this.quoteTransferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recordTransferRepeatShown without sending the request
     */
    async recordTransferRepeatShownRequestOpts(requestParameters: RecordTransferRepeatShownRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling recordTransferRepeatShown().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfer/bookings/{bookingId}/repeat-shown`;
        urlPath = urlPath.replace('{bookingId}', encodeURIComponent(String(requestParameters['bookingId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async recordTransferRepeatShownRaw(requestParameters: RecordTransferRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.recordTransferRepeatShownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async recordTransferRepeatShown(requestParameters: RecordTransferRepeatShownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordTransferRepeatShownRaw(requestParameters, initOverrides);
    }

}
