package com.cleany.notification;

public enum CustomerNotificationType {
    CLEANING_ORDER_ACCEPTED,
    CLEANING_ORDER_CANCELLED,
    CLEANING_ORDER_COMPLETED,
    CLEANING_ONSITE_ISSUE_REPORTED,
    RENTAL_BOOKING_CONFIRMED,
    RENTAL_BOOKING_CANCELLED,
    TRANSFER_REQUESTED,
    TRANSFER_CONFIRMED,
    TRANSFER_REJECTED,
    TRANSFER_CANCELLED,
    TRANSFER_COMPLETED,
    TRANSFER_ADMIN_REQUESTED,
    REFERRAL_UNLOCKED,
    RENTAL_CLEANING_BENEFIT_AVAILABLE
}
